/*
 * CODE GENERATED BY cmd/harbor-protocol-ts-types. DO NOT EDIT.
 * Run 'make protocol-ts-types-gen' to regenerate from the canonical
 * Harbor Protocol single sources (internal/protocol/{types,methods,errors}
 * + the canonical event-type set). This is a vendorable external-client
 * wire-type module: copy it into your TypeScript client and keep it fresh
 * by re-vendoring after a Harbor upgrade. It is independent of the
 * Console's hand-maintained protocol.ts and of the committed wire
 * manifest; it carries no client logic, only types.
 */

/** The Harbor Protocol version this module was generated against (RFC §5.3). */
export const PROTOCOL_VERSION = "0.1.0";

/**
 * The canonical wire-surface digest the runtime reports on `runtime.info`.
 * Compare it against the live runtime's digest to detect a wire skew
 * between what you vendored and what the runtime speaks.
 */
export const WIRE_SURFACE_DIGEST = "sha256:f47c6ed217211a93e1b1c153c80801e05727835689f64a730578966f57f7f7de";

/** Every canonical Harbor Protocol method name. */
export type HarborMethod =
  | "agent_config.add_mcp_connection"
  | "agent_config.diff"
  | "agent_config.get"
  | "agent_config.list_revisions"
  | "agent_config.remove_mcp_connection"
  | "agent_config.remove_oauth_provider"
  | "agent_config.rollback"
  | "agent_config.session.set_source_disables"
  | "agent_config.session.set_user_prompt"
  | "agent_config.session.skills.delete"
  | "agent_config.session.skills.list"
  | "agent_config.session.skills.upsert"
  | "agent_config.set_llm_params"
  | "agent_config.set_mcp_discovery_origins"
  | "agent_config.set_oauth_provider"
  | "agent_config.set_prompt_layers"
  | "agent_config.set_revision"
  | "agent_config.set_tool_exposure"
  | "agent_config.skills.delete"
  | "agent_config.skills.list"
  | "agent_config.skills.upsert"
  | "agent_config.user.diff"
  | "agent_config.user.get"
  | "agent_config.user.list_revisions"
  | "agent_config.user.rollback"
  | "agent_config.user.set_revision"
  | "agents.deregister"
  | "agents.drain"
  | "agents.force_stop"
  | "agents.get"
  | "agents.governance"
  | "agents.list"
  | "agents.memory"
  | "agents.metrics"
  | "agents.pause"
  | "agents.permissions"
  | "agents.restart"
  | "agents.skills"
  | "agents.tools"
  | "approve"
  | "artifacts.delete"
  | "artifacts.get_ref"
  | "artifacts.list"
  | "artifacts.put"
  | "auth.rotate_token"
  | "cancel"
  | "events.aggregate"
  | "events.list"
  | "events.subscribe"
  | "flows.describe"
  | "flows.list"
  | "flows.metrics"
  | "flows.run"
  | "flows.runs.describe"
  | "flows.runs.list"
  | "governance.get_tenant_overrides"
  | "governance.posture"
  | "governance.rotate_key"
  | "governance.set_tenant_overrides"
  | "inject_context"
  | "llm.posture"
  | "mcp.apps.call_tool"
  | "mcp.apps.tool_context"
  | "mcp.servers.bindings.list"
  | "mcp.servers.get"
  | "mcp.servers.health"
  | "mcp.servers.list"
  | "mcp.servers.policy"
  | "mcp.servers.probe"
  | "mcp.servers.prompts"
  | "mcp.servers.read_resource"
  | "mcp.servers.refresh_binding"
  | "mcp.servers.refresh_discovery"
  | "mcp.servers.resources"
  | "mcp.servers.revoke_binding"
  | "mcp.servers.set_raw_html_trust"
  | "memory.delete"
  | "memory.get"
  | "memory.health"
  | "memory.list"
  | "memory.put"
  | "memory.strategy_trace"
  | "metrics.snapshot"
  | "pause"
  | "pause.list"
  | "prioritize"
  | "redirect"
  | "reject"
  | "resume"
  | "runs.set_overrides"
  | "runtime.counters"
  | "runtime.drivers"
  | "runtime.health"
  | "runtime.info"
  | "search.artifacts"
  | "search.events"
  | "search.query"
  | "search.sessions"
  | "search.tasks"
  | "sessions.delete"
  | "sessions.inspect"
  | "sessions.list"
  | "sessions.set_title"
  | "start"
  | "state.history"
  | "tasks.get"
  | "tasks.list"
  | "tools.content_stats"
  | "tools.describe"
  | "tools.get"
  | "tools.list"
  | "tools.metrics"
  | "tools.revoke_oauth"
  | "tools.set_approval_policy"
  | "topology.snapshot"
  | "user_message";

/** Every canonical Harbor Protocol error code. */
export type HarborErrorCode =
  | "auth_rejected"
  | "identity_required"
  | "identity_scope_required"
  | "invalid_request"
  | "not_found"
  | "payload_invalid"
  | "presign_unsupported"
  | "request_too_large"
  | "runtime_error"
  | "scope_mismatch"
  | "session_erased"
  | "session_running"
  | "unknown_method";

/** Every canonical Harbor event-type wire string. */
export type HarborEventType =
  | "agent.config.reverted"
  | "agent.config.revised"
  | "agent.deregistered"
  | "agent.drained"
  | "agent.force_stopped"
  | "agent.health"
  | "agent.paused"
  | "agent.registered"
  | "agent.restart_requested"
  | "agent.restarted"
  | "agent_config.oauth_provider.installed"
  | "agent_config.oauth_provider.removed"
  | "artifacts.deleted"
  | "artifacts.uploaded"
  | "audit.admin_scope_used"
  | "audit.redaction_failed"
  | "auth.rejected"
  | "bus.dropped"
  | "bus.subscription_idle_closed"
  | "control.applied"
  | "control.received"
  | "control.rejected"
  | "dev.draft.created"
  | "dev.draft.discarded"
  | "dev.draft.previewed"
  | "dev.draft.saved"
  | "dev.draft.updated"
  | "distributed.bus_envelope"
  | "flow.budget_exceeded"
  | "flows.page_viewed"
  | "flows.run_invoked"
  | "governance.budget_exceeded"
  | "governance.key_rotated"
  | "governance.maxtokens_exceeded"
  | "governance.posture_read_admin"
  | "governance.rate_limited"
  | "governance.tenant_overrides_set"
  | "llm.completion.chunk"
  | "llm.context_leak"
  | "llm.context_window_exceeded"
  | "llm.cost.recorded"
  | "llm.image.materialized"
  | "llm.mode_downgraded"
  | "llm.posture_read_admin"
  | "llm.provider_file.uploaded"
  | "llm.retry_with_feedback"
  | "mcp.app_available"
  | "mcp.connection.added"
  | "mcp.connection.auth_required"
  | "mcp.connection.discovery_origins_set"
  | "mcp.connection.failed"
  | "mcp.connection.paused"
  | "mcp.connection.pending"
  | "mcp.connection.removed"
  | "mcp.connection.resumed"
  | "mcp.raw_html_trust_toggled"
  | "mcp.resource_offloaded"
  | "mcp.resource_updated"
  | "memory.health_changed"
  | "memory.identity_rejected"
  | "memory.item_deleted"
  | "memory.item_put"
  | "memory.recovery_dropped"
  | "notification.auth_required"
  | "notification.governance_budget_exceeded"
  | "notification.identity_rejected"
  | "notification.pause_requested"
  | "notification.task_completed"
  | "notification.task_failed"
  | "notification.task_group_resolved"
  | "notification.tool_approval_requested"
  | "pause.payload_artifact_routed"
  | "pause.requested"
  | "pause.resumed"
  | "planner.action_extra_field_dropped"
  | "planner.decision"
  | "planner.error"
  | "planner.finish"
  | "planner.max_steps_exceeded"
  | "planner.repair_exhausted"
  | "planner.repair_guidance_injected"
  | "run.hook_dispatched"
  | "run.hook_failed"
  | "runs.overrides_set"
  | "runtime.error"
  | "runtime.run_cancelled"
  | "runtime.warning"
  | "session.closed"
  | "session.erased"
  | "session.gc_reaped"
  | "session.naming_failed"
  | "session.opened"
  | "session.reopened"
  | "session.title_changed"
  | "session.touched"
  | "skill.deleted"
  | "skill.identity_rejected"
  | "skill.pack_overwrite_refused"
  | "skill.proposed"
  | "skill.search_executed"
  | "skill.upserted"
  | "task.background_acknowledged"
  | "task.cancelled"
  | "task.completed"
  | "task.failed"
  | "task.group_cancelled"
  | "task.group_created"
  | "task.group_resolved"
  | "task.group_sealed"
  | "task.input_disposition.resolved"
  | "task.patch_applied"
  | "task.patch_rejected"
  | "task.paused"
  | "task.prioritised"
  | "task.resumed"
  | "task.spawned"
  | "task.started"
  | "tool.approval_requested"
  | "tool.approved"
  | "tool.auth_completed"
  | "tool.auth_required"
  | "tool.completed"
  | "tool.credential_exchanged"
  | "tool.failed"
  | "tool.invalid_args"
  | "tool.invoked"
  | "tool.policy_exhausted"
  | "tool.provider_credential_fetch_failed"
  | "tool.provider_credential_fetched"
  | "tool.rejected"
  | "topology.changed"
  | "trajectory.compressed"
  | "trajectory.compression_failed";

export interface Agent {
  id: string;
  name: string;
  description: string;
  incarnation: number;
  version_hash: string;
  owner: string;
  status: string;
  health: string;
  hosting: string;
  planner_type: string;
  model: string;
  tools_count: number;
  mcp_count: number;
  registered_at: string;
  updated_at: string;
  identity: IdentityScope;
  is_default?: boolean;
}

export interface AgentAggregates {
  total: number;
  active: number;
  paused: number;
  drained: number;
}

export interface AgentConfig {
  planner_type: string;
  planner_config?: Record<string, string>;
  model: string;
  model_policy?: Record<string, string>;
  max_steps: number;
}

export interface AgentConfigAddMCPConnectionRequest {
  identity: IdentityScope;
  agent_id: string;
  connection: AgentConfigMCPConnectionDescriptor;
  headers?: Record<string, string>;
}

export interface AgentConfigAddMCPConnectionResponse {
  revision?: AgentConfigRevisionView;
  connection: AgentConfigMCPConnectionDescriptor;
  state: string;
  reason?: string;
  pause_token?: string;
  protocol_version: string;
}

export interface AgentConfigConnections {
  servers?: AgentConfigMCPConnectionDescriptor[];
}

export interface AgentConfigConnectionsDiff {
  added?: string[];
  removed?: string[];
}

export interface AgentConfigDiff {
  from_revision_id: string;
  to_revision_id: string;
  skills: AgentConfigSkillsDiff;
  tool_exposure: AgentConfigToolExposureDiff;
  prompt_layers: AgentConfigPromptLayersDiff;
  connections: AgentConfigConnectionsDiff;
  oauth_providers: AgentConfigOAuthProvidersDiff;
  llm_params: AgentConfigLLMParamsDiff;
  hooks: AgentConfigHooksDiff;
  naming: AgentConfigNamingDiff;
}

export interface AgentConfigDiffRequest {
  identity: IdentityScope;
  agent_id: string;
  from_revision: string;
  to_revision: string;
}

export interface AgentConfigDiffResponse {
  diff: AgentConfigDiff;
  protocol_version: string;
}

export interface AgentConfigGetRequest {
  identity: IdentityScope;
  agent_id: string;
}

export interface AgentConfigGetResponse {
  revision?: AgentConfigRevisionView;
  set: boolean;
  protocol_version: string;
}

export interface AgentConfigHooks {
  run_completion?: AgentConfigRunCompletionHook;
}

export interface AgentConfigHooksDiff {
  section_present_changed: boolean;
  section_present_from?: string;
  section_present_to?: string;
  run_completion_tool_changed: boolean;
  run_completion_tool_from?: string;
  run_completion_tool_to?: string;
  run_completion_timeout_changed: boolean;
  run_completion_timeout_from?: string;
  run_completion_timeout_to?: string;
}

export interface AgentConfigLLMParams {
  model?: string;
  temperature?: number;
  max_tokens?: number;
  reasoning_effort?: string;
}

export interface AgentConfigLLMParamsDiff {
  model_changed: boolean;
  model_from?: string;
  model_to?: string;
  temperature_changed: boolean;
  temperature_from?: string;
  temperature_to?: string;
  max_tokens_changed: boolean;
  max_tokens_from?: string;
  max_tokens_to?: string;
  reasoning_effort_changed: boolean;
  reasoning_effort_from?: string;
  reasoning_effort_to?: string;
}

export interface AgentConfigListRevisionsRequest {
  identity: IdentityScope;
  agent_id: string;
  limit?: number;
}

export interface AgentConfigListRevisionsResponse {
  revisions: AgentConfigRevisionView[];
  protocol_version: string;
}

export interface AgentConfigLoadingModeChange {
  key: string;
  from?: string;
  to?: string;
}

export interface AgentConfigMCPConnectionDescriptor {
  name: string;
  transport: string;
  command?: string[];
  url?: string;
  oauth_provider?: string;
  meta_annotations?: Record<string, string>;
  oauth_discovery_allowed_origins?: string[];
}

export interface AgentConfigNaming {
  auto?: boolean;
  after_turns?: number;
  repeat_every?: number;
  max_repetitions?: number;
  max_title_len?: number;
  model?: string;
}

export interface AgentConfigNamingDiff {
  auto_changed: boolean;
  auto_from?: string;
  auto_to?: string;
  after_turns_changed: boolean;
  after_turns_from?: string;
  after_turns_to?: string;
  repeat_every_changed: boolean;
  repeat_every_from?: string;
  repeat_every_to?: string;
  max_repetitions_changed: boolean;
  max_repetitions_from?: string;
  max_repetitions_to?: string;
  max_title_len_changed: boolean;
  max_title_len_from?: string;
  max_title_len_to?: string;
  model_changed: boolean;
  model_from?: string;
  model_to?: string;
}

export interface AgentConfigOAuthProviderDescriptor {
  name: string;
  driver: string;
  credential_source: string;
  credential_broker: string;
  scopes?: string[];
}

export interface AgentConfigOAuthProviders {
  providers?: AgentConfigOAuthProviderDescriptor[];
}

export interface AgentConfigOAuthProvidersDiff {
  added?: string[];
  removed?: string[];
}

export interface AgentConfigPayload {
  prompt_layers?: AgentConfigPromptLayers;
  skills?: AgentConfigSkillsSelection;
  tool_exposure?: AgentConfigToolExposure;
  connections?: AgentConfigConnections;
  oauth_providers?: AgentConfigOAuthProviders;
  llm_params?: AgentConfigLLMParams;
  hooks?: AgentConfigHooks;
  naming?: AgentConfigNaming;
}

export interface AgentConfigPromptLayers {
  base?: string;
  user?: string;
}

export interface AgentConfigPromptLayersDiff {
  base_changed: boolean;
  base_from?: string;
  base_to?: string;
  user_changed: boolean;
  user_from?: string;
  user_to?: string;
}

export interface AgentConfigRemoveMCPConnectionRequest {
  identity: IdentityScope;
  agent_id: string;
  name: string;
}

export interface AgentConfigRemoveMCPConnectionResponse {
  revision: AgentConfigRevisionView;
  name: string;
  protocol_version: string;
}

export interface AgentConfigRemoveOAuthProviderRequest {
  identity: IdentityScope;
  agent_id: string;
  name: string;
}

export interface AgentConfigRemoveOAuthProviderResponse {
  revision: AgentConfigRevisionView;
  name: string;
  uninstalled: boolean;
  protocol_version: string;
}

export interface AgentConfigRevisionView {
  revision_id: string;
  parent_revision_id?: string;
  content_hash: string;
  author_tenant?: string;
  author_user?: string;
  created_at: string;
  payload: AgentConfigPayload;
}

export interface AgentConfigRollbackRequest {
  identity: IdentityScope;
  agent_id: string;
  revision_id: string;
}

export interface AgentConfigRollbackResponse {
  revision: AgentConfigRevisionView;
  protocol_version: string;
}

export interface AgentConfigRunCompletionHook {
  tool: string;
  timeout_ms?: number;
}

export interface AgentConfigSessionOverlay {
  user_prompt?: string;
  disabled_servers?: string[];
  disabled_tools?: string[];
  personal_skills?: string[];
}

export interface AgentConfigSessionSetSourceDisablesRequest {
  identity: IdentityScope;
  agent_id: string;
  disabled_servers?: string[];
  disabled_tools?: string[];
}

export interface AgentConfigSessionSetSourceDisablesResponse {
  overlay: AgentConfigSessionOverlay;
  protocol_version: string;
}

export interface AgentConfigSessionSetUserPromptRequest {
  identity: IdentityScope;
  agent_id: string;
  user_prompt: string;
}

export interface AgentConfigSessionSetUserPromptResponse {
  overlay: AgentConfigSessionOverlay;
  protocol_version: string;
}

export interface AgentConfigSessionSkillsDeleteRequest {
  identity: IdentityScope;
  agent_id: string;
  name: string;
}

export interface AgentConfigSessionSkillsDeleteResponse {
  overlay: AgentConfigSessionOverlay;
  protocol_version: string;
}

export interface AgentConfigSessionSkillsListRequest {
  identity: IdentityScope;
  agent_id: string;
}

export interface AgentConfigSessionSkillsListResponse {
  skills: AgentConfigSkillSummary[];
  protocol_version: string;
}

export interface AgentConfigSessionSkillsUpsertRequest {
  identity: IdentityScope;
  agent_id: string;
  skill: AgentConfigSkillInput;
}

export interface AgentConfigSessionSkillsUpsertResponse {
  skill: AgentConfigSkillSummary;
  overlay: AgentConfigSessionOverlay;
  protocol_version: string;
}

export interface AgentConfigSetLLMParamsRequest {
  identity: IdentityScope;
  agent_id: string;
  llm_params: AgentConfigLLMParams;
}

export interface AgentConfigSetLLMParamsResponse {
  revision: AgentConfigRevisionView;
  protocol_version: string;
}

export interface AgentConfigSetMCPDiscoveryOriginsRequest {
  identity: IdentityScope;
  agent_id: string;
  name: string;
  allowed_origins: string[];
}

export interface AgentConfigSetMCPDiscoveryOriginsResponse {
  revision: AgentConfigRevisionView;
  name: string;
  granted?: string[];
  revoked?: string[];
  applied_live: boolean;
  protocol_version: string;
}

export interface AgentConfigSetOAuthProviderRequest {
  identity: IdentityScope;
  agent_id: string;
  provider: AgentConfigOAuthProviderDescriptor;
}

export interface AgentConfigSetOAuthProviderResponse {
  revision: AgentConfigRevisionView;
  name: string;
  protocol_version: string;
}

export interface AgentConfigSetPromptLayersRequest {
  identity: IdentityScope;
  agent_id: string;
  prompt_layers: AgentConfigPromptLayers;
}

export interface AgentConfigSetPromptLayersResponse {
  revision: AgentConfigRevisionView;
  protocol_version: string;
}

export interface AgentConfigSetRevisionRequest {
  identity: IdentityScope;
  agent_id: string;
  payload: AgentConfigPayload;
}

export interface AgentConfigSetRevisionResponse {
  revision: AgentConfigRevisionView;
  protocol_version: string;
}

export interface AgentConfigSetToolExposureRequest {
  identity: IdentityScope;
  agent_id: string;
  tool_exposure: AgentConfigToolExposure;
}

export interface AgentConfigSetToolExposureResponse {
  revision: AgentConfigRevisionView;
  protocol_version: string;
}

export interface AgentConfigSkillInput {
  name: string;
  title?: string;
  description?: string;
  trigger: string;
  task_type?: string;
  tags?: string[];
  steps: string[];
  origin: string;
  scope: string;
}

export interface AgentConfigSkillSummary {
  name: string;
  title?: string;
  trigger?: string;
  task_type?: string;
  origin: string;
  scope: string;
  content_hash?: string;
  updated_at: string;
}

export interface AgentConfigSkillsDeleteRequest {
  identity: IdentityScope;
  agent_id: string;
  name: string;
}

export interface AgentConfigSkillsDeleteResponse {
  revision: AgentConfigRevisionView;
  protocol_version: string;
}

export interface AgentConfigSkillsDiff {
  added?: string[];
  removed?: string[];
}

export interface AgentConfigSkillsListRequest {
  identity: IdentityScope;
  agent_id: string;
}

export interface AgentConfigSkillsListResponse {
  skills: AgentConfigSkillSummary[];
  protocol_version: string;
}

export interface AgentConfigSkillsSelection {
  names: string[];
}

export interface AgentConfigSkillsUpsertRequest {
  identity: IdentityScope;
  agent_id: string;
  skill: AgentConfigSkillInput;
}

export interface AgentConfigSkillsUpsertResponse {
  revision: AgentConfigRevisionView;
  skill: AgentConfigSkillSummary;
  protocol_version: string;
}

export interface AgentConfigToolExposure {
  paused_servers?: string[];
  disabled_tools?: string[];
  server_loading_modes?: Record<string, string>;
  tool_loading_modes?: Record<string, string>;
}

export interface AgentConfigToolExposureDiff {
  paused_added?: string[];
  paused_resumed?: string[];
  disabled_added?: string[];
  disabled_enabled?: string[];
  server_loading_changes?: AgentConfigLoadingModeChange[];
  tool_loading_changes?: AgentConfigLoadingModeChange[];
}

export interface AgentConfigUserDiffRequest {
  identity: IdentityScope;
  agent_id: string;
  from_revision: string;
  to_revision: string;
}

export interface AgentConfigUserDiffResponse {
  diff: AgentConfigDiff;
  protocol_version: string;
}

export interface AgentConfigUserGetRequest {
  identity: IdentityScope;
  agent_id: string;
}

export interface AgentConfigUserGetResponse {
  revision?: AgentConfigRevisionView;
  set: boolean;
  protocol_version: string;
}

export interface AgentConfigUserListRevisionsRequest {
  identity: IdentityScope;
  agent_id: string;
  limit?: number;
}

export interface AgentConfigUserListRevisionsResponse {
  revisions: AgentConfigRevisionView[];
  protocol_version: string;
}

export interface AgentConfigUserPayload {
  user_prompt?: string;
  disabled_servers?: string[];
  disabled_tools?: string[];
  personal_skills?: string[];
}

export interface AgentConfigUserRollbackRequest {
  identity: IdentityScope;
  agent_id: string;
  revision_id: string;
}

export interface AgentConfigUserRollbackResponse {
  revision: AgentConfigRevisionView;
  protocol_version: string;
}

export interface AgentConfigUserSetRevisionRequest {
  identity: IdentityScope;
  agent_id: string;
  payload: AgentConfigUserPayload;
}

export interface AgentConfigUserSetRevisionResponse {
  revision: AgentConfigRevisionView;
  protocol_version: string;
}

export interface AgentControlRequest {
  identity: IdentityScope;
  id: string;
  reason?: string;
}

export interface AgentControlResponse {
  agent_id: string;
  command: string;
  status: string;
}

export interface AgentCostCeiling {
  tier: string;
  limit_usd: number;
  spend_usd: number;
}

export interface AgentFilter {
  status?: string[];
  planner_type?: string[];
  search?: string;
  tenant_ids?: string[];
}

export interface AgentGetRequest {
  identity: IdentityScope;
  id: string;
}

export interface AgentGetResponse {
  agent: Agent;
  config: AgentConfig;
  agent_card_ref?: string;
}

export interface AgentGovernance {
  ceilings: AgentCostCeiling[];
  rate_limits: AgentRateLimit[];
}

export interface AgentGovernanceRequest {
  identity: IdentityScope;
  id: string;
}

export interface AgentGovernanceResponse {
  agent_id: string;
  governance: AgentGovernance;
}

export interface AgentListRequest {
  identity: IdentityScope;
  filter?: AgentFilter;
  page?: number;
  page_size?: number;
}

export interface AgentListResponse {
  agents: Agent[];
  page: number;
  page_size: number;
  page_count: number;
  total_rows: number;
  aggregates: AgentAggregates;
}

export interface AgentMemoryBinding {
  strategy_id: string;
  ttl_seconds: number;
  scope: string;
}

export interface AgentMemoryRequest {
  identity: IdentityScope;
  id: string;
}

export interface AgentMemoryResponse {
  agent_id: string;
  binding: AgentMemoryBinding;
}

export interface AgentMetrics {
  active_agents: number;
  running_tasks: number;
  total_cost_usd: number;
  total_tokens: number;
}

export interface AgentMetricsRequest {
  identity: IdentityScope;
}

export interface AgentMetricsResponse {
  metrics: AgentMetrics;
}

export interface AgentPermissions {
  model: string;
  description: string;
  allowed_principals?: string[];
}

export interface AgentPermissionsRequest {
  identity: IdentityScope;
  id: string;
}

export interface AgentPermissionsResponse {
  agent_id: string;
  permissions: AgentPermissions;
}

export interface AgentRateLimit {
  tier: string;
  requests_per_minute: number;
  max_tokens: number;
}

export interface AgentSkillBinding {
  skill_id: string;
  name: string;
  generated: boolean;
}

export interface AgentSkillsRequest {
  identity: IdentityScope;
  id: string;
}

export interface AgentSkillsResponse {
  agent_id: string;
  skills: AgentSkillBinding[];
}

export interface AgentToolBinding {
  tool_id: string;
  tool_name: string;
  transport: string;
  auth_status: string;
  binding_scope?: string;
}

export interface AgentToolsRequest {
  identity: IdentityScope;
  id: string;
}

export interface AgentToolsResponse {
  agent_id: string;
  bindings: AgentToolBinding[];
}

export interface ArtifactRef {
  id: string;
  mime_type?: string;
  size_bytes: number;
  filename?: string;
  sha256?: string;
  namespace?: string;
  scope: ArtifactScope;
}

export interface ArtifactRefSummary {
  filename: string;
  mime: string;
  size_bytes: number;
  created_at: string;
}

export interface ArtifactRow {
  ref: ArtifactRef;
  tags?: string[];
  source?: string;
  driver?: string;
  created_at?: string;
}

export interface ArtifactScope {
  tenant: string;
  user: string;
  session: string;
  task?: string;
}

export interface ArtifactsDeleteRequest {
  scope: ArtifactScope;
  id: string;
}

export interface ArtifactsDeleteResponse {
  deleted: boolean;
  protocol_version: string;
}

export interface ArtifactsGetRefRequest {
  scope: ArtifactScope;
  id: string;
  expiry?: number;
}

export interface ArtifactsGetRefResponse {
  ref: ArtifactRef;
  presigned_url: string;
  expires_at: string;
  protocol_version: string;
}

export interface ArtifactsListRequest {
  scope: ArtifactScope;
  mime_type?: string[];
  source?: string[];
  size_range?: SizeRange;
  created_range?: TimeRange;
  tags?: string[];
  limit?: number;
}

export interface ArtifactsListResponse {
  rows: ArtifactRow[];
  total_matched: number;
  protocol_version: string;
}

export interface ArtifactsPutOpts {
  mime_type?: string;
  filename?: string;
  namespace?: string;
  source?: string;
  tags?: string[];
}

export interface ArtifactsPutRequest {
  scope: ArtifactScope;
  bytes: string;
  opts?: ArtifactsPutOpts;
}

export interface ArtifactsPutResponse {
  ref: ArtifactRef;
  protocol_version: string;
}

export interface AuthRotateTokenRequest {
  identity: IdentityScope;
}

export interface AuthRotateTokenResponse {
  new_token: string;
  expires_at: string;
}

export interface ControlRequest {
  identity: IdentityScope;
  payload?: Record<string, unknown>;
  event_id?: string;
}

export interface ControlResponse {
  accepted: boolean;
  method: string;
  protocol_version: string;
}

export interface Deprecation {
  subject: string;
  kind: string;
  deprecated_in: string;
  removed_in: string;
  replacement?: string;
  note?: string;
}

export interface Error {
  code: string;
  message: string;
}

export interface EventAggregateRequest {
  identity?: IdentityScope;
  filter: EventFilter;
  window: number;
  bucket: number;
  anchor?: string;
  by_tenant?: boolean;
}

export interface EventAggregateResponse {
  buckets: EventBucket[];
  truncated?: boolean;
  protocol_version: string;
}

export interface EventBucket {
  bucket_start: string;
  bucket_end: string;
  counts: Record<string, number>;
  counts_by_tenant?: Record<string, Record<string, number>>;
}

export interface EventFilter {
  event_types?: string[];
  tenant_ids?: string[];
  user_ids?: string[];
  session_ids?: string[];
  run_ids?: string[];
  since?: string;
  until?: string;
}

export interface EventsListRequest {
  identity?: IdentityScope;
  filter: EventFilter;
  cursor?: number;
  limit?: number;
}

export interface EventsListResponse {
  events: StateEvent[];
  next_cursor: number;
  has_more: boolean;
  truncated?: boolean;
}

export interface Flow {
  id: string;
  name: string;
  owner?: string;
  version?: string;
  planner_family?: string;
  node_count: number;
  edge_count: number;
  runs_24h: number;
  p50_latency_ms: number;
  p95_latency_ms: number;
  success_rate: number;
  last_run?: string;
  budget: FlowBudget;
}

export interface FlowArtifactRef {
  id: string;
  mime_type?: string;
  size_bytes?: number;
  filename?: string;
  sha256?: string;
}

export interface FlowBudget {
  deadline_ms?: number;
  request_cap?: number;
  cost_cap_usd?: number;
  token_cap?: number;
}

export interface FlowBudgetConsumption {
  requests_used: number;
  cost_usd_used: number;
  tokens_used: number;
}

export interface FlowDescribeRequest {
  identity: IdentityScope;
  id: string;
}

export interface FlowDescription {
  flow: Flow;
  nodes: FlowNode[];
  edges: FlowEdge[];
  source?: string;
  budget_consumption: FlowBudgetConsumption;
}

export interface FlowEdge {
  from: string;
  to: string;
}

export interface FlowFilter {
  tenants?: string[];
  planner_families?: string[];
  query?: string;
}

export interface FlowListRequest {
  identity: IdentityScope;
  filter: FlowFilter;
  page?: number;
  page_size?: number;
}

export interface FlowListResponse {
  flows: Flow[];
  page: number;
  page_size: number;
  page_count: number;
  total_rows: number;
}

export interface FlowMetrics {
  flow_id: string;
  window_start: string;
  window_end: string;
  buckets: FlowMetricsBucket[];
  budget_consumption: FlowBudgetConsumption;
}

export interface FlowMetricsBucket {
  bucket_start: string;
  runs: number;
  p95_latency_ms: number;
  success_rate: number;
  cost_usd: number;
}

export interface FlowMetricsRequest {
  identity: IdentityScope;
  flow_id: string;
  window_ms?: number;
  bucket_ms?: number;
}

export interface FlowNode {
  id: string;
  type: string;
  descriptor?: string;
  policy?: FlowNodePolicy;
}

export interface FlowNodePolicy {
  max_retries?: number;
  timeout_ms?: number;
}

export interface FlowNodeRunState {
  node_id: string;
  status: string;
  duration_ms?: number;
  retries?: number;
  error_class?: string;
}

export interface FlowRun {
  run_id: string;
  flow_id: string;
  status: string;
  trigger: string;
  started_at: string;
  duration_ms?: number;
  cost_usd?: number;
  identity: IdentityScope;
  error_class?: string;
}

export interface FlowRunDescribeRequest {
  identity: IdentityScope;
  run_id: string;
}

export interface FlowRunDescription {
  run: FlowRun;
  node_states: FlowNodeRunState[];
  output_preview?: string;
  output_ref?: FlowArtifactRef;
}

export interface FlowRunRequest {
  identity: IdentityScope;
  flow_id: string;
  inputs?: Record<string, unknown>;
}

export interface FlowRunResponse {
  run_id: string;
  status: string;
  started_at: string;
}

export interface FlowRunsListRequest {
  identity: IdentityScope;
  flow_id: string;
  tenants?: string[];
  page?: number;
  page_size?: number;
  since?: string;
  until?: string;
}

export interface FlowRunsListResponse {
  runs: FlowRun[];
  page: number;
  page_size: number;
  page_count: number;
  total_rows: number;
}

export interface GovernanceGetTenantOverridesRequest {
  identity: IdentityScope;
}

export interface GovernanceGetTenantOverridesResponse {
  overrides: GovernanceTenantOverrides;
  set: boolean;
  protocol_version: string;
}

export interface GovernancePostureRequest {
  tenant_id?: string;
}

export interface GovernancePostureResponse {
  default_tier: string;
  resolved_tier: string;
  identity_tiers: Record<string, IdentityTierView>;
  protocol_version: string;
}

export interface GovernanceRotateKeyRequest {
  identity: IdentityScope;
  provider?: string;
  key: string;
}

export interface GovernanceRotateKeyResponse {
  provider: string;
  fingerprint: string;
  rotated_at: string;
  protocol_version: string;
}

export interface GovernanceSetTenantOverridesRequest {
  identity: IdentityScope;
  overrides: GovernanceTenantOverrides;
}

export interface GovernanceSetTenantOverridesResponse {
  applied_at: string;
  protocol_version: string;
}

export interface GovernanceTenantOverrides {
  model?: string;
  extra_instructions?: string;
  temperature?: number;
  max_tokens?: number;
  reasoning_effort?: string;
}

export interface HistogramBucket {
  upper_bound: number;
  count: number;
}

export interface IdentityScope {
  tenant: string;
  user: string;
  session: string;
  run?: string;
  scope?: string;
  actor?: IdentityScope;
  requester?: IdentityScope;
  impersonating?: IdentityScope;
}

export interface IdentityTierView {
  budget_ceiling_usd: number;
  rate_limit: RateLimitView;
  max_tokens: number;
}

export interface InterventionSummary {
  type: string;
  reason: string;
  outcome: string;
  occurred_at: string;
}

export interface LLMPostureRequest {
  tenant_id?: string;
}

export interface LLMPostureResponse {
  provider: string;
  model: string;
  region: string;
  mock_mode: boolean;
  protocol_version: string;
}

export interface MCPAppCallToolRequest {
  identity: IdentityScope;
  tool: string;
  arguments?: unknown;
}

export interface MCPAppCallToolResponse {
  tool: string;
  content?: unknown;
  artifact_ref?: MCPResourceArtifactRef;
  is_error: boolean;
  app?: MCPAppRef;
  protocol_version: string;
}

export interface MCPAppRef {
  server_id?: string;
  tool_call_id?: string;
  resource_uri: string;
  display_mode?: string;
  raw_html_trusted: boolean;
}

export interface MCPAuthorizationServerView {
  issuer: string;
  authorization_endpoint: string;
  token_endpoint: string;
  scopes_supported: string[];
  code_challenge_methods_supported: string[];
  registration_endpoint?: string;
  resource?: string;
  source_url: string;
}

export interface MCPBindingScopeCount {
  binding_scope: string;
  count: number;
}

export interface MCPBindingView {
  principal_id: string;
  binding_scope: string;
  scopes: string[];
  expires_at: string;
  last_used_at: string;
}

export interface MCPDiscoveryStepStatusView {
  step: string;
  target: string;
  ok: boolean;
  reason?: string;
  detail?: string;
}

export interface MCPHealthBucket {
  start_ms: number;
  latency_ms: number;
}

export interface MCPOAuthRequirementView {
  resource_metadata_url: string;
  authorization_servers: MCPAuthorizationServerView[];
  discovered_at: string;
  source: string;
  source_url: string;
  status: MCPDiscoveryStepStatusView[];
}

export interface MCPPromptArg {
  name: string;
  description?: string;
  required: boolean;
}

export interface MCPPromptView {
  name: string;
  description?: string;
  arguments: MCPPromptArg[];
}

export interface MCPReconnect {
  occurred_at: string;
  reason?: string;
}

export interface MCPResourceArtifactRef {
  id: string;
  mime_type?: string;
  size_bytes?: number;
  filename?: string;
  sha256?: string;
}

export interface MCPResourceView {
  uri: string;
  mime_type?: string;
  size_bytes?: number;
  name?: string;
  title?: string;
}

export interface MCPScopeShortfallView {
  tool_name: string;
  downstream_resource: string;
  required_scopes: string[];
  granted_scopes: string[];
  www_authenticate: string;
  origin: string;
  observed_at: string;
}

export interface MCPServerBindingsListRequest {
  identity: IdentityScope;
  name: string;
}

export interface MCPServerBindingsListResponse {
  bindings: MCPBindingView[];
  protocol_version: string;
}

export interface MCPServerGetRequest {
  identity: IdentityScope;
  name: string;
}

export interface MCPServerGetResponse {
  server: MCPServerView;
  display_modes_advertised: string[];
  content_shapes: string[];
  tool_policy: MCPToolPolicyView;
  bindings_summary: MCPBindingScopeCount[];
  protocol_version: string;
}

export interface MCPServerHealthRequest {
  identity: IdentityScope;
  name: string;
}

export interface MCPServerHealthResponse {
  handshake_latency_buckets: MCPHealthBucket[];
  reconnect_history: MCPReconnect[];
  transport_error_rate: number;
  protocol_version: string;
}

export interface MCPServerPolicyRequest {
  identity: IdentityScope;
  name: string;
}

export interface MCPServerPolicyResponse {
  tool_policy: MCPToolPolicyView;
  protocol_version: string;
}

export interface MCPServerProbeRequest {
  identity: IdentityScope;
  name: string;
}

export interface MCPServerProbeResponse {
  ok: boolean;
  latency_ms: number;
  error?: string;
  protocol_version: string;
}

export interface MCPServerPromptsRequest {
  identity: IdentityScope;
  name: string;
}

export interface MCPServerPromptsResponse {
  prompts: MCPPromptView[];
  protocol_version: string;
}

export interface MCPServerRefreshBindingRequest {
  identity: IdentityScope;
  name: string;
  principal_id?: string;
}

export interface MCPServerRefreshBindingResponse {
  authorize_url: string;
  state: string;
  protocol_version: string;
}

export interface MCPServerRefreshDiscoveryRequest {
  identity: IdentityScope;
  name: string;
}

export interface MCPServerRefreshDiscoveryResponse {
  discovery_id: string;
  tool_count: number;
  resource_count: number;
  prompt_count: number;
  protocol_version: string;
}

export interface MCPServerResourcesRequest {
  identity: IdentityScope;
  name: string;
}

export interface MCPServerResourcesResponse {
  resources: MCPResourceView[];
  protocol_version: string;
}

export interface MCPServerRevokeBindingRequest {
  identity: IdentityScope;
  name: string;
  principal_id?: string;
}

export interface MCPServerRevokeBindingResponse {
  revoked: boolean;
  protocol_version: string;
}

export interface MCPServerSetRawHTMLTrustRequest {
  identity: IdentityScope;
  name: string;
  trusted: boolean;
}

export interface MCPServerSetRawHTMLTrustResponse {
  name: string;
  trusted: boolean;
  protocol_version: string;
}

export interface MCPServerView {
  name: string;
  transport: string;
  url_or_command: string;
  state: string;
  last_discovery_at: string;
  tool_count: number;
  resource_count: number;
  prompt_count: number;
  recent_latency_ms: number;
  error_rate_per_min: number;
  oauth_binding_count: number;
  raw_html_trusted: boolean;
  oauth_requirement?: MCPOAuthRequirementView;
  last_scope_shortfall?: MCPScopeShortfallView;
}

export interface MCPServersListRequest {
  identity: IdentityScope;
  state?: string[];
  transport?: string[];
  has_oauth?: boolean;
  has_recent_error?: boolean;
  name_prefix?: string;
  page_token?: string;
  page_size?: number;
}

export interface MCPServersListResponse {
  servers: MCPServerView[];
  next_page_token?: string;
  protocol_version: string;
}

export interface MCPToolPolicyView {
  timeout_ms: number;
  max_retries: number;
  concurrency_cap: number;
}

export interface MemoryAggregates {
  total: number;
  identity_rejected_24h: number;
  recovery_dropped_24h: number;
}

export interface MemoryArtifactRef {
  id: string;
  mime_type?: string;
  size_bytes?: number;
  filename?: string;
  sha256?: string;
}

export interface MemoryDeleteRequest {
  identity: IdentityScope;
  key: string;
}

export interface MemoryDeleteResponse {
  deleted: boolean;
  remaining_turns: number;
  protocol_version: string;
}

export interface MemoryFilter {
  tenant_ids?: string[];
  user_ids?: string[];
  session_ids?: string[];
  agent_ids?: string[];
  scopes?: string[];
  drivers?: string[];
  strategies?: string[];
  content_search?: string;
}

export interface MemoryGetRequest {
  identity: IdentityScope;
  key: string;
}

export interface MemoryGetResponse {
  detail: MemoryItemDetail;
  protocol_version: string;
}

export interface MemoryHealthAggregate {
  total: number;
  identity_rejected_24h: number;
  recovery_dropped_24h: number;
  driver_by_scope: Record<string, string>;
}

export interface MemoryHealthRequest {
  identity: IdentityScope;
}

export interface MemoryHealthResponse {
  aggregate: MemoryHealthAggregate;
  protocol_version: string;
}

export interface MemoryItem {
  key: string;
  strategy: string;
  scope: string;
  identity: IdentityScope;
  agent_id?: string;
  created_at: string;
  last_updated_at: string;
  expires_at?: string;
  size_bytes: number;
  heavy_content?: boolean;
  driver: string;
}

export interface MemoryItemDetail {
  item: MemoryItem;
  value?: string;
  value_artifact?: MemoryArtifactRef;
  metadata: MemoryMetadata;
}

export interface MemoryListRequest {
  identity: IdentityScope;
  filter?: MemoryFilter;
  page?: number;
  page_size?: number;
}

export interface MemoryListResponse {
  items: MemoryItem[];
  page: number;
  page_size: number;
  page_count: number;
  total_rows: number;
  aggregates: MemoryAggregates;
  protocol_version: string;
}

export interface MemoryMetadata {
  ttl?: number;
  strategy_config?: Record<string, string>;
  related_event_ids?: string[];
}

export interface MemoryPutRequest {
  identity: IdentityScope;
  turn: MemoryTurnInput;
}

export interface MemoryPutResponse {
  key: string;
  protocol_version: string;
}

export interface MemoryStrategyTrace {
  strategy: string;
  summary: string;
  recent_turn_count: number;
  estimated_tokens: number;
  health: string;
}

export interface MemoryStrategyTraceRequest {
  identity: IdentityScope;
}

export interface MemoryStrategyTraceResponse {
  trace: MemoryStrategyTrace;
  protocol_version: string;
}

export interface MemoryTurnInput {
  user_text: string;
  assistant_text: string;
}

export interface MetricsSnapshot {
  counters: NamedCounter[];
  histograms: NamedHistogram[];
  gauges: NamedGauge[];
  snapshot_at: number;
}

export interface NamedCounter {
  name: string;
  value: number;
  labels?: Record<string, string>;
}

export interface NamedGauge {
  name: string;
  value: number;
  labels?: Record<string, string>;
}

export interface NamedHistogram {
  name: string;
  count: number;
  sum: number;
  buckets?: HistogramBucket[];
  labels?: Record<string, string>;
}

export interface PauseArtifactRef {
  id: string;
  mime_type?: string;
  size_bytes?: number;
  filename?: string;
  sha256?: string;
}

export interface PauseFilter {
  status?: string[];
  tenant_ids?: string[];
  user_ids?: string[];
  session_ids?: string[];
  run_ids?: string[];
  reasons?: string[];
  since?: string;
  until?: string;
}

export interface PauseListRequest {
  identity: IdentityScope;
  filter?: PauseFilter;
  page?: number;
  page_size?: number;
}

export interface PauseListResponse {
  snapshots: PauseSnapshot[];
  page: number;
  page_size: number;
  page_count: number;
  total_rows: number;
  truncated?: boolean;
}

export interface PauseSnapshot {
  token: string;
  reason: string;
  state: string;
  identity: IdentityScope;
  paused_at: string;
  resumed_at?: string;
  payload?: Record<string, unknown>;
  payload_ref?: PauseArtifactRef;
}

export interface RateLimitView {
  capacity: number;
  refill_tokens: number;
  refill_interval_ms: number;
}

export interface ReadMCPResourceRequest {
  identity: IdentityScope;
  server_id: string;
  resource_uri: string;
}

export interface ReadMCPResourceResponse {
  resource_uri: string;
  mime_type?: string;
  content?: string;
  artifact_ref?: MCPResourceArtifactRef;
  protocol_version: string;
}

export interface RetentionHorizon {
  surface: string;
  scope?: string;
  oldest_retained_at?: string;
}

export interface RunOverrides {
  session_id: string;
  reasoning_effort?: string;
  temperature?: number;
  max_tokens?: number;
  system_prompt_override?: string;
  model?: string;
}

export interface RunSetOverridesRequest {
  identity: IdentityScope;
  overrides: RunOverrides;
}

export interface RunSetOverridesResponse {
  applied_at: string;
  protocol_version: string;
}

export interface RuntimeCounters {
  events_per_second: number;
  tasks_running: number;
  background_jobs_active: number;
  mcp_connections_healthy: number;
  sessions_active: number;
  snapshot_at: number;
}

export interface RuntimeDrivers {
  subsystems: SubsystemDriver[];
}

export interface RuntimeHealth {
  subsystems: SubsystemHealth[];
  retention?: RetentionHorizon[];
}

export interface RuntimeInfo {
  instance_id: string;
  display_name?: string;
  build_version: string;
  build_commit: string;
  build_date?: string;
  build_go_version: string;
  protocol_version: string;
  capabilities: string[];
  uptime_seconds: number;
  mcp_app_display_modes?: string[];
  wire_surface_digest: string;
}

export interface RuntimeInfoRequest {
  identity: IdentityScope;
}

export interface SearchArtifactRef {
  id: string;
  mime_type?: string;
  size_bytes?: number;
  filename?: string;
  sha256?: string;
}

export interface SearchFacet {
  key: string;
  value: string;
}

export interface SearchFilter {
  tenant_ids?: string[];
  user_ids?: string[];
  session_ids?: string[];
  since?: string;
  until?: string;
}

export interface SearchRequest {
  query?: string;
  indexes?: string[];
  filter?: SearchFilter;
  facets?: SearchFacet[];
  page?: number;
  page_size?: number;
}

export interface SearchResponse {
  rows: SearchResultRow[];
  page: number;
  page_size: number;
  page_count: number;
  total_count: number;
  has_more: boolean;
  protocol_version: string;
}

export interface SearchResultRow {
  index: string;
  id: string;
  tenant_id: string;
  user_id: string;
  session_id: string;
  run_id?: string;
  occurred_at?: string;
  preview?: string;
  ref?: SearchArtifactRef;
  facets?: Record<string, string>;
}

export interface SessionFilter {
  statuses?: string[];
  agent_ids?: string[];
  user_ids?: string[];
  tenant_ids?: string[];
  started_window?: Window;
  has_intervention?: boolean;
  has_failed_task?: boolean;
  cost_above_cents?: number;
  query?: string;
}

export interface SessionRow {
  session_id: string;
  status: string;
  agent_id?: string;
  agent_name?: string;
  user_id: string;
  tenant_id: string;
  started_at: string;
  last_activity_at: string;
  duration: number;
  tasks_count: number;
  events_count: number;
  total_cost_cents: number;
  total_tokens: number;
  has_pending_intervention: boolean;
  has_failed_task: boolean;
  identity: IdentityScope;
  title?: string;
  title_source?: string;
  counters_partial?: boolean;
}

export interface SessionsDeleteRequest {
  identity: IdentityScope;
}

export interface SessionsDeleteResponse {
  session_id: string;
  deleted: boolean;
  state_records_deleted: number;
  artifacts_deleted: number;
  memory_purged: boolean;
}

export interface SessionsInspectRequest {
  identity: IdentityScope;
  session_id: string;
}

export interface SessionsInspectResponse {
  row: SessionRow;
  recent_interventions: InterventionSummary[];
  recent_artifacts: ArtifactRefSummary[];
}

export interface SessionsListRequest {
  identity: IdentityScope;
  filter: SessionFilter;
  sort?: string;
  cursor?: string;
  limit?: number;
}

export interface SessionsListResponse {
  rows: SessionRow[];
  next_cursor: string;
  truncated: boolean;
}

export interface SessionsSetTitleRequest {
  identity: IdentityScope;
  session_id: string;
  title: string;
}

export interface SessionsSetTitleResponse {
  session_id: string;
  title: string;
  title_source: string;
}

export interface SizeRange {
  min_bytes?: number;
  max_bytes?: number;
}

export interface StartRequest {
  identity: IdentityScope;
  query?: string;
  description?: string;
  priority?: number;
  idempotency_key?: string;
  input_artifact_ids?: string[];
  input_artifact_dispositions?: Record<string, string>;
  output_schema?: unknown;
}

export interface StartResponse {
  task_id: string;
  reused: boolean;
  protocol_version: string;
}

export interface StateArtifactRef {
  id: string;
  mime_type?: string;
  size_bytes?: number;
  filename?: string;
  sha256?: string;
}

export interface StateEvent {
  type: string;
  sequence: number;
  occurred_at: string;
  tenant: string;
  user: string;
  session: string;
  run?: string;
  payload?: unknown;
  extra?: Record<string, string>;
  artifacts?: StateArtifactRef[];
}

export interface StateHistoryRequest {
  identity: IdentityScope;
  session_id: string;
  before?: number;
  limit?: number;
}

export interface StateHistoryResponse {
  events: StateEvent[];
  head_sequence: number;
  tail_sequence: number;
  next_cursor: number;
  has_more: boolean;
  truncated?: boolean;
}

export interface SubsystemDriver {
  subsystem: string;
  driver: string;
  mode?: string;
}

export interface SubsystemHealth {
  subsystem: string;
  status: string;
  detail?: string;
}

export interface TaskCostRollup {
  total_tokens: number;
  prompt_tokens: number;
  output_tokens: number;
  usd: number;
  per_step: TaskCostStep[];
}

export interface TaskCostStep {
  step_index: number;
  tokens: number;
  usd: number;
}

export interface TaskDetail {
  task: TaskRow;
  parent_session: TaskParentSessionRef;
  parent_task?: TaskParentTaskRef;
  cost: TaskCostRollup;
  planner_snapshot?: TaskPlannerSnapshotRef;
  result_ref?: ArtifactRef;
  result_inline?: string;
  trajectory?: TaskTrajectoryRef;
  input_artifacts?: TaskInputArtifact[];
}

export interface TaskFilter {
  statuses?: string[];
  kinds?: string[];
  parent_task_id?: string;
  identities?: IdentityScope[];
  tenant_ids?: string[];
  since?: string;
  until?: string;
  error_classes?: string[];
  latency_above_ms?: number;
  search?: string;
  group_id?: string;
  has_pending_approval?: boolean;
}

export interface TaskGetRequest {
  identity: IdentityScope;
  id: string;
}

export interface TaskInputArtifact {
  id: string;
  disposition?: string;
}

export interface TaskListAggregates {
  pending: number;
  running: number;
  paused: number;
  failed: number;
  complete: number;
  cancelled: number;
}

export interface TaskListCursor {
  next_page_token?: string;
}

export interface TaskListRequest {
  identity: IdentityScope;
  filter: TaskFilter;
  page_size?: number;
  cursor: TaskListCursor;
  include_status_counter_strip?: boolean;
}

export interface TaskListResponse {
  rows: TaskRow[];
  cursor: TaskListCursor;
  aggregates: TaskListAggregates;
  status_counter_strip?: TasksListStatusCounterStrip;
}

export interface TaskParentSessionRef {
  session_id: string;
  agent_name: string;
  status: string;
  started_at: string;
  latest_event_at: string;
}

export interface TaskParentTaskRef {
  task_id: string;
  kind: string;
  status: string;
}

export interface TaskPlannerSnapshotRef {
  checkpoint_id: string;
  summary: string;
}

export interface TaskRow {
  id: string;
  kind: string;
  status: string;
  priority: number;
  identity: IdentityScope;
  parent_session_id: string;
  parent_task_id?: string;
  description: string;
  query: string;
  started_at: string;
  updated_at: string;
  duration_ms: number;
  error_class?: string;
  tool_count: number;
  background_acknowledged?: boolean;
  group_id?: string;
  progress?: number;
  tags?: string[];
  last_activity_at: string;
  is_background: boolean;
  has_pending_approval: boolean;
}

export interface TaskTrajectoryRef {
  steps: TaskTrajectoryStep[];
}

export interface TaskTrajectoryStep {
  index: number;
  reasoning_trace: string;
}

export interface TasksListStatusCounterStrip {
  pending: number;
  running: number;
  completed: number;
  paused: number;
  failed: number;
}

export interface TimeRange {
  after?: string;
  before?: string;
}

export interface Tool {
  id: string;
  name: string;
  version: string;
  description: string;
  scope: string;
  transport: string;
  oauth_status: string;
  approval_policy: string;
  reliability_tier: string;
  owner: string;
  last_used_at: string;
}

export interface ToolAggregates {
  total: number;
  active: number;
  pending_approval: number;
  awaiting_oauth: number;
}

export interface ToolContentBucket {
  max_bytes: number;
  count: number;
}

export interface ToolContentStats {
  id: string;
  histogram: ToolContentBucket[];
  heavy_threshold_bytes: number;
  heavy_count: number;
  negotiated_display: Record<string, string>;
}

export interface ToolContentStatsRequest {
  identity: IdentityScope;
  id: string;
}

export interface ToolContextPayload {
  content?: unknown;
  artifact_ref?: MCPResourceArtifactRef;
}

export interface ToolContextRequest {
  identity: IdentityScope;
  server_id: string;
  tool_call_id: string;
}

export interface ToolContextResponse {
  tool: string;
  input: ToolContextPayload;
  result: ToolContextPayload;
  is_error: boolean;
  protocol_version: string;
}

export interface ToolDescribeRequest {
  identity: IdentityScope;
  id: string;
  agent_id?: string;
}

export interface ToolFilter {
  scopes?: string[];
  transports?: string[];
  oauth_statuses?: string[];
  approval_policies?: string[];
  reliability_tiers?: string[];
  search?: string;
}

export interface ToolGetRequest {
  identity: IdentityScope;
  id: string;
}

export interface ToolListRequest {
  identity: IdentityScope;
  filter: ToolFilter;
  page?: number;
  page_size?: number;
}

export interface ToolListResponse {
  tools: Tool[];
  page: number;
  page_size: number;
  page_count: number;
  total_rows: number;
  aggregates: ToolAggregates;
  aggregates_partial?: boolean;
}

export interface ToolManifest {
  tool: Tool;
  side_effect: string;
  args_schema: string;
  out_schema: string;
  examples: string[];
  auth_scopes: string[];
  oauth_binding_scope: string;
  retry_attempts: number;
  timeout_ms: number;
  loading_mode: string;
  display_modes: Record<string, string>;
}

export interface ToolMetrics {
  id: string;
  window: string;
  error_rate_1h: number;
  error_rate_24h: number;
  error_rate_7d: number;
  invocations: number;
  failures: number;
  status: string;
}

export interface ToolMetricsRequest {
  identity: IdentityScope;
  id: string;
  window?: string;
}

export interface ToolRevokeOAuthRequest {
  identity: IdentityScope;
  id: string;
}

export interface ToolRevokeOAuthResponse {
  id: string;
  revoked_count: number;
}

export interface ToolSetApprovalPolicyRequest {
  identity: IdentityScope;
  id: string;
  policy: string;
}

export interface ToolSetApprovalPolicyResponse {
  id: string;
  policy: string;
}

export interface TopologyEdge {
  from: string;
  to: string;
  queue_depth: number;
  queue_capacity: number;
}

export interface TopologyNode {
  name: string;
  kind: string;
}

export interface TopologyProjection {
  engine_id: string;
  occurred_at: string;
  nodes: TopologyNode[];
  edges: TopologyEdge[];
}

export interface TopologySnapshotRequest {
  identity: IdentityScope;
}

export interface Version {
  Major: number;
  Minor: number;
  Patch: number;
}

export interface VersionHandshake {
  protocol_version: string;
  capabilities: string[];
}

export interface Window {
  from?: string;
  to?: string;
}

