// Harbor Console — Sessions-page wire types (Phase 73c / D-122).
//
// The hand-authored TypeScript mirror of `internal/protocol/types/
// sessions.go` — the `sessions.list` / `sessions.inspect` request /
// response shapes. D-093 pins `src/lib/protocol.ts` as generated by
// `cmd/harbor-gen-protocol-ts`; that generator binary has not yet
// landed (Phase 72h committed `protocol.ts` as a hand-shaped stub).
// This module follows the Flows-page precedent (`$lib/flows/types.ts`):
// the Sessions-page wire types live here, hand-authored, until the
// generator emits them. A documented Phase 73c deviation — see the
// phase plan §"Findings I'm departing from".
//
// The `identity` field every request carries is folded into the
// request body by the shared `HarborClient` transport — callers pass
// the request WITHOUT `identity`.

/** A session's lifecycle status — the closed enum the status facet filters on. */
export type SessionStatus = 'running' | 'paused' | 'completed' | 'failed';

/** The `sessions.list` row ordering. */
export type SessionSort =
  | 'started_desc'
  | 'started_asc'
  | 'last_activity_desc'
  | 'cost_desc';

/** The flat wire identity scope a Protocol request carries. */
export interface SessionIdentityScope {
  tenant: string;
  user: string;
  session: string;
  /** The admin-impersonation triplet (Phase 72b / D-107). */
  actor?: SessionIdentityScope;
  requester?: SessionIdentityScope;
  impersonating?: SessionIdentityScope;
}

/** A half-open time-range filter; both bounds optional (RFC 3339). */
export interface SessionWindow {
  from?: string;
  to?: string;
}

/** The server-enforced facet filter on `sessions.list`. */
export interface SessionFilter {
  statuses?: SessionStatus[];
  agent_ids?: string[];
  user_ids?: string[];
  /** A `tenant_ids` entry outside the caller's tenant requires `admin` (D-079). */
  tenant_ids?: string[];
  started_window?: SessionWindow;
  has_intervention?: boolean;
  has_failed_task?: boolean;
  cost_above_cents?: number;
  /** Free-text search forwarded to `search.sessions` when non-empty. */
  query?: string;
}

/** The `sessions.list` request body (sans `identity` — folded by the transport). */
export interface SessionsListRequest {
  filter?: SessionFilter;
  sort?: SessionSort;
  cursor?: string;
  limit?: number;
}

/** One catalog-row projection of a session. No Priority field — D-065. */
export interface SessionRow {
  session_id: string;
  status: SessionStatus;
  agent_id: string;
  agent_name: string;
  user_id: string;
  tenant_id: string;
  started_at: string;
  last_activity_at: string;
  /** Elapsed span in nanoseconds (Go `time.Duration` JSON form). */
  duration: number;
  tasks_count: number;
  events_count: number;
  total_cost_cents: number;
  total_tokens: number;
  has_pending_intervention: boolean;
  has_failed_task: boolean;
  /** The impersonation triplet (Phase 72b / D-107) for the Identity column. */
  identity: SessionIdentityScope;
}

/** The `sessions.list` reply — a page of rows plus the opaque next cursor. */
export interface SessionsListResponse {
  rows: SessionRow[];
  next_cursor: string;
  /** D-026 fail-loudly: true when the candidate set hit limit+1 rows. */
  truncated: boolean;
}

/** One Recent-Interventions card entry on the Sessions detail view. */
export interface InterventionSummary {
  type: string;
  reason: string;
  outcome: string;
  occurred_at: string;
}

/** One Recent-Artifacts card entry — metadata only (D-026). */
export interface ArtifactRefSummary {
  filename: string;
  mime: string;
  size_bytes: number;
  created_at: string;
}

/** The `sessions.inspect` reply — the full per-session snapshot. */
export interface SessionsInspectResponse {
  row: SessionRow;
  recent_interventions: InterventionSummary[];
  recent_artifacts: ArtifactRefSummary[];
}

/** The Sessions-page pagination bounds — mirror the Go-side constants. */
export const DEFAULT_SESSION_LIST_LIMIT = 50;
export const MAX_SESSION_LIST_LIMIT = 200;
