#!/usr/bin/env bash
# PREFLIGHT_REQUIRES: static-only
#
# Phase 118 smoke — Protocol TS lockstep gate.
#
# Static-only: the gate is a build-time contract (a Go manifest generator +
# a TS-source scan), not an HTTP surface. These assertions pin the
# load-bearing facts in source so a regression fails preflight:
#   1. The committed wire manifest exists and carries the GENERATED / DO-NOT-
#      EDIT banner (hand-edits are rejection-on-sight).
#   2. The `protocol-ts-gen` + `protocol-ts-gen-check` Make targets exist.
#   3. The lockstep tool builds.
#   4. The TS-source scan runs clean (node stdlib only — no `npm ci`).

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "${ROOT}"

# shellcheck source=scripts/smoke/common.sh
source "scripts/smoke/common.sh"

MANIFEST="web/console/src/lib/protocol/wire-manifest.gen.json"

# Skip cleanly on a checkout without the Console (keeps preflight green where
# the frontend isn't present).
if [ ! -f "${MANIFEST}" ]; then
    skip "phase 118: wire manifest not present (web/console absent)"
    smoke_summary
    exit 0
fi

# 1. The committed manifest is GENERATED-headed.
assert_grep_present 'GENERATED BY cmd/harbor-protocol-ts-lockstep' \
    "${MANIFEST}" \
    "wire manifest carries the GENERATED banner"
assert_grep_present 'DO NOT EDIT' \
    "${MANIFEST}" \
    "wire manifest carries the DO-NOT-EDIT notice"

# 2. The Make targets exist.
assert_grep_present '^protocol-ts-gen:' "Makefile" \
    "protocol-ts-gen target present"
assert_grep_present '^protocol-ts-gen-check:' "Makefile" \
    "protocol-ts-gen-check target present"

# 3. The lockstep tool builds.
if command -v go >/dev/null 2>&1; then
    if go build -o /dev/null ./cmd/harbor-protocol-ts-lockstep/ >/dev/null 2>&1; then
        ok "cmd/harbor-protocol-ts-lockstep builds"
    else
        fail "cmd/harbor-protocol-ts-lockstep does not build"
    fi
else
    skip "lockstep tool build: go not available"
fi

# 4. The TS-source scan runs clean.
if command -v node >/dev/null 2>&1; then
    if node web/console/scripts/check-protocol-ts-lockstep.mjs >/dev/null 2>&1; then
        ok "protocol-ts lockstep scan passes (wire manifest in lockstep with the TS client)"
    else
        fail "protocol-ts lockstep scan reports violations"
    fi
else
    skip "protocol-ts lockstep scan: node not available"
fi

smoke_summary
