#!/usr/bin/env bash
# PREFLIGHT_REQUIRES: live-server
#
# Phase 135 smoke — external-client TS wire-type generator + event-viewer-ts.
# (RFC §5, §3.6; docs/plans/phase-135-ts-types-generator.md; D-269)
#
# The generator cmd/harbor-protocol-ts-types reflects over the canonical
# Protocol single sources and emits a vendorable external-client TS
# wire-type module
# (examples/protocol-clients/event-viewer-ts/harbor-protocol.gen.ts). The
# event-viewer-ts client consumes it against the dev runtime. This smoke
# asserts:
#
#   1. Static — the generated module + the client + its package files exist;
#      the module carries the DO-NOT-EDIT banner; the client vendors its
#      types from the generated module and stays dependency-free (no Harbor
#      import, no committed node_modules).
#   2. Gen-check — regenerate the module to a temp file and assert it is
#      byte-identical to the committed one (the non-mutating equivalent of
#      `make protocol-ts-types-gen-check`'s git-diff half), and the Go
#      lockstep tests pass.
#   3. Non-interference — the D-223 Console wire manifest is NOT a target of
#      this generator (it must stay byte-stable while we regenerate ours).
#   4. Live — run event-viewer-ts in PROBE mode against the booted dev
#      server and assert the runtime.info round-trip (typed against the
#      generated RuntimeInfo) succeeds.
#
# Conventions (AGENTS.md §4.2): missing surface / no node / no server →
# SKIP, so the gate is green on builds that predate the surface.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "${ROOT}"

# shellcheck source=scripts/smoke/common.sh
source "scripts/smoke/common.sh"

GEN_MODULE="examples/protocol-clients/event-viewer-ts/harbor-protocol.gen.ts"
CLIENT="examples/protocol-clients/event-viewer-ts/event-viewer.ts"
GEN_CMD="cmd/harbor-protocol-ts-types"
MANIFEST="web/console/src/lib/protocol/wire-manifest.gen.json"

if [ ! -d "${GEN_CMD}" ]; then
    skip "phase 135: ${GEN_CMD} not yet present (phase not implemented)"
    smoke_summary
    exit 0
fi

# ----------------------------------------------------------------------------
# 1. Static — the surface exists and is shaped correctly.
# ----------------------------------------------------------------------------
assert_file "${GEN_MODULE}" 'phase 135: generated external-client TS module present'
assert_file "${CLIENT}" 'phase 135: event-viewer-ts client present'
assert_file 'examples/protocol-clients/event-viewer-ts/package.json' 'phase 135: client package.json present'
assert_file 'examples/protocol-clients/event-viewer-ts/tsconfig.json' 'phase 135: client tsconfig present'

assert_grep_present 'CODE GENERATED BY cmd/harbor-protocol-ts-types. DO NOT EDIT.' "${GEN_MODULE}" \
    'phase 135: generated module carries the DO-NOT-EDIT banner'
assert_grep_present 'export interface RuntimeInfo' "${GEN_MODULE}" \
    'phase 135: generated module declares the RuntimeInfo interface'
assert_grep_present 'export type HarborMethod' "${GEN_MODULE}" \
    'phase 135: generated module declares the HarborMethod union'

# The client vendors its types from the generated module …
assert_grep_present './harbor-protocol.gen' "${CLIENT}" \
    'phase 135: client imports the generated wire-type module'
# … and is dependency-free (a Harbor import would defeat the example's premise).
assert_grep_absent 'hurtener/Harbor' "${CLIENT}" \
    'phase 135: event-viewer-ts stays SDK-free (no Harbor import)'
# No committed node_modules / build under the example dir.
if [ -d 'examples/protocol-clients/event-viewer-ts/node_modules' ]; then
    fail 'phase 135: node_modules committed under event-viewer-ts (must not be)'
else
    ok 'phase 135: no committed node_modules under event-viewer-ts'
fi

# ----------------------------------------------------------------------------
# 2. Gen-check — the committed module is in sync with the canonical sources.
# ----------------------------------------------------------------------------
if ! command -v go >/dev/null 2>&1; then
    skip 'phase 135: go toolchain unavailable — gen-check skipped'
else
    GEN_TMP="$(mktemp -t harbor-135-gen-XXXXXX)"
    trap 'rm -f "${GEN_TMP}"' EXIT
    if go run ./"${GEN_CMD}" -out "${GEN_TMP}" -root . >/dev/null 2>&1; then
        if diff -q "${GEN_TMP}" "${GEN_MODULE}" >/dev/null 2>&1; then
            ok 'phase 135: committed TS module is byte-identical to a fresh regeneration'
        else
            fail 'phase 135: committed TS module is stale — run `make protocol-ts-types-gen` and commit'
        fi
    else
        fail 'phase 135: the TS-types generator failed to run'
    fi

    # The Go lockstep tests (in-sync + canonical-surface coverage) pass.
    if go test ./"${GEN_CMD}"/... >/dev/null 2>&1; then
        ok 'phase 135: TS-types generator lockstep tests pass'
    else
        fail 'phase 135: TS-types generator lockstep tests fail'
    fi
fi

# ----------------------------------------------------------------------------
# 3. Non-interference — the D-223 Console wire manifest is NOT this
#    generator's target; it must stay byte-stable. (Belt-and-suspenders:
#    the generator writes only to the example dir.)
# ----------------------------------------------------------------------------
if [ -f "${MANIFEST}" ]; then
    if command -v git >/dev/null 2>&1 && git rev-parse --git-dir >/dev/null 2>&1; then
        if git diff --quiet -- "${MANIFEST}" 2>/dev/null; then
            ok 'phase 135: D-223 Console wire manifest untouched by the TS-types generator'
        else
            fail 'phase 135: D-223 Console wire manifest changed — the TS-types generator must not touch it'
        fi
    else
        skip 'phase 135: git unavailable — manifest non-interference check skipped'
    fi
else
    skip "phase 135: ${MANIFEST} absent — manifest non-interference check skipped"
fi

# ----------------------------------------------------------------------------
# 4. Live — run event-viewer-ts (PROBE mode) against the booted dev server.
#    Requires a TypeScript-capable Node (>= 22.6 strips types in place).
# ----------------------------------------------------------------------------
if ! command -v node >/dev/null 2>&1; then
    skip 'phase 135: node unavailable — live event-viewer-ts probe skipped'
    smoke_summary
    exit 0
fi
if ! node --experimental-strip-types -e '0' >/dev/null 2>&1; then
    skip 'phase 135: this node does not support --experimental-strip-types — live probe skipped'
    smoke_summary
    exit 0
fi
if ! skip_if_404 "$(api_url /healthz)" 'phase 135: dev server reachability'; then
    smoke_summary
    exit 0
fi

PROBE_LOG="$(mktemp -t harbor-135-probe-XXXXXX)"
trap 'rm -f "${GEN_TMP:-}" "${PROBE_LOG}"' EXIT
if HARBOR_BASE_URL="${HARBOR_BASE_URL:-http://127.0.0.1:18080}" \
   HARBOR_TOKEN="${HARBOR_DEV_TOKEN:-}" \
   HARBOR_SESSION='event-viewer-ts-smoke' \
   HARBOR_PROBE=1 \
   node --experimental-strip-types "${CLIENT}" >"${PROBE_LOG}" 2>&1; then
    if grep -q 'probe OK' "${PROBE_LOG}"; then
        ok 'phase 135: event-viewer-ts runtime.info round-trip OK against the dev runtime'
    else
        fail "phase 135: event-viewer-ts probe ran but did not confirm the round-trip (see ${PROBE_LOG})"
        sed 's/^/    /' "${PROBE_LOG}" || true
    fi
else
    fail "phase 135: event-viewer-ts probe failed against the dev runtime (see ${PROBE_LOG})"
    sed 's/^/    /' "${PROBE_LOG}" || true
fi

smoke_summary
