#!/usr/bin/env bash
# PREFLIGHT_REQUIRES: live-server
#
# Phase 113a smoke — Protocol adoption track: the generated contract
# reference + the executed quickstart.
# (RFC §5, §3.6; docs/plans/phase-113a-protocol-reference-and-quickstart.md)
#
# Two assertion classes:
#   1. Static, phase-103-style site trip-wires: the four generated pages
#      under docs/site/protocol/ exist AND carry the generated-file
#      header; the hand-written quickstart + choreography guides 1-3
#      exist; the Protocol nav section is wired in
#      docs/site/.vitepress/config.ts; the Makefile has
#      `protocol-docs-gen-check:`; the docs workflow invokes it;
#      CLAUDE.md §18 names the generated reference; the README Docs
#      table carries the Protocol row; each choreography guide's
#      demonstrated method names resolve against the generated
#      methods.md (lockstep greps).
#   2. Live — the EXECUTED quickstart (the recipe-cannot-lie pattern):
#      extract the quickstart's `<!-- qs-step: ... -->`-tagged bash
#      blocks and run them, in order, in ONE shell against the booted
#      preflight dev server (HARBOR_BASE_URL): bootstrap → start → SSE
#      tail (bounded) → tasks.get → one steering call, asserting status
#      + JSON shape per step. Once the page exists, a step whose block
#      and the wire disagree is a FAIL, never a SKIP.
#
# Conventions (AGENTS.md §4.2): 404/405/501 → SKIP on pre-113a builds;
# once shipped, OK ≥ the quickstart's step count and FAIL = 0.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "${ROOT}"

# shellcheck source=scripts/smoke/common.sh
source "scripts/smoke/common.sh"

PROTO_DIR="docs/site/protocol"
QUICKSTART="${PROTO_DIR}/quickstart.md"

if [ ! -d "${PROTO_DIR}" ]; then
    skip "phase 113a: ${PROTO_DIR} not yet present (phase not implemented)"
    smoke_summary
    exit 0
fi

# ----------------------------------------------------------------------------
# 1. Static — the four generated pages exist and carry the header.
# ----------------------------------------------------------------------------
GEN_HEADER='CODE GENERATED BY cmd/harbor-gen-protocol-docs. DO NOT EDIT.'
for page in methods.md events.md errors.md types.md; do
    assert_file "${PROTO_DIR}/${page}" "phase 113a: generated ${page} present"
    assert_grep_present "${GEN_HEADER}" "${PROTO_DIR}/${page}" \
        "phase 113a: ${page} carries the generated-file header"
done

# 2. Static — the five hand-written pages exist.
for page in index.md quickstart.md auth-and-identity.md streaming-semantics.md task-control.md; do
    assert_file "${PROTO_DIR}/${page}" "phase 113a: hand-written ${page} present"
done

# 3. Static — the Protocol nav section is wired (one entry per page).
CONFIG='docs/site/.vitepress/config.ts'
assert_grep_present '"/protocol/"' "${CONFIG}" 'phase 113a: config.ts has the /protocol/ sidebar section'
for link in '/protocol/quickstart' '/protocol/methods' '/protocol/events' \
            '/protocol/errors' '/protocol/types' '/protocol/auth-and-identity' \
            '/protocol/streaming-semantics' '/protocol/task-control'; do
    assert_grep_present "${link}" "${CONFIG}" "phase 113a: config.ts nav entry ${link}"
done

# 4. Static — the gen-check gate exists and CI invokes it.
assert_grep_present '^protocol-docs-gen-check:' Makefile \
    'phase 113a: Makefile has the protocol-docs-gen-check gate'
assert_grep_present 'protocol-docs-gen-check' .github/workflows/docs.yml \
    'phase 113a: docs workflow runs the gen-check before the site build'

# 5. Static — §18 names the generated reference; README has the row.
assert_grep_present 'docs/site/protocol' CLAUDE.md \
    'phase 113a: CLAUDE.md §18 covers the generated Protocol reference'
assert_grep_present 'docs/site/protocol' README.md \
    'phase 113a: README Docs table carries the Protocol row'

# ----------------------------------------------------------------------------
# 6. Lockstep greps — every method a choreography guide demonstrates
#    resolves against the generated methods.md. Guides declare them on a
#    "> Methods demonstrated:" block as backticked names.
# ----------------------------------------------------------------------------
for guide in auth-and-identity.md streaming-semantics.md task-control.md; do
    path="${PROTO_DIR}/${guide}"
    [ -f "${path}" ] || continue
    demonstrated=$(awk '/^> Methods demonstrated:/,/^$/' "${path}" \
        | grep -oE '`[a-z0-9_.]+`' | tr -d '`' | sort -u || true)
    if [ -z "${demonstrated}" ]; then
        fail "phase 113a: ${guide} declares no 'Methods demonstrated' line"
        continue
    fi
    for m in ${demonstrated}; do
        if grep -qF "| \`${m}\` |" "${PROTO_DIR}/methods.md"; then
            ok "phase 113a: ${guide} method \`${m}\` resolves in methods.md"
        else
            fail "phase 113a: ${guide} demonstrates \`${m}\` but methods.md has no such row"
        fi
    done
done

# ----------------------------------------------------------------------------
# 7. Live — the EXECUTED quickstart. Extract the qs-step-tagged bash
#    blocks and run them in order, in one shell, against the preflight
#    dev server. Variables (TOKEN / SESSION / TASK_ID / ...) flow from
#    block to block exactly as they do for a reader following the page.
# ----------------------------------------------------------------------------
if ! command -v curl >/dev/null 2>&1 || ! command -v jq >/dev/null 2>&1; then
    skip 'phase 113a: curl or jq not available — executed quickstart skipped'
    smoke_summary
    exit 0
fi

if ! skip_if_404 "$(api_url /healthz)" 'phase 113a: dev server reachability'; then
    smoke_summary
    exit 0
fi

# Extract each tagged block into its own file under a temp dir. The tag
# count is load-bearing: the page promises exactly five executable
# steps, and a drifted tag set fails loudly rather than silently
# shrinking the executed surface.
QS_TMP="$(mktemp -d -t harbor-qs-XXXXXX)"
trap 'rm -rf "${QS_TMP}"' EXIT

awk -v outdir="${QS_TMP}" '
    /<!-- qs-step: / {
        step = $0
        sub(/.*<!-- qs-step: */, "", step)
        sub(/ *-->.*/, "", step)
        want = 1
        next
    }
    want && /^```bash$/ { inblock = 1; want = 0; next }
    inblock && /^```$/  { inblock = 0; next }
    inblock { print > (outdir "/" step ".sh") }
' "${QUICKSTART}"

STEP_COUNT=$(find "${QS_TMP}" -name '*.sh' | wc -l | tr -d ' ')
if [ "${STEP_COUNT}" -ne 5 ]; then
    fail "phase 113a: quickstart has ${STEP_COUNT} qs-step-tagged blocks, want 5 — the tagging is load-bearing"
    smoke_summary
    exit 1
fi
ok "phase 113a: quickstart carries the 5 tagged executable steps"

# Run the five blocks in one subshell, sourcing them in order, with
# per-step assertions between. The subshell records a verdict line per
# step; we re-emit them as smoke counters afterwards.
VERDICTS="${QS_TMP}/verdicts"
: > "${VERDICTS}"
(
    set -u
    verdict() { printf '%s\t%s\n' "$1" "$2" >> "${VERDICTS}"; }

    # --- Step 1: bootstrap.
    if source "${QS_TMP}/1-bootstrap.sh" > /dev/null 2>&1 \
        && [ -n "${TOKEN:-}" ] && [ "${TOKEN}" != "null" ] \
        && [ -n "$(printf '%s' "${BOOTSTRAP}" | jq -r '.identity.tenant // empty')" ]; then
        verdict OK 'quickstart step 1: bootstrap returns a token + identity envelope'
    else
        verdict FAIL 'quickstart step 1: bootstrap did not yield a token (page/wire drift?)'
        exit 0
    fi

    # --- Step 2: start.
    if source "${QS_TMP}/2-start.sh" > /dev/null 2>&1 \
        && [ -n "${TASK_ID:-}" ] && [ "${TASK_ID}" != "null" ]; then
        verdict OK "quickstart step 2: start spawned task ${TASK_ID}"
    else
        verdict FAIL 'quickstart step 2: start did not return a task_id'
        exit 0
    fi

    # --- Step 3: SSE tail (bounded; Last-Event-ID replay).
    source "${QS_TMP}/3-events.sh" > /dev/null 2>&1 || true
    if printf '%s' "${EVENTS:-}" | grep -q '^event: task\.' \
        && printf '%s' "${EVENTS:-}" | grep -q "${TASK_ID}"; then
        verdict OK 'quickstart step 3: SSE tail observed task events for the started run'
    else
        verdict FAIL 'quickstart step 3: SSE tail observed no event for the started run'
    fi

    # --- Step 4: tasks.get.
    if source "${QS_TMP}/4-tasks-get.sh" > /dev/null 2>&1 \
        && [ "$(printf '%s' "${TASK}" | jq -r '.task.id // empty')" = "${TASK_ID}" ] \
        && [ -n "$(printf '%s' "${TASK}" | jq -r '.task.status // empty')" ]; then
        verdict OK "quickstart step 4: tasks.get snapshots the task (status=$(printf '%s' "${TASK}" | jq -r '.task.status'))"
    else
        verdict FAIL 'quickstart step 4: tasks.get did not return the task'
    fi

    # --- Step 5: one steering call (cancel). Both documented outcomes
    # are valid wire shapes: 200 {"accepted":true} when the run is
    # still live, 404 {"code":"not_found"} when it already reached a
    # terminal state (the page teaches exactly this).
    source "${QS_TMP}/5-cancel.sh" > /dev/null 2>&1 || true
    CANCEL_BODY="${CANCEL%$'\n'*}"
    case "${CANCEL_STATUS:-}" in
        200)
            if [ "$(printf '%s' "${CANCEL_BODY}" | jq -r '.accepted')" = "true" ]; then
                verdict OK 'quickstart step 5: cancel accepted (200, accepted=true)'
            else
                verdict FAIL 'quickstart step 5: cancel returned 200 without accepted=true'
            fi
            ;;
        404)
            if [ "$(printf '%s' "${CANCEL_BODY}" | jq -r '.code')" = "not_found" ]; then
                verdict OK 'quickstart step 5: cancel on a terminal run returns the canonical not_found envelope'
            else
                verdict FAIL 'quickstart step 5: cancel returned 404 without the canonical error envelope'
            fi
            ;;
        *)
            verdict FAIL "quickstart step 5: cancel returned unexpected status ${CANCEL_STATUS:-<none>}"
            ;;
    esac
) || true

if [ ! -s "${VERDICTS}" ]; then
    fail 'phase 113a: executed quickstart produced no verdicts (extraction or subshell failure)'
else
    while IFS=$'\t' read -r status msg; do
        case "${status}" in
            OK)   ok "phase 113a: ${msg}" ;;
            FAIL) fail "phase 113a: ${msg}" ;;
        esac
    done < "${VERDICTS}"
fi

smoke_summary
