// Harbor Console — typed Memory-page Protocol client (Phase 73j / D-118).
//
// This module is the typed wire surface for the three `memory.*` read
// methods the Console Memory page consumes — `memory.list`, `memory.get`,
// `memory.health`. Components NEVER hand-roll `fetch`; they call the
// typed `MemoryClient` (CLAUDE.md §4.5 rule 5).
//
// # Why this is a separate module (documented deviation — CLAUDE.md §4.3)
//
// D-093 pins that `src/lib/protocol.ts` is generated by
// `cmd/harbor-gen-protocol-ts` from the Go-side `CanonicalWireTypes` and
// MUST NEVER be hand-edited. At Phase 73j that generator command does not
// yet exist (Phase 72h committed `protocol.ts` as a hand-authored
// empty-but-typed stub; the generator lands in a later Console-tooling
// phase). Hand-editing the generated stub now would corrupt the
// generated-file contract AND fail the future `protocol-ts-gen-check`.
//
// The honest interim shape: the Memory-page wire types live in this
// dedicated hand-authored module. The TS interfaces here are kept in
// 1:1 lockstep with the Go-side `internal/protocol/types/memory.go`
// single-source structs (D-002). When `cmd/harbor-gen-protocol-ts`
// lands, these interfaces fold into the generated `protocol.ts` and
// this module collapses to a thin re-export — a mechanical migration.
//
// The Go side stays the single source of truth: every interface below
// mirrors a struct in `internal/protocol/types/memory.go`.

import type { OperatorIdentity } from './protocol.js';

/** Memory-record scope — the wire projection of `types.MemoryScope`. */
export type MemoryScope = 'session' | 'user' | 'tenant';

/** Memory strategy — the wire projection of `types.MemoryStrategyName`. */
export type MemoryStrategyName = 'none' | 'truncation' | 'rolling_summary';

/** Memory driver — the wire projection of `types.MemoryDriverName`. */
export type MemoryDriverName = 'inmem' | 'sqlite' | 'postgres';

/** Default / max `memory.list` page size — mirrors the Go-side constants. */
export const DEFAULT_MEMORY_LIST_PAGE_SIZE = 50;
export const MAX_MEMORY_LIST_PAGE_SIZE = 200;

/** Flat identity scope carried on a wire row — mirrors `types.IdentityScope`. */
export interface IdentityScope {
  tenant: string;
  user: string;
  session: string;
}

/** One Memory-page table row — mirrors `types.MemoryItem`. */
export interface MemoryItem {
  key: string;
  strategy: string;
  scope: string;
  identity: IdentityScope;
  agent_id?: string;
  created_at: string;
  last_updated_at: string;
  expires_at?: string;
  size_bytes: number;
  heavy_content?: boolean;
  driver: string;
}

/** The `memory.list` query filter — mirrors `types.MemoryFilter`. */
export interface MemoryFilter {
  tenant_ids?: string[];
  user_ids?: string[];
  session_ids?: string[];
  agent_ids?: string[];
  scopes?: string[];
  drivers?: string[];
  strategies?: string[];
  has_ttl_expiring?: boolean;
  content_search?: string;
}

/** The `memory.list` request — mirrors `types.MemoryListRequest`. */
export interface MemoryListRequest {
  identity?: IdentityScope;
  filter?: MemoryFilter;
  page?: number;
  page_size?: number;
}

/** Page-level counters — mirrors `types.MemoryAggregates`. */
export interface MemoryAggregates {
  total: number;
  expiring_in_1h: number;
  identity_rejected_24h: number;
  recovery_dropped_24h: number;
}

/** The `memory.list` response — mirrors `types.MemoryListResponse`. */
export interface MemoryListResponse {
  items: MemoryItem[];
  page: number;
  page_size: number;
  page_count: number;
  total_rows: number;
  aggregates: MemoryAggregates;
  protocol_version: string;
}

/** By-reference heavy-value stub — mirrors `types.MemoryArtifactRef`. */
export interface MemoryArtifactRef {
  id: string;
  mime_type?: string;
  size_bytes?: number;
  filename?: string;
  sha256?: string;
}

/** Per-record metadata — mirrors `types.MemoryMetadata`. */
export interface MemoryMetadata {
  ttl?: number;
  strategy_config?: Record<string, string>;
  related_event_ids?: string[];
}

/** The `memory.get` request — mirrors `types.MemoryGetRequest`. */
export interface MemoryGetRequest {
  identity?: IdentityScope;
  key: string;
}

/** A single record's full detail — mirrors `types.MemoryItemDetail`. */
export interface MemoryItemDetail {
  item: MemoryItem;
  /** Post-redaction value, populated ONLY below the heavy threshold (D-026). */
  value?: string;
  /** By-reference stub, populated ONLY at/above the heavy threshold (D-026). */
  value_artifact?: MemoryArtifactRef;
  metadata: MemoryMetadata;
}

/** The `memory.get` response — mirrors `types.MemoryGetResponse`. */
export interface MemoryGetResponse {
  detail: MemoryItemDetail;
  protocol_version: string;
}

/** Aggregate health counters — mirrors `types.MemoryHealthAggregate`. */
export interface MemoryHealthAggregate {
  total: number;
  expiring_in_1h: number;
  identity_rejected_24h: number;
  recovery_dropped_24h: number;
  driver_by_scope: Record<string, string>;
}

/** The `memory.health` response — mirrors `types.MemoryHealthResponse`. */
export interface MemoryHealthResponse {
  aggregate: MemoryHealthAggregate;
  protocol_version: string;
}

/** Canonical Protocol error body — mirrors `errors.Error`. */
export interface ProtocolError {
  code: string;
  message: string;
}

/**
 * A typed Protocol error the Console renders on the Memory page's
 * empty / error / unauthorized states. Carries the canonical Code so a
 * component can branch (`identity_required`, `identity_scope_required`,
 * `not_found`, ...) without string-matching the message.
 */
export class MemoryProtocolError extends Error {
  readonly code: string;
  readonly status: number;
  constructor(code: string, message: string, status: number) {
    super(message);
    this.name = 'MemoryProtocolError';
    this.code = code;
    this.status = status;
  }
}

/** Memory route paths — the wire routes the three handlers mount under. */
const MEMORY_ROUTES = {
  list: '/v1/memory/list',
  get: '/v1/memory/get',
  health: '/v1/memory/health'
} as const;

/**
 * MemoryClient is the typed Memory-page Protocol client. It is
 * constructed once with the runtime base URL + the operator's bearer
 * token; every method issues a single POST and decodes the typed
 * response. A non-2xx response is raised as a {@link MemoryProtocolError}
 * carrying the canonical Protocol Code — never a silently-swallowed
 * empty result (CLAUDE.md §13 "no silent degradation").
 *
 * The Console NEVER hand-rolls `fetch` in a `.svelte` file — every
 * Memory-page Runtime call goes through this typed client.
 */
export class MemoryClient {
  readonly #baseURL: string;
  readonly #token: string;
  readonly #identity: OperatorIdentity;
  readonly #fetch: typeof fetch;

  constructor(opts: {
    baseURL: string;
    token: string;
    identity: OperatorIdentity;
    /** Injectable for tests; defaults to the global `fetch`. */
    fetchImpl?: typeof fetch;
  }) {
    this.#baseURL = opts.baseURL.replace(/\/$/, '');
    this.#token = opts.token;
    this.#identity = opts.identity;
    this.#fetch = opts.fetchImpl ?? fetch;
  }

  /** `memory.list` — paginated, identity-scope-filtered memory records. */
  async list(req: MemoryListRequest): Promise<MemoryListResponse> {
    return this.#post<MemoryListResponse>(MEMORY_ROUTES.list, req);
  }

  /** `memory.get` — full detail of one memory record. */
  async get(req: MemoryGetRequest): Promise<MemoryGetResponse> {
    return this.#post<MemoryGetResponse>(MEMORY_ROUTES.get, req);
  }

  /** `memory.health` — aggregate memory-health counters. */
  async health(): Promise<MemoryHealthResponse> {
    return this.#post<MemoryHealthResponse>(MEMORY_ROUTES.health, {});
  }

  /** Issues one POST, decodes the typed response, raises on non-2xx. */
  async #post<T>(route: string, body: unknown): Promise<T> {
    const resp = await this.#fetch(`${this.#baseURL}${route}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${this.#token}`
      },
      body: JSON.stringify(body)
    });
    const text = await resp.text();
    if (!resp.ok) {
      let code = 'runtime_error';
      let message = text || resp.statusText;
      try {
        const err = JSON.parse(text) as ProtocolError;
        if (err.code) code = err.code;
        if (err.message) message = err.message;
      } catch {
        // A non-JSON error body — keep the raw text as the message.
      }
      throw new MemoryProtocolError(code, message, resp.status);
    }
    return JSON.parse(text) as T;
  }

  /** The operator identity this client is scoped to (read-only). */
  get identity(): OperatorIdentity {
    return this.#identity;
  }
}
