// CODE GENERATED BY cmd/harbor-gen-protocol-ts. DO NOT EDIT.
//
// This file is the typed Harbor Protocol client surface for the Console
// (D-093). It is generated from `internal/protocol/singlesource.CanonicalWireTypes`
// by `cmd/harbor-gen-protocol-ts` and MUST NEVER be hand-edited — the
// `make protocol-ts-gen-check` CI step asserts `git diff --exit-code` is clean.
//
// Phase 72h commits this initial empty-but-typed-shaped stub so the
// SvelteKit scaffold type-checks. Downstream Console phases regenerate it
// as Protocol wire types land on the Go side.

/**
 * The Console's view of the operator identity carried by every Protocol
 * request. Hashed into the Console DB `operator_id` row-scope key — see
 * `src/lib/db/schema.ts`.
 */
export interface OperatorIdentity {
  tenantID: string;
  userID: string;
}

/** Placeholder for the generated Protocol method surface. */
export const PROTOCOL_TS_GENERATED = true as const;
