package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"time"

	protoerrors "github.com/hurtener/Harbor/internal/protocol/errors"
	"github.com/hurtener/Harbor/internal/protocol/methods"
	"github.com/hurtener/Harbor/internal/protocol/singlesource"
	"github.com/hurtener/Harbor/internal/protocol/types"
)

// manifestHeader is the value of the manifest's `_comment` field. The
// phase smoke and the §4.5 lockstep rule grep for the DO-NOT-EDIT token;
// hand-editing the manifest is rejection-on-sight (regenerate instead).
const manifestHeader = "GENERATED BY cmd/harbor-protocol-ts-lockstep. DO NOT EDIT. " +
	"Run 'make protocol-ts-gen' to regenerate. This is the machine-checkable " +
	"Go-side wire contract the hand-maintained Console TypeScript client is " +
	"lockstep-gated against by 'make protocol-ts-gen-check'."

// Manifest is the committed JSON contract of the Harbor Protocol wire
// surface, emitted from the canonical Go single sources. It is the
// machine-checkable artifact the TypeScript-source scan compares the
// hand-maintained Console client against, and the artifact the
// `git diff --exit-code` half of the gate watches: any Go-side wire
// change re-emits a different manifest, so an un-regenerated manifest
// fails the gate and surfaces the drift.
type Manifest struct {
	// Comment is the DO-NOT-EDIT banner (JSON carries no comment syntax).
	Comment string `json:"_comment"`
	// ProtocolVersion is the pinned Harbor Protocol version the contract
	// belongs to (RFC §5.3 — bumping it is an RFC change).
	ProtocolVersion string `json:"protocol_version"`
	// Types maps each canonical wire-type name to its field-level shape.
	Types map[string]TypeShape `json:"types"`
	// Methods is the sorted set of canonical Protocol method names.
	Methods []string `json:"methods"`
	// Errors is the sorted set of canonical Protocol error codes.
	Errors []string `json:"errors"`
	// Events is the sorted set of canonical event-type wire strings,
	// derived by scanning the production tree for EventType constant
	// declarations (no driver imports — see scanEventTypes).
	Events []string `json:"events"`
}

// TypeShape is one canonical wire type's field-level shape: its single
// home package plus its fields in wire (declaration) order.
type TypeShape struct {
	// Home is the canonical package directory that declares the type
	// (relative to internal/protocol — almost always "types", "errors"
	// for the Error wire type).
	Home string `json:"home"`
	// Fields are the type's JSON fields in wire order.
	Fields []FieldShape `json:"fields"`
}

// FieldShape is one wire field: its JSON key, a canonical TS-type token,
// an optional named-type reference, and optionality.
type FieldShape struct {
	// Key is the JSON wire key (the json struct tag, or the Go field
	// name when untagged).
	Key string `json:"key"`
	// Type is the canonical TS-type token: one of string / number /
	// boolean / array / object / any.
	Type string `json:"type"`
	// Ref names the canonical wire type this field (or its array/slice
	// element) resolves to, when that named type is itself in the
	// canonical set. Empty for scalars and non-canonical shapes.
	Ref string `json:"ref,omitempty"`
	// Optional is true when the field carries `omitempty` or is a
	// pointer (a TS `?:` field).
	Optional bool `json:"optional,omitempty"`
}

var (
	timeType       = reflect.TypeOf(time.Time{})
	rawMessageType = reflect.TypeOf(json.RawMessage(nil))
)

// eventConstRe matches a typed EventType constant declaration — either
// the subsystem-side `Name events.EventType = "..."` or the events
// package's own `Name EventType = "..."`. It mirrors the docs
// generator's TestGen_EventConstantsAllRegistered scan, so the manifest's
// event set is the full tree truth without seating the event registry
// (no driver blank-imports — §13-clean).
var eventConstRe = regexp.MustCompile(`\b[A-Za-z0-9_]+\s+(?:events\.)?EventType\s*=\s*"([a-z0-9_.]+)"`)

// BuildManifest assembles the wire-surface manifest from the canonical
// Go sources. root is the repository root (".") used to scan the
// production tree for event-type declarations; the type/method/error
// sets come from the imported canonical packages directly.
func BuildManifest(root string) (Manifest, error) {
	typeShapes, err := buildTypeShapes()
	if err != nil {
		return Manifest{}, err
	}

	events, err := scanEventTypes(root)
	if err != nil {
		return Manifest{}, fmt.Errorf("scan event types: %w", err)
	}

	return Manifest{
		Comment:         manifestHeader,
		ProtocolVersion: types.ProtocolVersion,
		Types:           typeShapes,
		Methods:         methodNames(),
		Errors:          errorCodes(),
		Events:          events,
	}, nil
}

// buildTypeShapes reflects over every canonical wire type and records its
// field-level shape. It fails loudly when CanonicalWireTypes names a type
// the typeInstanceIndex does not carry — the same lockstep stance the
// docs generator takes (the test pins this; the generator double-checks
// at runtime so a stale index can never emit a silently-incomplete
// manifest).
func buildTypeShapes() (map[string]TypeShape, error) {
	shapes := make(map[string]TypeShape, len(singlesource.CanonicalWireTypes))
	for name, home := range singlesource.CanonicalWireTypes {
		t, ok := typeInstanceIndex[name]
		if !ok {
			return nil, fmt.Errorf("canonical wire type %q has no typeInstanceIndex entry — extend the index (the lockstep test pins this)", name)
		}
		if t.Kind() != reflect.Struct {
			return nil, fmt.Errorf("canonical wire type %q resolves to %s, want a struct", name, t.Kind())
		}
		shapes[name] = TypeShape{Home: home, Fields: structFields(t)}
	}
	return shapes, nil
}

// structFields walks t's exported fields in declaration order (the order
// encoding/json emits) and renders each as a FieldShape. Embedded seal
// markers and anonymous structs are flattened the way encoding/json
// promotes them; `json:"-"` fields are dropped.
func structFields(t reflect.Type) []FieldShape {
	var out []FieldShape
	for i := range t.NumField() {
		f := t.Field(i)
		if !f.IsExported() {
			continue
		}
		tag := f.Tag.Get("json")
		if tag == "-" {
			continue
		}
		tagParts := strings.Split(tag, ",")
		tagName := tagParts[0]
		omitempty := false
		for _, opt := range tagParts[1:] {
			if opt == "omitempty" {
				omitempty = true
			}
		}

		// Anonymous untagged struct embeds are promoted by encoding/json:
		// recurse so the promoted fields appear at this level (seal
		// markers are empty structs and contribute nothing).
		if f.Anonymous && tagName == "" {
			ft := f.Type
			if ft.Kind() == reflect.Pointer {
				ft = ft.Elem()
			}
			if ft.Kind() == reflect.Struct {
				out = append(out, structFields(ft)...)
				continue
			}
		}

		key := tagName
		if key == "" {
			key = f.Name
		}
		token, ref, optional := mapFieldType(f.Type)
		out = append(out, FieldShape{
			Key:      key,
			Type:     token,
			Ref:      ref,
			Optional: optional || omitempty,
		})
	}
	return out
}

// mapFieldType reduces a Go field type to the canonical TS-type token the
// TypeScript client is expected to declare, plus a named-type ref when
// the type (or an array/slice element) is itself canonical, plus
// optionality for pointer types. JSON marshalling semantics drive the
// mapping: time.Time → string, []byte → base64 string, json.RawMessage →
// any, numeric kinds → number, etc.
func mapFieldType(t reflect.Type) (token, ref string, optional bool) {
	if t.Kind() == reflect.Pointer {
		optional = true
		t = t.Elem()
	}
	if t == timeType {
		return "string", "", optional
	}
	if t == rawMessageType {
		return "any", "", optional
	}
	switch t.Kind() {
	case reflect.Bool:
		return "boolean", "", optional
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number", "", optional
	case reflect.String:
		return "string", "", optional
	case reflect.Slice, reflect.Array:
		if t.Elem().Kind() == reflect.Uint8 {
			// []byte marshals to a base64 JSON string.
			return "string", "", optional
		}
		return "array", canonicalName(t.Elem()), optional
	case reflect.Map:
		return "object", "", optional
	case reflect.Struct:
		return "object", canonicalName(t), optional
	case reflect.Interface:
		return "any", "", optional
	default:
		return "any", "", optional
	}
}

// canonicalName unwraps pointer / slice / array / map indirection and
// reports the underlying type's name when it is a canonical wire type
// (an entry of the typeInstanceIndex declared in the canonical wire
// packages). Empty otherwise.
func canonicalName(t reflect.Type) string {
	for {
		switch t.Kind() {
		case reflect.Pointer, reflect.Slice, reflect.Array, reflect.Map:
			t = t.Elem()
			continue
		}
		break
	}
	name := t.Name()
	if name == "" {
		return ""
	}
	pkg := t.String()
	if !strings.HasPrefix(pkg, "types.") && pkg != "errors.Error" {
		return ""
	}
	if _, ok := typeInstanceIndex[name]; !ok {
		return ""
	}
	return name
}

// methodNames returns the sorted canonical Protocol method names.
func methodNames() []string {
	ms := methods.Methods()
	out := make([]string, 0, len(ms))
	for _, m := range ms {
		out = append(out, string(m))
	}
	sort.Strings(out)
	return out
}

// errorCodes returns the sorted canonical Protocol error codes.
func errorCodes() []string {
	cs := protoerrors.Codes()
	out := make([]string, 0, len(cs))
	for _, c := range cs {
		out = append(out, string(c))
	}
	sort.Strings(out)
	return out
}

// scanEventTypes walks root/internal and returns the sorted unique set of
// event-type wire strings declared as EventType constants. It reads the
// declarations textually (the docs generator's
// TestGen_EventConstantsAllRegistered mechanism) rather than seating the
// event registry, so the manifest's event set is complete without any
// driver blank-imports (§13: no second driver blank-import list).
func scanEventTypes(root string) ([]string, error) {
	seen := make(map[string]struct{})
	walkRoot := filepath.Join(root, "internal")
	err := filepath.WalkDir(walkRoot, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() {
			if d.Name() == "testdata" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		src, readErr := os.ReadFile(path) //nolint:gosec // G122: build-time scan of the repository's own internal/ source tree (trusted, not attacker-controlled); only non-test .go files are read
		if readErr != nil {
			return fmt.Errorf("read %q: %w", path, readErr)
		}
		for _, m := range eventConstRe.FindAllStringSubmatch(string(src), -1) {
			seen[m[1]] = struct{}{}
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(seen))
	for et := range seen {
		out = append(out, et)
	}
	sort.Strings(out)
	return out, nil
}

// render marshals the manifest to deterministic, newline-terminated
// pretty JSON (sorted map keys, two-space indent) so the
// `git diff --exit-code` gate is byte-stable.
func render(m Manifest) ([]byte, error) {
	b, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal manifest: %w", err)
	}
	b = append(b, '\n')
	return b, nil
}
