package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"time"

	protoerrors "github.com/hurtener/Harbor/internal/protocol/errors"
	"github.com/hurtener/Harbor/internal/protocol/methods"
	"github.com/hurtener/Harbor/internal/protocol/singlesource"
	"github.com/hurtener/Harbor/internal/protocol/types"
	"github.com/hurtener/Harbor/internal/protocol/wiresurface"
)

// moduleHeader is the generated module's banner. The phase smoke and the
// `make protocol-ts-types-gen-check` gate grep for the DO-NOT-EDIT token;
// hand-editing the module is rejection-on-sight (regenerate instead).
const moduleHeader = "CODE GENERATED BY cmd/harbor-protocol-ts-types. DO NOT EDIT.\n" +
	" * Run 'make protocol-ts-types-gen' to regenerate from the canonical\n" +
	" * Harbor Protocol single sources (internal/protocol/{types,methods,errors}\n" +
	" * + the canonical event-type set). This is a vendorable external-client\n" +
	" * wire-type module: copy it into your TypeScript client and keep it fresh\n" +
	" * by re-vendoring after a Harbor upgrade. It is independent of the\n" +
	" * Console's hand-maintained protocol.ts and of the committed wire\n" +
	" * manifest; it carries no client logic, only types."

// Module is the in-memory shape of the generated TypeScript module:
// every canonical wire type as a TypeScript interface, plus the method /
// error-code / event-type name sets as string-union types, plus the
// pinned Protocol version and the wire-surface digest.
type Module struct {
	// Comment is the DO-NOT-EDIT banner.
	Comment string
	// ProtocolVersion is the pinned Harbor Protocol version (RFC §5.3).
	ProtocolVersion string
	// WireSurfaceDigest is the canonical name-level wire-surface digest
	// (wiresurface.Digest()) the runtime also reports on runtime.info, so a
	// client that vendored this module at build time can compare the live
	// runtime's digest against the one it was built against.
	WireSurfaceDigest string
	// Types are the canonical wire-type interfaces, sorted by name.
	Types []TypeIface
	// Methods is the sorted set of canonical Protocol method names.
	Methods []string
	// Errors is the sorted set of canonical Protocol error codes.
	Errors []string
	// Events is the sorted set of canonical event-type wire strings.
	Events []string
}

// TypeIface is one canonical wire type rendered as a TypeScript
// interface: its name plus its fields in wire (declaration) order.
type TypeIface struct {
	Name   string
	Fields []FieldDef
}

// FieldDef is one TypeScript interface field: its wire key, its
// TypeScript type expression, and optionality.
type FieldDef struct {
	// Key is the JSON wire key (the json struct tag, or the Go field name
	// when untagged).
	Key string
	// TSType is the rendered TypeScript type expression (string / number /
	// boolean / a named interface / `T[]` / `Record<string, T>` /
	// unknown).
	TSType string
	// Optional is true when the field carries `omitempty` or is a pointer
	// (a TypeScript `?:` field).
	Optional bool
}

var (
	timeType       = reflect.TypeOf(time.Time{})
	rawMessageType = reflect.TypeOf(json.RawMessage(nil))
)

// eventConstRe matches a typed EventType constant declaration — either
// the subsystem-side `Name events.EventType = "..."` or the events
// package's own `Name EventType = "..."`. It mirrors the manifest
// generator's scan so the module's event set is the full tree truth
// without seating the event registry (no driver blank-imports).
var eventConstRe = regexp.MustCompile(`\b[A-Za-z0-9_]+\s+(?:events\.)?EventType\s*=\s*"([a-z0-9_.]+)"`)

// tsIdentRe matches a TypeScript property name that is safe to render
// unquoted. Wire keys outside this shape are emitted as quoted string
// keys.
var tsIdentRe = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

// BuildModule assembles the TypeScript module from the canonical Go
// sources. root is the repository root (".") used to scan the production
// tree for event-type declarations; the type / method / error sets come
// from the imported canonical packages directly.
func BuildModule(root string) (Module, error) {
	ifaces, err := buildTypeIfaces()
	if err != nil {
		return Module{}, err
	}
	events, err := scanEventTypes(root)
	if err != nil {
		return Module{}, fmt.Errorf("scan event types: %w", err)
	}
	return Module{
		Comment:           moduleHeader,
		ProtocolVersion:   types.ProtocolVersion,
		WireSurfaceDigest: wiresurface.Digest(),
		Types:             ifaces,
		Methods:           methodNames(),
		Errors:            errorCodes(),
		Events:            events,
	}, nil
}

// buildTypeIfaces reflects over every canonical wire type and records its
// TypeScript interface. It fails loudly when CanonicalWireTypes names a
// type the typeInstanceIndex does not carry — the lockstep test pins
// this, and the generator double-checks at runtime so a stale index can
// never emit a silently-incomplete module.
func buildTypeIfaces() ([]TypeIface, error) {
	out := make([]TypeIface, 0, len(singlesource.CanonicalWireTypes))
	for name := range singlesource.CanonicalWireTypes {
		t, ok := typeInstanceIndex[name]
		if !ok {
			return nil, fmt.Errorf("canonical wire type %q has no typeInstanceIndex entry — extend the index (the lockstep test pins this)", name)
		}
		if t.Kind() != reflect.Struct {
			return nil, fmt.Errorf("canonical wire type %q resolves to %s, want a struct", name, t.Kind())
		}
		out = append(out, TypeIface{Name: name, Fields: structFields(t)})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out, nil
}

// structFields walks t's exported fields in declaration order (the order
// encoding/json emits) and renders each as a FieldDef. Embedded untagged
// struct embeds are promoted the way encoding/json promotes them (seal
// markers are empty structs and contribute nothing); `json:"-"` fields are
// dropped.
func structFields(t reflect.Type) []FieldDef {
	var out []FieldDef
	for i := range t.NumField() {
		f := t.Field(i)
		if !f.IsExported() {
			continue
		}
		tag := f.Tag.Get("json")
		if tag == "-" {
			continue
		}
		tagParts := strings.Split(tag, ",")
		tagName := tagParts[0]
		omitempty := false
		for _, opt := range tagParts[1:] {
			if opt == "omitempty" {
				omitempty = true
			}
		}

		if f.Anonymous && tagName == "" {
			ft := f.Type
			if ft.Kind() == reflect.Pointer {
				ft = ft.Elem()
			}
			if ft.Kind() == reflect.Struct {
				out = append(out, structFields(ft)...)
				continue
			}
		}

		key := tagName
		if key == "" {
			key = f.Name
		}
		tsType, optional := mapFieldType(f.Type)
		out = append(out, FieldDef{
			Key:      key,
			TSType:   tsType,
			Optional: optional || omitempty,
		})
	}
	return out
}

// mapFieldType reduces a Go field type to a TypeScript type expression
// plus top-level optionality (pointer types are optional). JSON
// marshalling semantics drive the mapping: time.Time → string, []byte →
// base64 string, json.RawMessage → unknown, numeric kinds → number, etc.
func mapFieldType(t reflect.Type) (tsType string, optional bool) {
	if t.Kind() == reflect.Pointer {
		return tsTypeExpr(t.Elem()), true
	}
	return tsTypeExpr(t), false
}

// tsTypeExpr renders a Go type as a TypeScript type expression,
// recursing through pointer / slice / array / map element types so the
// vendored module carries faithful `T[]` and `Record<string, T>`
// shapes. A named canonical wire type renders as its interface name;
// anything else reduces to a safe scalar / `unknown` / `Record<string,
// unknown>`.
func tsTypeExpr(t reflect.Type) string {
	if t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	if t == timeType {
		return "string"
	}
	if t == rawMessageType {
		return "unknown"
	}
	switch t.Kind() {
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.String:
		return "string"
	case reflect.Slice, reflect.Array:
		if t.Elem().Kind() == reflect.Uint8 {
			// []byte marshals to a base64 JSON string.
			return "string"
		}
		return tsTypeExpr(t.Elem()) + "[]"
	case reflect.Map:
		return "Record<string, " + tsTypeExpr(t.Elem()) + ">"
	case reflect.Struct:
		if name := canonicalName(t); name != "" {
			return name
		}
		// A non-canonical inline struct marshals to a JSON object whose
		// shape this module does not name — keep it open rather than
		// inventing an interface.
		return "Record<string, unknown>"
	case reflect.Interface:
		return "unknown"
	default:
		return "unknown"
	}
}

// canonicalName reports t's name when t is itself a canonical wire type
// (an entry of the typeInstanceIndex declared in the canonical wire
// packages). Empty otherwise.
func canonicalName(t reflect.Type) string {
	name := t.Name()
	if name == "" {
		return ""
	}
	pkg := t.String()
	if !strings.HasPrefix(pkg, "types.") && pkg != "errors.Error" {
		return ""
	}
	if _, ok := typeInstanceIndex[name]; !ok {
		return ""
	}
	return name
}

// methodNames returns the sorted canonical Protocol method names.
func methodNames() []string {
	ms := methods.Methods()
	out := make([]string, 0, len(ms))
	for _, m := range ms {
		out = append(out, string(m))
	}
	sort.Strings(out)
	return out
}

// errorCodes returns the sorted canonical Protocol error codes.
func errorCodes() []string {
	cs := protoerrors.Codes()
	out := make([]string, 0, len(cs))
	for _, c := range cs {
		out = append(out, string(c))
	}
	sort.Strings(out)
	return out
}

// scanEventTypes walks root/internal and returns the sorted unique set of
// event-type wire strings declared as EventType constants. It reads the
// declarations textually rather than seating the event registry, so the
// module's event set is complete without any driver blank-imports.
func scanEventTypes(root string) ([]string, error) {
	seen := make(map[string]struct{})
	walkRoot := filepath.Join(root, "internal")
	err := filepath.WalkDir(walkRoot, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() {
			if d.Name() == "testdata" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		src, readErr := os.ReadFile(path) //nolint:gosec // G304: build-time scan of the repository's own internal/ source tree (trusted, not attacker-controlled); only non-test .go files are read
		if readErr != nil {
			return fmt.Errorf("read %q: %w", path, readErr)
		}
		for _, m := range eventConstRe.FindAllStringSubmatch(string(src), -1) {
			seen[m[1]] = struct{}{}
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(seen))
	for et := range seen {
		out = append(out, et)
	}
	sort.Strings(out)
	return out, nil
}
