// Protocol TypeScript lockstep guard tests.
//
// Runnable in `npm run test` so a regression fails CI even if a developer
// skips `npm run lint` — the guard re-runs the SAME scanner the lint gate and
// the `make protocol-ts-gen-check` gate wire in, so the gates can never
// disagree. The guard verifies the hand-maintained Console wire-type
// interfaces declare every field of the Go-generated wire manifest
// (`wire-manifest.gen.json`), with a justified allowlist for the wire types
// the Console intentionally leaves untyped.

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

// The lint gate's scanner, imported directly so test + lint share one source.
import { runChecks } from '../../../../scripts/check-protocol-ts-lockstep.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const MANIFEST = join(HERE, '..', 'wire-manifest.gen.json');
const ALLOW = join(HERE, '..', '..', '..', '..', 'scripts', 'protocol-ts-untyped-allow.json');

describe('protocol-ts lockstep guard', () => {
  it('reports zero manifest ↔ TS-client violations', () => {
    const violations = runChecks();
    expect(violations, violations.join('\n')).toEqual([]);
  });

  it('the committed manifest carries the GENERATED / DO-NOT-EDIT banner', () => {
    const manifest = JSON.parse(readFileSync(MANIFEST, 'utf8')) as { _comment: string };
    expect(manifest._comment).toMatch(/GENERATED BY cmd\/harbor-protocol-ts-lockstep/);
    expect(manifest._comment).toMatch(/DO NOT EDIT/);
  });

  it('every untyped-allowlist entry carries a justification string', () => {
    const allow = JSON.parse(readFileSync(ALLOW, 'utf8')) as { types: Record<string, string> };
    for (const [name, reason] of Object.entries(allow.types)) {
      expect(reason, `allowlist entry "${name}" must carry a justification`).toBeTruthy();
      expect(typeof reason).toBe('string');
    }
  });
});
