// Harbor Console — the unified typed Protocol client (D-121,
// CONVENTIONS.md §6).
//
// The foundation audit found five hand-authored Protocol clients —
// `ToolsClient`, `MemoryClient`, `FlowsClient`, the `mcpApi` object, and
// `HTTPProtocolClient` — each with its own error class, its own
// identity-passing convention, and its own `fetch` choke point. This module
// unifies them onto ONE `HarborClient` class with method namespaces hanging
// off it (`client.tools.list(...)`, `client.memory.health(...)`, …), one
// `ProtocolError`, and ONE transport choke point.
//
// `.svelte` components NEVER call `fetch` directly (CLAUDE.md §4.5 rule 5,
// §13). They construct a `HarborClient` (or receive an injected
// `ProtocolClient`) and call its typed namespace methods.
//
// # Routes
//
// The Runtime does not serve a single uniform endpoint shape. Each namespace
// method targets whatever route the Runtime actually mounts for it —
// `tools.*` at `POST /v1/tools/{verb}`, `memory.*` at `POST /v1/memory/{verb}`,
// `flows.*` at `POST /v1/flows/...`, `artifacts.*` and `mcp.servers.*` at the
// control surface `POST /v1/control/{method}` (CONVENTIONS.md §6).
//
// # Deviation note (D-093)
//
// D-093 pins `src/lib/protocol.ts` as generated by `cmd/harbor-gen-protocol-ts`.
// That generator binary has not yet landed (Phase 72h committed `protocol.ts`
// as a hand-shaped stub; the five legacy per-page clients are likewise hand-
// authored). This module is the hand-authored unified client; when the
// generator lands, the wire types fold into the generated file and this client
// re-exports them — a mechanical migration.

import { ProtocolError, type ProtocolErrorBody } from './errors.js';
import type { RuntimeConnection } from '../connection.js';
import type {
	MemoryGetResponse,
	MemoryListRequest,
	MemoryListResponse,
	MemoryHealthResponse
} from './memory-types.js';
import type { EventAggregateRequest, EventAggregateResponse } from './events.js';
import type { RuntimeCounters, RuntimeHealth } from './posture.js';
import type { PauseListRequest, PauseListResponse } from './pause.js';

/* ------------------------------------------------------------------ */
/* Transport                                                           */
/* ------------------------------------------------------------------ */

/** The HTTP verb a route is mounted under. All Protocol routes are POST. */
type Method = 'POST';

/** Options the `HarborClient` is constructed with. */
export interface HarborClientOptions {
	/** The resolved Runtime connection (base URL + token + identity triple). */
	connection: RuntimeConnection;
	/**
	 * Injectable `fetch` implementation. Defaults to `globalThis.fetch`; tests
	 * and the Playwright harness inject a deterministic stub so the client is
	 * exercised without a live Runtime.
	 */
	fetchImpl?: typeof fetch;
}

/**
 * Transport is the single `fetch` choke point shared by every namespace. It
 * serialises the request, folds the identity triple into the body (the
 * Runtime's defence-in-depth identity check), attaches the bearer token + the
 * `X-Harbor-*` identity headers, and raises a typed {@link ProtocolError} on
 * any non-2xx response — never a silently-swallowed empty result (CLAUDE.md
 * §13 "no silent degradation").
 */
export class Transport {
	readonly #baseURL: string;
	readonly #token: string;
	readonly #identity: RuntimeConnection['identity'];
	readonly #fetch: typeof fetch;

	constructor(opts: HarborClientOptions) {
		this.#baseURL = opts.connection.baseURL.replace(/\/$/, '');
		this.#token = opts.connection.token;
		this.#identity = opts.connection.identity;
		this.#fetch = opts.fetchImpl ?? globalThis.fetch.bind(globalThis);
	}

	/** The identity triple this transport is scoped to (read-only). */
	get identity(): RuntimeConnection['identity'] {
		return this.#identity;
	}

	/**
	 * The Runtime base URL (no trailing slash). Exposed so the
	 * `events.subscribe` SSE consumer can construct an `EventSource`
	 * target — the SSE stream is a long-lived `GET` that the request /
	 * response `Transport.request` choke point does not model. The SSE
	 * consumer is still a member of the `events` namespace, not a
	 * hand-rolled per-page client (CONVENTIONS.md §6).
	 */
	get baseURL(): string {
		return this.#baseURL;
	}

	/** The bearer JWT this transport carries (read-only). */
	get token(): string {
		return this.#token;
	}

	/**
	 * Issue one typed request against a Runtime route. `path` is the route the
	 * Runtime mounts (e.g. `/v1/tools/list`, `/v1/control/artifacts.list`).
	 * The identity triple is folded into the body; `body` is merged over it so
	 * a caller-supplied `identity` field wins for cross-tenant admin calls.
	 */
	async request<T>(path: string, body: Record<string, unknown> = {}, method: Method = 'POST'): Promise<T> {
		const payload = JSON.stringify({ identity: this.#identity, ...body });
		const resp = await this.#fetch(`${this.#baseURL}${path}`, {
			method,
			headers: {
				'Content-Type': 'application/json',
				Authorization: `Bearer ${this.#token}`,
				'X-Harbor-Tenant': this.#identity.tenant,
				'X-Harbor-User': this.#identity.user,
				'X-Harbor-Session': this.#identity.session
			},
			body: payload
		});
		const text = await resp.text();
		if (!resp.ok) {
			let code = 'runtime_error';
			let message = text || resp.statusText || `HTTP ${resp.status}`;
			try {
				const err = JSON.parse(text) as Partial<ProtocolErrorBody>;
				if (err.code) code = err.code;
				if (err.message) message = err.message;
			} catch {
				// Non-JSON error body — keep the raw text as the message; never
				// swallow the failure (CLAUDE.md §5 fail-loudly).
			}
			throw new ProtocolError(code, message, resp.status);
		}
		return (text.length > 0 ? JSON.parse(text) : {}) as T;
	}
}

/* ------------------------------------------------------------------ */
/* Namespace surfaces                                                  */
/* ------------------------------------------------------------------ */

/**
 * The `tools.*` namespace — ported from the legacy `ToolsClient`. The Runtime
 * mounts these at `POST /v1/tools/{verb}` (Phase 73f / D-116).
 */
export class ToolsNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `tools.list` — paginated, faceted catalog projection. */
	list<R = unknown>(filter: Record<string, unknown> = {}, page = 1, pageSize = 50): Promise<R> {
		return this.#t.request<R>('/v1/tools/list', { filter, page, page_size: pageSize });
	}
	/** `tools.get` — single catalog-row projection. */
	get<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/tools/get', { id });
	}
	/** `tools.describe` — full manifest projection. */
	describe<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/tools/describe', { id });
	}
	/** `tools.metrics` — per-tool error-rate gauges + status pill. */
	metrics<R = unknown>(id: string, window = '1h'): Promise<R> {
		return this.#t.request<R>('/v1/tools/metrics', { id, window });
	}
	/** `tools.content_stats` — per-tool result-size histogram. */
	contentStats<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/tools/content_stats', { id });
	}
	/** `tools.set_approval_policy` — ADMIN method (D-079 scope-gated). */
	setApprovalPolicy<R = unknown>(id: string, policy: string): Promise<R> {
		return this.#t.request<R>('/v1/tools/set_approval_policy', { id, policy });
	}
	/** `tools.revoke_oauth` — ADMIN method (D-079 scope-gated). */
	revokeOAuth<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/tools/revoke_oauth', { id });
	}
}

/**
 * The `memory.*` namespace — ported from the legacy `MemoryClient`. The Runtime
 * mounts these at `POST /v1/memory/{verb}` (Phase 73j / D-118).
 */
export class MemoryNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `memory.list` — paginated, identity-scope-filtered memory records. */
	list(req: MemoryListRequest = {}): Promise<MemoryListResponse> {
		return this.#t.request<MemoryListResponse>(
			'/v1/memory/list',
			req as unknown as Record<string, unknown>
		);
	}
	/** `memory.get` — full detail of one memory record. */
	get(key: string): Promise<MemoryGetResponse> {
		return this.#t.request<MemoryGetResponse>('/v1/memory/get', { key });
	}
	/** `memory.health` — aggregate memory-health counters. */
	health(): Promise<MemoryHealthResponse> {
		return this.#t.request<MemoryHealthResponse>('/v1/memory/health', {});
	}
}

/**
 * The `flows.*` namespace — ported from the legacy `FlowsClient`. The Runtime
 * mounts these at `POST /v1/flows/...` (Phase 73i / D-117).
 */
export class FlowsNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `flows.list` — paginated registered-flow catalog with aggregates. */
	list<R = unknown>(req: Record<string, unknown> = {}): Promise<R> {
		return this.#t.request<R>('/v1/flows/list', req);
	}
	/** `flows.describe` — a flow's full engine-graph description. */
	describe<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/flows/describe', req);
	}
	/** `flows.runs.list` — a flow's paginated run history. */
	runsList<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/flows/runs/list', req);
	}
	/** `flows.runs.describe` — a single run's per-node timeline. */
	runsDescribe<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/flows/runs/describe', req);
	}
	/** `flows.run` — invoke a one-shot run (ADMIN method, D-079 scope-gated). */
	run<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/flows/run', req);
	}
	/** `flows.metrics` — a flow's time-bucketed sparkline aggregates. */
	metrics<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/flows/metrics', req);
	}
}

/**
 * The `artifacts.*` namespace — ported from the legacy `HTTPProtocolClient`.
 * The Runtime mounts these on the control surface at
 * `POST /v1/control/artifacts.{verb}` (Phase 73l / D-120).
 */
export class ArtifactsNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `artifacts.list` — the identity-scoped, metadata-only artifact catalog. */
	list<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/control/artifacts.list', req);
	}
	/** `artifacts.put` — the Console / Playground file-upload pipeline. */
	put<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/control/artifacts.put', req);
	}
	/** `artifacts.get_ref` — the read-side presigned-URL resolver (D-022/D-026). */
	getRef<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/control/artifacts.get_ref', req);
	}
}

/**
 * The `mcp.servers.*` surface under the `mcp` namespace — ported from the
 * legacy `mcpApi` object. The Runtime mounts these on the control surface at
 * `POST /v1/control/mcp.servers.{verb}` (Phase 73k / D-119).
 */
export class MCPServersNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `mcp.servers.list` — the paginated, faceted MCP-server catalog. */
	list<R = unknown>(filter: Record<string, unknown> = {}): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.list', filter);
	}
	/** `mcp.servers.get` — one server's full descriptor. */
	get<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.get', { name });
	}
	/** `mcp.servers.resources` — a server's advertised resources. */
	resources<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.resources', { name });
	}
	/** `mcp.servers.prompts` — a server's advertised prompts. */
	prompts<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.prompts', { name });
	}
	/** `mcp.servers.health` — a server's handshake / reconnect health. */
	health<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.health', { name });
	}
	/** `mcp.servers.policy` — a server's read-only ToolPolicy projection. */
	policy<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.policy', { name });
	}
	/** `mcp.servers.bindings.list` — a server's OAuth bindings (no plaintext). */
	bindings<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.bindings.list', { name });
	}
	/** `mcp.servers.refresh_discovery` — re-run a server's discovery. */
	refreshDiscovery<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.refresh_discovery', { name });
	}
	/** `mcp.servers.probe` — a one-shot connectivity probe. */
	probe<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.probe', { name });
	}
	/** `mcp.servers.refresh_binding` — start an OAuth re-bind flow. */
	refreshBinding<R = unknown>(name: string, principalId: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.refresh_binding', {
			name,
			principal_id: principalId
		});
	}
	/** `mcp.servers.revoke_binding` — revoke an OAuth binding. */
	revokeBinding<R = unknown>(name: string, principalId: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.revoke_binding', {
			name,
			principal_id: principalId
		});
	}
	/** `mcp.servers.set_raw_html_trust` — toggle a server's raw-HTML trust. */
	setRawHTMLTrust<R = unknown>(name: string, trusted: boolean): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.set_raw_html_trust', {
			name,
			trusted
		});
	}
}

/**
 * The `events.*` namespace — the Console Events page surface (Phase 73g
 * / D-125). Phase 73g ships NO new Protocol method; this namespace wraps
 * the already-shipped `events.aggregate` (`POST /v1/events/aggregate` —
 * Phase 72a) and exposes the `events.subscribe` SSE endpoint
 * (`GET /v1/events` — Phase 72) as a typed `EventSource`-target builder.
 *
 * # Why the SSE stream is not a `Transport.request`
 *
 * `events.subscribe` is a long-lived server-sent-event stream, not a
 * request / response round-trip — `Transport.request` (the single
 * `fetch` choke point) does not model it. The namespace exposes
 * {@link subscribeURL}; the page-side `EventsSubscription` wrapper
 * opens an `EventSource` against it. Bearer auth rides as a query
 * param because `EventSource` cannot set an `Authorization` header —
 * the runtime accepts the bearer token on either surface (Phase 60).
 * No `.svelte` file constructs the URL or the `EventSource` by hand;
 * both go through this namespace + the `EventsSubscription` wrapper.
 */
export class EventsNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}

	/** `events.aggregate` — the time-bucketed per-type count series. */
	aggregate(req: EventAggregateRequest): Promise<EventAggregateResponse> {
		return this.#t.request<EventAggregateResponse>(
			'/v1/events/aggregate',
			req as unknown as Record<string, unknown>
		);
	}

	/**
	 * The `events.subscribe` SSE endpoint URL the page-side
	 * `EventsSubscription` opens an `EventSource` against. The optional
	 * `eventTypes` narrow to a repeatable `type` query param; `admin`
	 * requests cross-tenant fan-in (the runtime gates it on
	 * `auth.ScopeAdmin` / `auth.ScopeConsoleFleet`, D-079). The bearer
	 * token rides as `access_token` — `EventSource` cannot carry an
	 * `Authorization` header.
	 */
	subscribeURL(opts: { eventTypes?: string[]; admin?: boolean } = {}): string {
		const url = new URL(`${this.#t.baseURL}/v1/events`);
		for (const t of opts.eventTypes ?? []) {
			url.searchParams.append('type', t);
		}
		if (opts.admin) {
			url.searchParams.set('admin', '1');
		}
		url.searchParams.set('access_token', this.#t.token);
		return url.toString();
	}

	/** The identity triple the events subscription is scoped to. */
	get identity(): RuntimeConnection['identity'] {
		return this.#t.identity;
	}
}

/**
 * The `tasks.*` namespace — Phase 73d / D-123. The Runtime mounts the
 * two Tasks-page read methods at `POST /v1/tasks/{verb}`. The Console
 * Tasks page consumes the EXISTING Phase 54 control verbs for mutation
 * through {@link ControlNamespace} — there is NO `tasks.*` mutating
 * method (CLAUDE.md §13 "no parallel implementations").
 */
export class TasksNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `tasks.list` — paginated, faceted task-row projection + aggregates. */
	list<R = unknown>(req: Record<string, unknown> = {}): Promise<R> {
		return this.#t.request<R>('/v1/tasks/list', req);
	}
	/** `tasks.get` — enriched single-task detail. */
	get<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/tasks/get', { id });
	}
}

/**
 * The `control.*` namespace — the shipped Phase 54 task-control surface
 * (`cancel` / `pause` / `resume` / `prioritize` / `approve` / `reject`
 * + `redirect` / `inject_context` / `user_message`). The Runtime mounts
 * these on the control surface at `POST /v1/control/{verb}`.
 *
 * The Console Tasks-page bulk-action toolbar + per-task action bar
 * consume THESE shipped verbs — no new control method is minted
 * (CLAUDE.md §13). A verb targets a specific run by its task id carried
 * in `identity.run`; the optional `payload` carries method-specific
 * arguments (the `priority` for `prioritize`).
 */
export class ControlNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/**
	 * Dispatch a Phase 54 control verb against the run identified by
	 * `taskID` (carried in `identity.run`). `payload` carries the
	 * method-specific arguments; `scope` is the caller's steering scope
	 * claim. Returns the {@link ProtocolError}-on-failure ControlResponse.
	 */
	dispatch<R = unknown>(
		verb: string,
		taskID: string,
		payload?: Record<string, unknown>,
		scope = 'owner_user'
	): Promise<R> {
		const body: Record<string, unknown> = {
			identity: { run: taskID, scope }
		};
		if (payload !== undefined) {
			body.payload = payload;
		}
		return this.#t.request<R>(`/v1/control/${verb}`, body);
	}
	/**
	 * `start` — spawn a new foreground task in the caller's session.
	 *
	 * Round-6 F7 — `start` is NOT a steering verb. The wire shape is
	 * FLAT (mirrors `internal/protocol/types/control.go::StartRequest`):
	 * `{identity:triple, query, description, priority, idempotency_key}`,
	 * with no `task:{...}` wrapper. The previous Playground sendMessage
	 * went through `dispatch('user_message', sessionID, ...)` which (a)
	 * treated sessionID as a taskID and (b) used the steering-verb body
	 * shape — the runtime rejected it with "no live run for the
	 * requested run id" and the chat panel could never send its first
	 * message.
	 *
	 * The runtime folds the connection-scoped identity (tenant/user/
	 * session) into `identity` automatically via {@link Transport.request}
	 * — we do NOT override identity here. Kind is hardcoded to
	 * `foreground` at the dispatch layer (background runs go through
	 * `tasks.spawn_background`, not `start`).
	 */
	start<R = { task_id: string; reused: boolean; protocol_version: string }>(
		query: string,
		opts: {
			description?: string;
			priority?: number;
			idempotencyKey?: string;
			inputArtifactIDs?: string[];
		} = {}
	): Promise<R> {
		const body: Record<string, unknown> = { query };
		if (opts.description !== undefined) {
			body.description = opts.description;
		}
		if (opts.priority !== undefined) {
			body.priority = opts.priority;
		}
		if (opts.idempotencyKey !== undefined) {
			body.idempotency_key = opts.idempotencyKey;
		}
		// Round-7 F11 / D-166 — multimodal artifact inputs. The runtime
		// resolves each id to a `planner.InputArtifactView` and routes
		// per MIME on the first planner turn: image/* bytes inline as
		// `ImagePart.DataURL`; pdf/audio stay as typed refs; everything
		// else emits an `ArtifactStub` text block the LLM routes via
		// the tool catalog. Empty / undefined keeps the wire shape
		// text-only (the omitempty tag elides the field server-side).
		if (opts.inputArtifactIDs !== undefined && opts.inputArtifactIDs.length > 0) {
			body.input_artifact_ids = opts.inputArtifactIDs;
		}
		return this.#t.request<R>('/v1/control/start', body);
	}
	/** `cancel` — cancel the task's run. */
	cancel<R = unknown>(taskID: string): Promise<R> {
		return this.dispatch<R>('cancel', taskID);
	}
	/** `pause` — pause the task's run. */
	pause<R = unknown>(taskID: string): Promise<R> {
		return this.dispatch<R>('pause', taskID);
	}
	/** `resume` — resume the task's run. */
	resume<R = unknown>(taskID: string): Promise<R> {
		return this.dispatch<R>('resume', taskID);
	}
	/** `prioritize` — set the task's numeric priority. */
	prioritize<R = unknown>(taskID: string, priority: number): Promise<R> {
		return this.dispatch<R>('prioritize', taskID, { priority });
	}
	/** `approve` — approve a pending HITL gate on the task's run. */
	approve<R = unknown>(taskID: string): Promise<R> {
		return this.dispatch<R>('approve', taskID);
	}
	/** `reject` — reject a pending HITL gate on the task's run. */
	reject<R = unknown>(taskID: string): Promise<R> {
		return this.dispatch<R>('reject', taskID);
	}
}

/**
 * The `agents.*` namespace (Phase 73e / D-124). The Runtime mounts these
 * at `POST /v1/agents/{verb}` (the same one-shot request/response shape
 * as `tools.*`). All eight methods are READ-ONLY projections of the
 * Agent Registry; the five agent-control verbs the Agents page exposes
 * (Pause / Drain / Restart / Force-Stop / Deregister) are the EXISTING
 * shipped `registry.*` control verbs (D-066), not part of this surface.
 */
export class AgentsNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `agents.list` — paginated, faceted agent catalog projection. */
	list<R = unknown>(req: Record<string, unknown> = {}): Promise<R> {
		return this.#t.request<R>('/v1/agents/list', req);
	}
	/** `agents.get` — one agent's full registration-identity projection. */
	get<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/agents/get', { id });
	}
	/** `agents.tools` — the agent's tool bindings + per-binding OAuth. */
	tools<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/agents/tools', { id });
	}
	/** `agents.memory` — the agent's memory strategy + TTL + scope. */
	memory<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/agents/memory', { id });
	}
	/** `agents.governance` — per-identity-tier ceilings + spend + limits. */
	governance<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/agents/governance', { id });
	}
	/** `agents.skills` — the agent's attached skills. */
	skills<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/agents/skills', { id });
	}
	/** `agents.permissions` — the agent's permission model (V1: implicit). */
	permissions<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/agents/permissions', { id });
	}
	/** `agents.metrics` — the registry-wide rollup the page hero shows. */
	metrics<R = unknown>(): Promise<R> {
		return this.#t.request<R>('/v1/agents/metrics', {});
	}
}

/**
 * The `sessions.*` namespace (Phase 73c / D-122). The Runtime mounts
 * these at `POST /v1/sessions/{verb}` — the Sessions handler shares the
 * same identity + cross-tenant scope-claim gating the tools / flows
 * handlers use. Both methods are read-only.
 */
export class SessionsNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `sessions.list` — the paginated, filtered session catalog. */
	list<R = unknown>(req: Record<string, unknown> = {}): Promise<R> {
		return this.#t.request<R>('/v1/sessions/list', req);
	}
	/** `sessions.inspect` — a single session's full snapshot. */
	inspect<R = unknown>(sessionID: string): Promise<R> {
		return this.#t.request<R>('/v1/sessions/inspect', { session_id: sessionID });
	}
}

/**
 * The `topology.*` namespace — Phase 74 / D-114, consumed by the
 * Console Live Runtime page (Phase 73b / D-126). The Runtime mounts
 * `topology.snapshot` on the control surface at
 * `POST /v1/control/topology.snapshot`. It is a pure read — the page's
 * topology canvas renders the returned `TopologyProjection`.
 */
export class TopologyNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `topology.snapshot` — the Runtime engine's static node graph + live per-edge queue depth. */
	snapshot<R = unknown>(): Promise<R> {
		return this.#t.request<R>('/v1/control/topology.snapshot', {});
	}
}

/**
 * The `runs.*` namespace — Phase 73n / D-130, consumed by the Console
 * Playground page. The Runtime mounts `runs.set_overrides` at
 * `POST /v1/runs/set_overrides`. It records the reasoning-effort /
 * temperature / max-tokens / system-prompt override applied to the NEXT
 * message in the operator's session.
 */
export class RunsNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/**
	 * `runs.set_overrides` — record the next-message override. `overrides`
	 * carries `session_id` plus the optional tuning fields
	 * (`reasoning_effort` / `temperature` / `max_tokens` /
	 * `system_prompt_override`). The override is session-scoped and
	 * one-shot — it applies to the next `user_message` only.
	 */
	setOverrides<R = unknown>(overrides: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/runs/set_overrides', { overrides });
	}
}

/**
 * The `runtime.*` namespace — the read-only posture surface the Console
 * Overview page (Phase 73a / D-127) consumes. Phase 73a ships NO new
 * Protocol method: `runtime.counters` and `runtime.health` are already
 * shipped (Phase 72f / D-111) on the `PostureSurface`. Posture methods
 * route through the control transport — the Runtime mounts them at
 * `POST /v1/control/runtime.{counters,health}` (`methods.IsPostureMethod`
 * branches the route table). Both are pure reads; identity is mandatory
 * and a cross-tenant read requires `auth.ScopeAdmin` (D-079).
 */
export class RuntimeNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `runtime.counters` — the low-cardinality live-counter rollup. */
	counters(): Promise<RuntimeCounters> {
		return this.#t.request<RuntimeCounters>('/v1/control/runtime.counters', {});
	}
	/** `runtime.health` — the per-subsystem readiness rollup. */
	health(): Promise<RuntimeHealth> {
		return this.#t.request<RuntimeHealth>('/v1/control/runtime.health', {});
	}
}

/**
 * The `pause.*` namespace — the read-only pause-snapshot surface the
 * Console Overview-page intervention queue (Phase 73a / D-127)
 * consumes. Phase 73a ships NO new Protocol method: `pause.list` is
 * already shipped (Phase 72e / D-110) at `POST /v1/pause/list`. It is a
 * READ-ONLY snapshot — it does NOT mutate the Coordinator registry and
 * does NOT call Resume. The intervention queue's Approve / Reject row
 * actions invoke the SHIPPED Phase 54 `approve` / `reject` control
 * verbs through {@link ControlNamespace} — there is no parallel pause
 * mutation here (CLAUDE.md §13). Identity is mandatory; a cross-tenant
 * filter requires the verified `auth.ScopeAdmin` claim (D-079).
 */
export class PauseNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `pause.list` — the paginated, identity-scope-filtered pause snapshot. */
	list(req: PauseListRequest = {}): Promise<PauseListResponse> {
		return this.#t.request<PauseListResponse>(
			'/v1/pause/list',
			req as unknown as Record<string, unknown>
		);
	}
}

/**
 * The `runtime.*` / `governance.posture` / `llm.posture` posture
 * namespace — consumed by the Console Settings page (Phase 73m / D-129).
 * The five `runtime.*` / `metrics.*` reads are shipped by Phase 72f
 * (D-111); `governance.posture` / `llm.posture` by Phase 72g (D-112).
 * The Runtime mounts all seven on the control surface at
 * `POST /v1/control/{method}`. Phase 73m is a pure CONSUMER — it ships
 * none of these methods, it only reads them.
 */
export class PostureNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `runtime.info` — build identity + Protocol version + uptime + capabilities. */
	info<R = unknown>(): Promise<R> {
		return this.#t.request<R>('/v1/control/runtime.info', {});
	}
	/** `runtime.health` — per-subsystem readiness rollup. */
	health<R = unknown>(): Promise<R> {
		return this.#t.request<R>('/v1/control/runtime.health', {});
	}
	/** `runtime.drivers` — configured driver name per persistence-shaped subsystem. */
	drivers<R = unknown>(): Promise<R> {
		return this.#t.request<R>('/v1/control/runtime.drivers', {});
	}
	/** `governance.posture` — the read-only D-081 IdentityTiers view. */
	governance<R = unknown>(): Promise<R> {
		return this.#t.request<R>('/v1/control/governance.posture', {});
	}
	/** `llm.posture` — bound LLM provider / model / region + the MockMode flag. */
	llm<R = unknown>(): Promise<R> {
		return this.#t.request<R>('/v1/control/llm.posture', {});
	}
}

/**
 * The `auth.*` namespace — Phase 73m / D-129. The Runtime mounts the
 * single net-new method at `POST /v1/auth/{verb}`. `auth.rotate_token`
 * is an ADMIN method: the Runtime gates it on the verified
 * `auth.ScopeAdmin` claim (D-079).
 */
export class AuthNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/**
	 * `auth.rotate_token` — rotate the operator's Protocol-auth token.
	 * Returns the one-time-revealed re-minted token. ADMIN-gated:
	 * a connection without the admin scope claim gets a
	 * `ProtocolError` carrying `identity_scope_required` (HTTP 403).
	 */
	rotateToken<R = unknown>(): Promise<R> {
		return this.#t.request<R>('/v1/auth/rotate_token', {});
	}
}

/** The `mcp` namespace — groups the MCP-server surface. */
export class MCPNamespace {
	/** The `mcp.servers.*` method surface. */
	readonly servers: MCPServersNamespace;
	constructor(t: Transport) {
		this.servers = new MCPServersNamespace(t);
	}
}

/* ------------------------------------------------------------------ */
/* ProtocolClient interface + HarborClient                             */
/* ------------------------------------------------------------------ */

/**
 * The injectable Protocol-client interface. A page depends on THIS interface,
 * never on the concrete `HarborClient` — tests and the Playwright harness
 * inject a deterministic in-page implementation (CONVENTIONS.md §6).
 */
export interface ProtocolClient {
	readonly tools: ToolsNamespace;
	readonly tasks: TasksNamespace;
	readonly control: ControlNamespace;
	readonly memory: MemoryNamespace;
	readonly flows: FlowsNamespace;
	readonly artifacts: ArtifactsNamespace;
	readonly mcp: MCPNamespace;
	readonly events: EventsNamespace;
	readonly agents: AgentsNamespace;
	readonly sessions: SessionsNamespace;
	readonly topology: TopologyNamespace;
	readonly runs: RunsNamespace;
	readonly runtime: RuntimeNamespace;
	readonly pause: PauseNamespace;
	readonly posture: PostureNamespace;
	readonly auth: AuthNamespace;

	/**
	 * Round-8 F1 / phase 84a: returns the per-instance Protocol
	 * capabilities the runtime advertises (memoised per client). Pages
	 * with optional surfaces gate their fetches on
	 * `caps.has('topology_snapshot')` etc.
	 */
	capabilities(): Promise<ReadonlySet<string>>;
}

/**
 * The unified production Protocol client. ONE class, ONE `fetch` choke point
 * (the shared {@link Transport}), method namespaces hanging off it. Constructed
 * once from a resolved {@link RuntimeConnection}; immutable after construction.
 *
 * A page resolves its connection via `connection.ts`, constructs a
 * `HarborClient`, and calls `client.<namespace>.<method>(...)`. New page
 * surfaces add a namespace here — never a new top-level client.
 */
export class HarborClient implements ProtocolClient {
	readonly tools: ToolsNamespace;
	readonly tasks: TasksNamespace;
	readonly control: ControlNamespace;
	readonly memory: MemoryNamespace;
	readonly flows: FlowsNamespace;
	readonly artifacts: ArtifactsNamespace;
	readonly mcp: MCPNamespace;
	readonly events: EventsNamespace;
	readonly agents: AgentsNamespace;
	readonly sessions: SessionsNamespace;
	readonly topology: TopologyNamespace;
	readonly runs: RunsNamespace;
	readonly runtime: RuntimeNamespace;
	readonly pause: PauseNamespace;
	readonly posture: PostureNamespace;
	readonly auth: AuthNamespace;

	// Round-8 F1 / phase 84a: per-connection capability cache. Pages
	// with optional Protocol surfaces (Live Runtime topology view,
	// Playground topology trace) consult this BEFORE calling
	// `topology.snapshot` / similar, so the browser console stays
	// clean on planner/RunLoop runtimes that don't advertise the
	// surface. Lazy-loaded on first `capabilities()` call; the
	// returned Set is immutable, the resolution memoised for the
	// lifetime of the client (a re-attach builds a new HarborClient).
	#capsCache: Promise<ReadonlySet<string>> | null = null;

	constructor(opts: HarborClientOptions) {
		const transport = new Transport(opts);
		this.tools = new ToolsNamespace(transport);
		this.tasks = new TasksNamespace(transport);
		this.control = new ControlNamespace(transport);
		this.memory = new MemoryNamespace(transport);
		this.flows = new FlowsNamespace(transport);
		this.artifacts = new ArtifactsNamespace(transport);
		this.mcp = new MCPNamespace(transport);
		this.events = new EventsNamespace(transport);
		this.agents = new AgentsNamespace(transport);
		this.sessions = new SessionsNamespace(transport);
		this.topology = new TopologyNamespace(transport);
		this.runs = new RunsNamespace(transport);
		this.runtime = new RuntimeNamespace(transport);
		this.pause = new PauseNamespace(transport);
		this.posture = new PostureNamespace(transport);
		this.auth = new AuthNamespace(transport);
	}

	/**
	 * Returns the runtime's advertised capability set, fetched once per
	 * client and memoised. Pages with optional Protocol surfaces call
	 * `await client.capabilities()` then branch on `caps.has('...')`
	 * instead of eagerly invoking a method the runtime might not
	 * advertise. Round-8 F1 / phase 84a.
	 *
	 * The fetch goes through `posture.info` (the SHIPPED Phase 72f
	 * surface, every runtime advertises it). A network failure rejects
	 * the promise; the resolved Set is frozen.
	 */
	capabilities(): Promise<ReadonlySet<string>> {
		if (this.#capsCache !== null) {
			return this.#capsCache;
		}
		this.#capsCache = this.posture
			.info<{ capabilities?: string[] }>()
			.then((info) => new Set<string>(info.capabilities ?? []));
		return this.#capsCache;
	}
}
