// Harbor Console — the unified typed Protocol client (D-121,
// CONVENTIONS.md §6).
//
// The foundation audit found five hand-authored Protocol clients —
// `ToolsClient`, `MemoryClient`, `FlowsClient`, the `mcpApi` object, and
// `HTTPProtocolClient` — each with its own error class, its own
// identity-passing convention, and its own `fetch` choke point. This module
// unifies them onto ONE `HarborClient` class with method namespaces hanging
// off it (`client.tools.list(...)`, `client.memory.health(...)`, …), one
// `ProtocolError`, and ONE transport choke point.
//
// `.svelte` components NEVER call `fetch` directly (CLAUDE.md §4.5 rule 5,
// §13). They construct a `HarborClient` (or receive an injected
// `ProtocolClient`) and call its typed namespace methods.
//
// # Routes
//
// The Runtime does not serve a single uniform endpoint shape. Each namespace
// method targets whatever route the Runtime actually mounts for it —
// `tools.*` at `POST /v1/tools/{verb}`, `memory.*` at `POST /v1/memory/{verb}`,
// `flows.*` at `POST /v1/flows/...`, `artifacts.*` and `mcp.servers.*` at the
// control surface `POST /v1/control/{method}` (CONVENTIONS.md §6).
//
// # Deviation note (D-093)
//
// D-093 pins `src/lib/protocol.ts` as generated by `cmd/harbor-gen-protocol-ts`.
// That generator binary has not yet landed (Phase 72h committed `protocol.ts`
// as a hand-shaped stub; the five legacy per-page clients are likewise hand-
// authored). This module is the hand-authored unified client; when the
// generator lands, the wire types fold into the generated file and this client
// re-exports them — a mechanical migration.

import { ProtocolError, type ProtocolErrorBody } from './errors.js';
import type { RuntimeConnection } from '../connection.js';

/* ------------------------------------------------------------------ */
/* Transport                                                           */
/* ------------------------------------------------------------------ */

/** The HTTP verb a route is mounted under. All Protocol routes are POST. */
type Method = 'POST';

/** Options the `HarborClient` is constructed with. */
export interface HarborClientOptions {
	/** The resolved Runtime connection (base URL + token + identity triple). */
	connection: RuntimeConnection;
	/**
	 * Injectable `fetch` implementation. Defaults to `globalThis.fetch`; tests
	 * and the Playwright harness inject a deterministic stub so the client is
	 * exercised without a live Runtime.
	 */
	fetchImpl?: typeof fetch;
}

/**
 * Transport is the single `fetch` choke point shared by every namespace. It
 * serialises the request, folds the identity triple into the body (the
 * Runtime's defence-in-depth identity check), attaches the bearer token + the
 * `X-Harbor-*` identity headers, and raises a typed {@link ProtocolError} on
 * any non-2xx response — never a silently-swallowed empty result (CLAUDE.md
 * §13 "no silent degradation").
 */
export class Transport {
	readonly #baseURL: string;
	readonly #token: string;
	readonly #identity: RuntimeConnection['identity'];
	readonly #fetch: typeof fetch;

	constructor(opts: HarborClientOptions) {
		this.#baseURL = opts.connection.baseURL.replace(/\/$/, '');
		this.#token = opts.connection.token;
		this.#identity = opts.connection.identity;
		this.#fetch = opts.fetchImpl ?? globalThis.fetch.bind(globalThis);
	}

	/** The identity triple this transport is scoped to (read-only). */
	get identity(): RuntimeConnection['identity'] {
		return this.#identity;
	}

	/**
	 * Issue one typed request against a Runtime route. `path` is the route the
	 * Runtime mounts (e.g. `/v1/tools/list`, `/v1/control/artifacts.list`).
	 * The identity triple is folded into the body; `body` is merged over it so
	 * a caller-supplied `identity` field wins for cross-tenant admin calls.
	 */
	async request<T>(path: string, body: Record<string, unknown> = {}, method: Method = 'POST'): Promise<T> {
		const payload = JSON.stringify({ identity: this.#identity, ...body });
		const resp = await this.#fetch(`${this.#baseURL}${path}`, {
			method,
			headers: {
				'Content-Type': 'application/json',
				Authorization: `Bearer ${this.#token}`,
				'X-Harbor-Tenant': this.#identity.tenant,
				'X-Harbor-User': this.#identity.user,
				'X-Harbor-Session': this.#identity.session
			},
			body: payload
		});
		const text = await resp.text();
		if (!resp.ok) {
			let code = 'runtime_error';
			let message = text || resp.statusText || `HTTP ${resp.status}`;
			try {
				const err = JSON.parse(text) as Partial<ProtocolErrorBody>;
				if (err.code) code = err.code;
				if (err.message) message = err.message;
			} catch {
				// Non-JSON error body — keep the raw text as the message; never
				// swallow the failure (CLAUDE.md §5 fail-loudly).
			}
			throw new ProtocolError(code, message, resp.status);
		}
		return (text.length > 0 ? JSON.parse(text) : {}) as T;
	}
}

/* ------------------------------------------------------------------ */
/* Namespace surfaces                                                  */
/* ------------------------------------------------------------------ */

/**
 * The `tools.*` namespace — ported from the legacy `ToolsClient`. The Runtime
 * mounts these at `POST /v1/tools/{verb}` (Phase 73f / D-116).
 */
export class ToolsNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `tools.list` — paginated, faceted catalog projection. */
	list<R = unknown>(filter: Record<string, unknown> = {}, page = 1, pageSize = 50): Promise<R> {
		return this.#t.request<R>('/v1/tools/list', { filter, page, page_size: pageSize });
	}
	/** `tools.get` — single catalog-row projection. */
	get<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/tools/get', { id });
	}
	/** `tools.describe` — full manifest projection. */
	describe<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/tools/describe', { id });
	}
	/** `tools.metrics` — per-tool error-rate gauges + status pill. */
	metrics<R = unknown>(id: string, window = '1h'): Promise<R> {
		return this.#t.request<R>('/v1/tools/metrics', { id, window });
	}
	/** `tools.content_stats` — per-tool result-size histogram. */
	contentStats<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/tools/content_stats', { id });
	}
	/** `tools.set_approval_policy` — ADMIN method (D-079 scope-gated). */
	setApprovalPolicy<R = unknown>(id: string, policy: string): Promise<R> {
		return this.#t.request<R>('/v1/tools/set_approval_policy', { id, policy });
	}
	/** `tools.revoke_oauth` — ADMIN method (D-079 scope-gated). */
	revokeOAuth<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/tools/revoke_oauth', { id });
	}
}

/**
 * The `memory.*` namespace — ported from the legacy `MemoryClient`. The Runtime
 * mounts these at `POST /v1/memory/{verb}` (Phase 73j / D-118).
 */
export class MemoryNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `memory.list` — paginated, identity-scope-filtered memory records. */
	list<R = unknown>(req: Record<string, unknown> = {}): Promise<R> {
		return this.#t.request<R>('/v1/memory/list', req);
	}
	/** `memory.get` — full detail of one memory record. */
	get<R = unknown>(key: string): Promise<R> {
		return this.#t.request<R>('/v1/memory/get', { key });
	}
	/** `memory.health` — aggregate memory-health counters. */
	health<R = unknown>(): Promise<R> {
		return this.#t.request<R>('/v1/memory/health', {});
	}
}

/**
 * The `flows.*` namespace — ported from the legacy `FlowsClient`. The Runtime
 * mounts these at `POST /v1/flows/...` (Phase 73i / D-117).
 */
export class FlowsNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `flows.list` — paginated registered-flow catalog with aggregates. */
	list<R = unknown>(req: Record<string, unknown> = {}): Promise<R> {
		return this.#t.request<R>('/v1/flows/list', req);
	}
	/** `flows.describe` — a flow's full engine-graph description. */
	describe<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/flows/describe', req);
	}
	/** `flows.runs.list` — a flow's paginated run history. */
	runsList<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/flows/runs/list', req);
	}
	/** `flows.runs.describe` — a single run's per-node timeline. */
	runsDescribe<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/flows/runs/describe', req);
	}
	/** `flows.run` — invoke a one-shot run (ADMIN method, D-079 scope-gated). */
	run<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/flows/run', req);
	}
	/** `flows.metrics` — a flow's time-bucketed sparkline aggregates. */
	metrics<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/flows/metrics', req);
	}
}

/**
 * The `artifacts.*` namespace — ported from the legacy `HTTPProtocolClient`.
 * The Runtime mounts these on the control surface at
 * `POST /v1/control/artifacts.{verb}` (Phase 73l / D-120).
 */
export class ArtifactsNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `artifacts.list` — the identity-scoped, metadata-only artifact catalog. */
	list<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/control/artifacts.list', req);
	}
	/** `artifacts.put` — the Console / Playground file-upload pipeline. */
	put<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/control/artifacts.put', req);
	}
	/** `artifacts.get_ref` — the read-side presigned-URL resolver (D-022/D-026). */
	getRef<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/control/artifacts.get_ref', req);
	}
}

/**
 * The `mcp.servers.*` surface under the `mcp` namespace — ported from the
 * legacy `mcpApi` object. The Runtime mounts these on the control surface at
 * `POST /v1/control/mcp.servers.{verb}` (Phase 73k / D-119).
 */
export class MCPServersNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `mcp.servers.list` — the paginated, faceted MCP-server catalog. */
	list<R = unknown>(filter: Record<string, unknown> = {}): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.list', filter);
	}
	/** `mcp.servers.get` — one server's full descriptor. */
	get<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.get', { name });
	}
	/** `mcp.servers.resources` — a server's advertised resources. */
	resources<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.resources', { name });
	}
	/** `mcp.servers.prompts` — a server's advertised prompts. */
	prompts<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.prompts', { name });
	}
	/** `mcp.servers.health` — a server's handshake / reconnect health. */
	health<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.health', { name });
	}
	/** `mcp.servers.policy` — a server's read-only ToolPolicy projection. */
	policy<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.policy', { name });
	}
	/** `mcp.servers.bindings.list` — a server's OAuth bindings (no plaintext). */
	bindings<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.bindings.list', { name });
	}
	/** `mcp.servers.refresh_discovery` — re-run a server's discovery. */
	refreshDiscovery<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.refresh_discovery', { name });
	}
	/** `mcp.servers.probe` — a one-shot connectivity probe. */
	probe<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.probe', { name });
	}
	/** `mcp.servers.refresh_binding` — start an OAuth re-bind flow. */
	refreshBinding<R = unknown>(name: string, principalId: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.refresh_binding', {
			name,
			principal_id: principalId
		});
	}
	/** `mcp.servers.revoke_binding` — revoke an OAuth binding. */
	revokeBinding<R = unknown>(name: string, principalId: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.revoke_binding', {
			name,
			principal_id: principalId
		});
	}
	/** `mcp.servers.set_raw_html_trust` — toggle a server's raw-HTML trust. */
	setRawHTMLTrust<R = unknown>(name: string, trusted: boolean): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.set_raw_html_trust', {
			name,
			trusted
		});
	}
}

/** The `mcp` namespace — groups the MCP-server surface. */
export class MCPNamespace {
	/** The `mcp.servers.*` method surface. */
	readonly servers: MCPServersNamespace;
	constructor(t: Transport) {
		this.servers = new MCPServersNamespace(t);
	}
}

/* ------------------------------------------------------------------ */
/* ProtocolClient interface + HarborClient                             */
/* ------------------------------------------------------------------ */

/**
 * The injectable Protocol-client interface. A page depends on THIS interface,
 * never on the concrete `HarborClient` — tests and the Playwright harness
 * inject a deterministic in-page implementation (CONVENTIONS.md §6).
 */
export interface ProtocolClient {
	readonly tools: ToolsNamespace;
	readonly memory: MemoryNamespace;
	readonly flows: FlowsNamespace;
	readonly artifacts: ArtifactsNamespace;
	readonly mcp: MCPNamespace;
}

/**
 * The unified production Protocol client. ONE class, ONE `fetch` choke point
 * (the shared {@link Transport}), method namespaces hanging off it. Constructed
 * once from a resolved {@link RuntimeConnection}; immutable after construction.
 *
 * A page resolves its connection via `connection.ts`, constructs a
 * `HarborClient`, and calls `client.<namespace>.<method>(...)`. New page
 * surfaces add a namespace here — never a new top-level client.
 */
export class HarborClient implements ProtocolClient {
	readonly tools: ToolsNamespace;
	readonly memory: MemoryNamespace;
	readonly flows: FlowsNamespace;
	readonly artifacts: ArtifactsNamespace;
	readonly mcp: MCPNamespace;

	constructor(opts: HarborClientOptions) {
		const transport = new Transport(opts);
		this.tools = new ToolsNamespace(transport);
		this.memory = new MemoryNamespace(transport);
		this.flows = new FlowsNamespace(transport);
		this.artifacts = new ArtifactsNamespace(transport);
		this.mcp = new MCPNamespace(transport);
	}
}
