// Harbor Console — the unified typed Protocol client (D-121,
// CONVENTIONS.md §6).
//
// The foundation audit found five hand-authored Protocol clients —
// `ToolsClient`, `MemoryClient`, `FlowsClient`, the `mcpApi` object, and
// `HTTPProtocolClient` — each with its own error class, its own
// identity-passing convention, and its own `fetch` choke point. This module
// unifies them onto ONE `HarborClient` class with method namespaces hanging
// off it (`client.tools.list(...)`, `client.memory.health(...)`, …), one
// `ProtocolError`, and ONE transport choke point.
//
// `.svelte` components NEVER call `fetch` directly (CLAUDE.md §4.5 rule 5,
// §13). They construct a `HarborClient` (or receive an injected
// `ProtocolClient`) and call its typed namespace methods.
//
// # Routes
//
// The Runtime does not serve a single uniform endpoint shape. Each namespace
// method targets whatever route the Runtime actually mounts for it —
// `tools.*` at `POST /v1/tools/{verb}`, `memory.*` at `POST /v1/memory/{verb}`,
// `flows.*` at `POST /v1/flows/...`, `artifacts.*` and `mcp.servers.*` at the
// control surface `POST /v1/control/{method}` (CONVENTIONS.md §6).
//
// # Deviation note (D-093)
//
// D-093 pins `src/lib/protocol.ts` as generated by `cmd/harbor-gen-protocol-ts`.
// That generator binary has not yet landed (Phase 72h committed `protocol.ts`
// as a hand-shaped stub; the five legacy per-page clients are likewise hand-
// authored). This module is the hand-authored unified client; when the
// generator lands, the wire types fold into the generated file and this client
// re-exports them — a mechanical migration.

import { ProtocolError, type ProtocolErrorBody } from './errors.js';
import type { RuntimeConnection } from '../connection.js';
import type {
	MemoryGetResponse,
	MemoryListRequest,
	MemoryListResponse,
	MemoryHealthResponse
} from './memory-types.js';
import type {
	EventAggregateRequest,
	EventAggregateResponse,
	EventsListRequest,
	EventsListResponse
} from './events.js';
import type { RuntimeCounters, RuntimeHealth, MetricsSnapshot } from './posture.js';
import type { PauseListRequest, PauseListResponse } from './pause.js';
import type { SearchRequest, SearchResponse } from './search.js';
import type { StateHistoryRequest, StateHistoryResponse } from './state.js';
import type { RunOverrides } from './runs.js';
import type {
	GovernanceTenantOverrides,
	GovernanceGetTenantOverridesResponse,
	GovernanceSetTenantOverridesResponse,
	GovernanceSetPostureRequest,
	GovernanceSetPostureResponse,
} from './governance.js';
import type {
	AgentConfigPayload,
	AgentConfigToolExposure,
	AgentConfigPromptLayers,
	AgentConfigGetResponse,
	AgentConfigSetRevisionResponse,
	AgentConfigListRevisionsResponse,
	AgentConfigDiffResponse,
	AgentConfigRollbackResponse,
	AgentConfigSetToolExposureResponse,
	AgentConfigSetPromptLayersResponse,
	AgentConfigExtraSystemBlocks,
	AgentConfigSetExtraSystemBlocksResponse,
	AgentConfigLLMParams,
	AgentConfigSetLLMParamsResponse,
	AgentConfigMCPConnectionDescriptor,
	AgentConfigAddMCPConnectionResponse,
	AgentConfigRemoveMCPConnectionResponse,
	AgentConfigSetMCPDiscoveryOriginsResponse,
	AgentConfigOAuthProviderDescriptor,
	AgentConfigSetOAuthProviderResponse,
	AgentConfigRegisterOAuthMCPCapabilityResponse,
	AgentConfigRemoveOAuthMCPCapabilityResponse,
	SignedOAuthMCPConnectionDescriptor,
	AgentConfigRemoveOAuthProviderResponse,
	AgentConfigLLMProviderDescriptor,
	AgentConfigSetLLMProviderResponse,
	AgentConfigSkillInput,
	AgentConfigSkillsListResponse,
	AgentConfigSkillsUpsertResponse,
	AgentConfigSkillsDeleteResponse,
	AgentConfigSessionSetUserPromptResponse,
	AgentConfigSessionSetSourceDisablesResponse,
	AgentConfigSessionSkillsListResponse,
	AgentConfigSessionSkillsUpsertResponse,
	AgentConfigSessionSkillsDeleteResponse,
	AgentConfigUserPayload,
	AgentConfigUserGetResponse,
	AgentConfigUserSetRevisionResponse,
	AgentConfigUserListRevisionsResponse,
	AgentConfigUserDiffResponse,
	AgentConfigUserRollbackResponse,
	AgentConfigUserSkillsListResponse,
	AgentConfigUserSkillsUpsertResponse,
	AgentConfigUserSkillsDeleteResponse,
} from './agentconfig.js';

/* ------------------------------------------------------------------ */
/* Transport                                                           */
/* ------------------------------------------------------------------ */

/** The HTTP verb a route is mounted under. All Protocol routes are POST. */
type Method = 'POST';

/**
 * The `start` (and idempotent-restart) reply. Mirrors the Go
 * `types.StartResponse` — a named type so the lockstep gate guards its
 * fields rather than leaving the shape as an inline generic default.
 */
export interface StartResponse {
	task_id: string;
	reused: boolean;
	protocol_version: string;
}

/** Options the `HarborClient` is constructed with. */
export interface HarborClientOptions {
	/** The resolved Runtime connection (base URL + token + identity triple). */
	connection: RuntimeConnection;
	/**
	 * Injectable `fetch` implementation. Defaults to `globalThis.fetch`; tests
	 * and the Playwright harness inject a deterministic stub so the client is
	 * exercised without a live Runtime.
	 */
	fetchImpl?: typeof fetch;
}

/**
 * Transport is the single `fetch` choke point shared by every namespace. It
 * serialises the request, folds the identity triple into the body (the
 * Runtime's defence-in-depth identity check), attaches the bearer token + the
 * `X-Harbor-*` identity headers, and raises a typed {@link ProtocolError} on
 * any non-2xx response — never a silently-swallowed empty result (CLAUDE.md
 * §13 "no silent degradation").
 */
export class Transport {
	readonly #baseURL: string;
	readonly #token: string;
	readonly #identity: RuntimeConnection['identity'];
	readonly #fetch: typeof fetch;

	constructor(opts: HarborClientOptions) {
		this.#baseURL = opts.connection.baseURL.replace(/\/$/, '');
		this.#token = opts.connection.token;
		this.#identity = opts.connection.identity;
		this.#fetch = opts.fetchImpl ?? globalThis.fetch.bind(globalThis);
	}

	/** The identity triple this transport is scoped to (read-only). */
	get identity(): RuntimeConnection['identity'] {
		return this.#identity;
	}

	/**
	 * The Runtime base URL (no trailing slash). Exposed so the
	 * `events.subscribe` SSE consumer can construct an `EventSource`
	 * target — the SSE stream is a long-lived `GET` that the request /
	 * response `Transport.request` choke point does not model. The SSE
	 * consumer is still a member of the `events` namespace, not a
	 * hand-rolled per-page client (CONVENTIONS.md §6).
	 */
	get baseURL(): string {
		return this.#baseURL;
	}

	/** The bearer JWT this transport carries (read-only). */
	get token(): string {
		return this.#token;
	}

	/**
	 * Issue one typed request against a Runtime route. `path` is the route the
	 * Runtime mounts (e.g. `/v1/tools/list`, `/v1/control/artifacts.list`).
	 * The identity triple is folded into the body; `body` is merged over it so
	 * a caller-supplied `identity` field wins for cross-tenant admin calls.
	 *
	 * `opts.omitBodyIdentity` suppresses the body identity fold for the few
	 * handlers that decode an identity-LESS request type with
	 * `DisallowUnknownFields` (e.g. `governance.set_posture`) and would reject a
	 * folded `identity` key with `unknown field "identity"` (HTTP 400). The
	 * identity still rides the `X-Harbor-*` headers, so the handler's
	 * server-side `resolveIdentity` is unaffected — only the body fold is
	 * dropped.
	 */
	async request<T>(
		path: string,
		body: Record<string, unknown> = {},
		method: Method = 'POST',
		opts: { omitBodyIdentity?: boolean } = {}
	): Promise<T> {
		// D-171 — session is per-request (header-supplied) and OPTIONAL on a
		// connection. The runtime's posture handlers require a body identity
		// to FULLY match the resolved identity (incl. session) OR be empty;
		// a partial body identity (or an empty `session: ''`) is rejected
		// against the token's default session. So fold the FULL identity
		// only when a session is set; otherwise send an empty body identity
		// `{}` and rely on the X-Harbor-* headers (the runtime backfills it,
		// defaulting the session to the token claim). The contract's
		// "simplest correct client sends identity: {}" path.
		const idObj: Record<string, string> = this.#identity.session !== ''
			? {
					tenant: this.#identity.tenant,
					user: this.#identity.user,
					session: this.#identity.session
				}
			: {};
		const payload = opts.omitBodyIdentity
			? JSON.stringify({ ...body })
			: JSON.stringify({ identity: idObj, ...body });
		const resp = await this.#fetch(`${this.#baseURL}${path}`, {
			method,
			headers: {
				'Content-Type': 'application/json',
				Authorization: `Bearer ${this.#token}`,
				'X-Harbor-Tenant': this.#identity.tenant,
				'X-Harbor-User': this.#identity.user,
				'X-Harbor-Session': this.#identity.session
			},
			body: payload
		});
		const text = await resp.text();
		if (!resp.ok) {
			let code = 'runtime_error';
			let message = text || resp.statusText || `HTTP ${resp.status}`;
			try {
				const err = JSON.parse(text) as Partial<ProtocolErrorBody>;
				if (err.code) code = err.code;
				if (err.message) message = err.message;
			} catch {
				// Non-JSON error body — keep the raw text as the message; never
				// swallow the failure (CLAUDE.md §5 fail-loudly).
			}
			throw new ProtocolError(code, message, resp.status);
		}
		return (text.length > 0 ? JSON.parse(text) : {}) as T;
	}
}

/* ------------------------------------------------------------------ */
/* Namespace surfaces                                                  */
/* ------------------------------------------------------------------ */

/**
 * The `tools.*` namespace — ported from the legacy `ToolsClient`. The Runtime
 * mounts these at `POST /v1/tools/{verb}` (Phase 73f / D-116).
 */
export class ToolsNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `tools.list` — paginated, faceted catalog projection. */
	list<R = unknown>(filter: Record<string, unknown> = {}, page = 1, pageSize = 50): Promise<R> {
		return this.#t.request<R>('/v1/tools/list', { filter, page, page_size: pageSize });
	}
	/** `tools.get` — single catalog-row projection. */
	get<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/tools/get', { id });
	}
	/** `tools.describe` — full manifest projection. `agentId`, when set,
	 * projects the EFFECTIVE loading_mode through that agent's active
	 * tool-exposure config (D-281); omitted reports the boot-effective
	 * mode. */
	describe<R = unknown>(id: string, agentId?: string): Promise<R> {
		return this.#t.request<R>('/v1/tools/describe', agentId ? { id, agent_id: agentId } : { id });
	}
	/** `tools.metrics` — per-tool error-rate gauges + status pill. */
	metrics<R = unknown>(id: string, window = '1h'): Promise<R> {
		return this.#t.request<R>('/v1/tools/metrics', { id, window });
	}
	/** `tools.content_stats` — per-tool result-size histogram. */
	contentStats<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/tools/content_stats', { id });
	}
	/** `tools.set_approval_policy` — ADMIN method (D-079 scope-gated). */
	setApprovalPolicy<R = unknown>(id: string, policy: string): Promise<R> {
		return this.#t.request<R>('/v1/tools/set_approval_policy', { id, policy });
	}
	/** `tools.revoke_oauth` — ADMIN method (D-079 scope-gated). */
	revokeOAuth<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/tools/revoke_oauth', { id });
	}
}

/**
 * The `memory.*` namespace — ported from the legacy `MemoryClient`. The Runtime
 * mounts these at `POST /v1/memory/{verb}` (Phase 73j / D-118).
 */
export class MemoryNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `memory.list` — paginated, identity-scope-filtered memory records. */
	list(req: MemoryListRequest = {}): Promise<MemoryListResponse> {
		return this.#t.request<MemoryListResponse>(
			'/v1/memory/list',
			req as unknown as Record<string, unknown>
		);
	}
	/** `memory.get` — full detail of one memory record. */
	get(key: string): Promise<MemoryGetResponse> {
		return this.#t.request<MemoryGetResponse>('/v1/memory/get', { key });
	}
	/** `memory.health` — aggregate memory-health counters. */
	health(): Promise<MemoryHealthResponse> {
		return this.#t.request<MemoryHealthResponse>('/v1/memory/health', {});
	}
	/** `memory.strategy_trace` — the live strategy-compaction projection
	 * (Phase 108n / D-186). Read scope (no admin claim). */
	strategyTrace<R = unknown>(): Promise<R> {
		return this.#t.request<R>('/v1/memory/strategy_trace', {});
	}
	/** `memory.put` — admin-gated "add a memory turn" mutation (D-079). */
	put<R = unknown>(userMessage: string, assistantResponse: string): Promise<R> {
		return this.#t.request<R>('/v1/memory/put', {
			turn: { user_text: userMessage, assistant_text: assistantResponse }
		});
	}
	/** `memory.delete` — admin-gated "evict a memory turn" mutation (D-079). */
	delete<R = unknown>(key: string): Promise<R> {
		return this.#t.request<R>('/v1/memory/delete', { key });
	}
}

/**
 * The `flows.*` namespace — ported from the legacy `FlowsClient`. The Runtime
 * mounts these at `POST /v1/flows/...` (Phase 73i / D-117).
 */
export class FlowsNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `flows.list` — paginated registered-flow catalog with aggregates. */
	list<R = unknown>(req: Record<string, unknown> = {}): Promise<R> {
		return this.#t.request<R>('/v1/flows/list', req);
	}
	/** `flows.describe` — a flow's full engine-graph description. */
	describe<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/flows/describe', req);
	}
	/** `flows.runs.list` — a flow's paginated run history. */
	runsList<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/flows/runs/list', req);
	}
	/** `flows.runs.describe` — a single run's per-node timeline. */
	runsDescribe<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/flows/runs/describe', req);
	}
	/** `flows.run` — invoke a one-shot run (ADMIN method, D-079 scope-gated). */
	run<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/flows/run', req);
	}
	/** `flows.metrics` — a flow's time-bucketed sparkline aggregates. */
	metrics<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/flows/metrics', req);
	}
}

/**
 * The `artifacts.*` namespace — ported from the legacy `HTTPProtocolClient`.
 * The Runtime mounts these on the control surface at
 * `POST /v1/control/artifacts.{verb}` (Phase 73l / D-120).
 */
export class ArtifactsNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/**
	 * `artifacts.list` — the identity-scoped, metadata-only artifact catalog.
	 *
	 * Every method on this namespace passes `omitBodyIdentity`. The five
	 * artifacts request types scope by `scope` and declare NO `identity`
	 * field, so the transport's default identity fold would add a member the
	 * wire type does not define — refused `unknown field "identity"` (400)
	 * now that the control transport decodes strictly (D-374). The identity
	 * still rides the `X-Harbor-*` headers, so `resolveIdentity` is
	 * unaffected. Enforced by the lockstep scan in
	 * `web/console/scripts/check-protocol-ts-lockstep.mjs`.
	 */
	list<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/control/artifacts.list', req, 'POST', {
			omitBodyIdentity: true,
		});
	}
	/** `artifacts.put` — the Console / Playground file-upload pipeline. */
	put<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/control/artifacts.put', req, 'POST', {
			omitBodyIdentity: true,
		});
	}
	/**
	 * `artifacts.get` — the driver-independent byte read. Served by every
	 * registered driver because it resolves through the mandatory store
	 * `Get`; `getRef` below is the transport optimisation for stores that
	 * can hand bytes off their own edge, not a second implementation of
	 * this. The response is truthful about its own bound
	 * (`total_size_bytes` / `returned_bytes` / `truncated`).
	 */
	get<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/control/artifacts.get', req, 'POST', {
			omitBodyIdentity: true,
		});
	}
	/** `artifacts.get_ref` — the read-side presigned-URL resolver (D-022/D-026). */
	getRef<R = unknown>(req: Record<string, unknown>): Promise<R> {
		return this.#t.request<R>('/v1/control/artifacts.get_ref', req, 'POST', {
			omitBodyIdentity: true,
		});
	}
	/** `artifacts.delete` — admin-gated, audited artifact eviction (Phase 108o / D-187). */
	delete<R = unknown>(req: { scope: Record<string, unknown>; id: string }): Promise<R> {
		return this.#t.request<R>(
			'/v1/control/artifacts.delete',
			req as unknown as Record<string, unknown>,
			'POST',
			{ omitBodyIdentity: true }
		);
	}
}

/**
 * The `mcp.servers.*` surface under the `mcp` namespace — ported from the
 * legacy `mcpApi` object. The Runtime mounts these on the control surface at
 * `POST /v1/control/mcp.servers.{verb}` (Phase 73k / D-119).
 */
export class MCPServersNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `mcp.servers.list` — the paginated, faceted MCP-server catalog. */
	list<R = unknown>(filter: Record<string, unknown> = {}): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.list', filter);
	}
	/** `mcp.servers.get` — one server's full descriptor. */
	get<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.get', { name });
	}
	/** `mcp.servers.resources` — a server's advertised resources. */
	resources<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.resources', { name });
	}
	/** `mcp.servers.prompts` — a server's advertised prompts. */
	prompts<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.prompts', { name });
	}
	/** `mcp.servers.health` — a server's handshake / reconnect health. */
	health<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.health', { name });
	}
	/** `mcp.servers.policy` — a server's read-only ToolPolicy projection. */
	policy<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.policy', { name });
	}
	/** `mcp.servers.bindings.list` — a server's OAuth bindings (no plaintext). */
	bindings<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.bindings.list', { name });
	}
	/** `mcp.servers.refresh_discovery` — re-run a server's discovery. */
	refreshDiscovery<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.refresh_discovery', { name });
	}
	/** `mcp.servers.probe` — a one-shot connectivity probe. */
	probe<R = unknown>(name: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.probe', { name });
	}
	/** `mcp.servers.refresh_binding` — start an OAuth re-bind flow. */
	refreshBinding<R = unknown>(name: string, principalId: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.refresh_binding', {
			name,
			principal_id: principalId
		});
	}
	/** `mcp.servers.revoke_binding` — revoke an OAuth binding. */
	revokeBinding<R = unknown>(name: string, principalId: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.revoke_binding', {
			name,
			principal_id: principalId
		});
	}
	/** `mcp.servers.set_raw_html_trust` — toggle a server's raw-HTML trust. */
	setRawHTMLTrust<R = unknown>(name: string, trusted: boolean): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.set_raw_html_trust', {
			name,
			trusted
		});
	}

	/**
	 * `mcp.servers.read_resource` — fetch a `ui://` resource's bytes scoped
	 * to the request identity triple, D-026 heavy-content aware (the MCP Apps
	 * host's `onreadresource` handler routes here, never to a direct MCP
	 * transport — D-173). The Runtime mounts it on the control surface at
	 * `POST /v1/control/mcp.servers.read_resource`.
	 */
	readResource<R = unknown>(serverID: string, resourceURI: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.servers.read_resource', {
			server_id: serverID,
			resource_uri: resourceURI
		});
	}
}

/**
 * The `mcp.apps.*` surface — the MCP Apps host's app-tool-call proxy. The
 * single method `call_tool` routes an app-initiated `tools/call` back through
 * the SAME identity + approval-gate + tool-side-OAuth path a planner-initiated
 * call uses (D-173): the Console opens no direct MCP transport, so an app call
 * to a gated tool parks on the unified pause primitive exactly as a planner
 * call does. The Runtime mounts it at `POST /v1/control/mcp.apps.call_tool`.
 */
export class MCPAppsNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/**
	 * `mcp.apps.call_tool` — proxy an app-initiated tool invocation. `tool` is
	 * the Harbor catalog tool name (`<source>_<tool>`); `args` is the raw JSON
	 * argument object the tool's schema validates on the wire.
	 */
	callTool<R = unknown>(tool: string, args?: unknown): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.apps.call_tool', {
			tool,
			arguments: args
		});
	}
	/**
	 * `mcp.apps.tool_context` — fetch the captured tool context (input + lowered
	 * result) that produced a rendered `ui://` MCP App, so the host can push it
	 * across the AppBridge after the app initializes (the Data Delivery
	 * lifecycle stage). `serverID` + `toolCallID` are the correlation pair the
	 * `mcp.app_available` event carries; the read is identity-scoped, so an
	 * unknown or cross-identity pair fails with `not_found`.
	 */
	toolContext<R = unknown>(serverID: string, toolCallID: string): Promise<R> {
		return this.#t.request<R>('/v1/control/mcp.apps.tool_context', {
			server_id: serverID,
			tool_call_id: toolCallID
		});
	}
}

/**
 * The `events.*` namespace — the Console Events page surface (Phase 73g
 * / D-125). Phase 73g ships NO new Protocol method; this namespace wraps
 * the already-shipped `events.aggregate` (`POST /v1/events/aggregate` —
 * Phase 72a) and exposes the `events.subscribe` SSE endpoint
 * (`GET /v1/events` — Phase 72) as a typed `EventSource`-target builder.
 *
 * # Why the SSE stream is not a `Transport.request`
 *
 * `events.subscribe` is a long-lived server-sent-event stream, not a
 * request / response round-trip — `Transport.request` (the single
 * `fetch` choke point) does not model it. The namespace exposes
 * {@link subscribeURL}; the page-side `EventsSubscription` wrapper
 * opens an `EventSource` against it. Bearer auth rides as a query
 * param because `EventSource` cannot set an `Authorization` header —
 * the runtime accepts the bearer token on either surface (Phase 60).
 * No `.svelte` file constructs the URL or the `EventSource` by hand;
 * both go through this namespace + the `EventsSubscription` wrapper.
 */
export class EventsNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}

	/** `events.aggregate` — the time-bucketed per-type count series. */
	aggregate(req: EventAggregateRequest): Promise<EventAggregateResponse> {
		return this.#t.request<EventAggregateResponse>(
			'/v1/events/aggregate',
			req as unknown as Record<string, unknown>
		);
	}

	/**
	 * `events.list` — the durable, time-ranged, cross-session raw-event
	 * read (D-294). Returns a bounded, tail-first page of the flat
	 * `StateEvent` rows (same shape as `state.history` / the SSE
	 * stream) plus a scroll-up `next_cursor` and the honest `truncated`
	 * retention-gap flag. Pass the prior response's `next_cursor` back as
	 * `cursor` to page one window older; a cross-tenant filter is gated on
	 * the verified `admin` / `console:fleet` scope (D-079).
	 */
	list(req: EventsListRequest): Promise<EventsListResponse> {
		return this.#t.request<EventsListResponse>(
			'/v1/events/list',
			req as unknown as Record<string, unknown>
		);
	}

	/**
	 * The `events.subscribe` SSE endpoint URL the page-side
	 * `EventsSubscription` opens an `EventSource` against. The optional
	 * `eventTypes` narrow to a repeatable `type` query param; `admin`
	 * requests cross-tenant fan-in (the runtime gates it on
	 * `auth.ScopeAdmin` / `auth.ScopeConsoleFleet`, D-079). The bearer
	 * token rides as `access_token` — `EventSource` cannot carry an
	 * `Authorization` header.
	 */
	subscribeURL(opts: { eventTypes?: string[]; admin?: boolean; session?: string } = {}): string {
		const url = new URL(`${this.#t.baseURL}/v1/events`);
		for (const t of opts.eventTypes ?? []) {
			url.searchParams.append('type', t);
		}
		if (opts.admin) {
			url.searchParams.set('admin', '1');
		}
		url.searchParams.set('access_token', this.#t.token);
		// D-171 — EventSource cannot set the `X-Harbor-Session` header, so
		// the conversation session rides as a `?session=` query param the
		// SSE shim promotes to the header (header-precedence). `opts.session`
		// (the Events page's Session facet) overrides the client's default
		// identity.session, letting the operator pivot the stream to any
		// session in scope without rebuilding the client; it falls back to
		// the client's own session, then the token default when both empty.
		const sess =
			opts.session !== undefined && opts.session !== '' ? opts.session : this.#t.identity.session;
		if (sess !== '') {
			url.searchParams.set('session', sess);
		}
		return url.toString();
	}

	/** The identity triple the events subscription is scoped to. */
	get identity(): RuntimeConnection['identity'] {
		return this.#t.identity;
	}
}

/**
 * The `tasks.*` namespace — Phase 73d / D-123. The Runtime mounts the
 * two Tasks-page read methods at `POST /v1/tasks/{verb}`. The Console
 * Tasks page consumes the EXISTING Phase 54 control verbs for mutation
 * through {@link ControlNamespace} — there is NO `tasks.*` mutating
 * method (CLAUDE.md §13 "no parallel implementations").
 */
export class TasksNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `tasks.list` — paginated, faceted task-row projection + aggregates. */
	list<R = unknown>(req: Record<string, unknown> = {}): Promise<R> {
		return this.#t.request<R>('/v1/tasks/list', req);
	}
	/** `tasks.get` — enriched single-task detail. */
	get<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/tasks/get', { id });
	}
}

/**
 * The `control.*` namespace — the shipped Phase 54 task-control surface
 * (`cancel` / `pause` / `resume` / `prioritize` / `approve` / `reject`
 * + `redirect` / `inject_context` / `user_message`). The Runtime mounts
 * these on the control surface at `POST /v1/control/{verb}`.
 *
 * The Console Tasks-page bulk-action toolbar + per-task action bar
 * consume THESE shipped verbs — no new control method is minted
 * (CLAUDE.md §13). A verb targets a specific run by its task id carried
 * in `identity.run`; the optional `payload` carries method-specific
 * arguments (the `priority` for `prioritize`).
 */
export class ControlNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/**
	 * Dispatch a Phase 54 control verb against the run identified by
	 * `taskID` (carried in `identity.run`). `payload` carries the
	 * method-specific arguments; `scope` is the caller's steering scope
	 * claim. Returns the {@link ProtocolError}-on-failure ControlResponse.
	 */
	dispatch<R = unknown>(
		verb: string,
		taskID: string,
		payload?: Record<string, unknown>,
		scope = 'owner_user'
	): Promise<R> {
		const body: Record<string, unknown> = {
			identity: { run: taskID, scope }
		};
		if (payload !== undefined) {
			body.payload = payload;
		}
		return this.#t.request<R>(`/v1/control/${verb}`, body);
	}
	/**
	 * `start` — spawn a new foreground task in the caller's session.
	 *
	 * Round-6 F7 — `start` is NOT a steering verb. The wire shape is
	 * FLAT (mirrors `internal/protocol/types/control.go::StartRequest`):
	 * `{identity:triple, query, description, priority, idempotency_key}`,
	 * with no `task:{...}` wrapper. The previous Playground sendMessage
	 * went through `dispatch('user_message', sessionID, ...)` which (a)
	 * treated sessionID as a taskID and (b) used the steering-verb body
	 * shape — the runtime rejected it with "no live run for the
	 * requested run id" and the chat panel could never send its first
	 * message.
	 *
	 * The runtime folds the connection-scoped identity (tenant/user/
	 * session) into `identity` automatically via {@link Transport.request}
	 * — we do NOT override identity here. Kind is hardcoded to
	 * `foreground` at the dispatch layer (background runs go through
	 * `tasks.spawn_background`, not `start`).
	 */
	start<R = StartResponse>(
		query: string,
		opts: {
			description?: string;
			priority?: number;
			idempotencyKey?: string;
			inputArtifactIDs?: string[];
			/**
			 * Phase 84b (D-189) — optional per-attachment disposition
			 * hints, keyed by an `inputArtifactIDs` entry. Values: `ref` /
			 * `inline` / `provider_native` / `tool:<name>`. The hint is
			 * the top precedence layer (hint > the agent's
			 * `multimodal.disposition` config map > the runtime default);
			 * an omitted key defers to the lower layers.
			 */
			inputArtifactDispositions?: Record<string, string>;
			/**
			 * D-276 — opt the task-shaped run into per-task structured
			 * output. A JSON-Schema document (object or raw JSON string)
			 * the completed task's answer is validated against; the
			 * validated result lands as `answer_payload` on the task
			 * envelope (readable via `tasks.get`'s `result_inline`). An
			 * empty / non-compiling / over-cap (64 KiB) schema is rejected
			 * at the Protocol edge with CodeInvalidRequest before any task
			 * spawns. A schema-constrained task suppresses assistant token
			 * deltas — the answer arrives once, on completion. Omitted (the
			 * default) keeps the wire shape schemaless.
			 */
			outputSchema?: unknown;
			/**
			 * Name which agent's CONFIGURATION the run executes under.
			 * Omitted binds the runtime's configured default exactly as
			 * before. A named agent is accepted when it is the runtime's
			 * configured default id, or when a config revision exists
			 * for the caller's tenant under that id; anything else is
			 * refused at the Protocol edge with `invalid_request` before
			 * a task exists — never silently substituted with the
			 * default. Selects configuration only: the run's southbound
			 * tool provenance stays the runtime's boot-derived value.
			 */
			agentId?: string;
			/**
			 * D-364 — caller-supplied content admitted into the run's
			 * `<read_only_external_memory>` tier under the fixed
			 * runtime-owned `caller_supplied` map key. It COMPOSES with
			 * the runtime's own retrieval rather than replacing it, and
			 * it can never reach the trusted system-prompt spine or the
			 * conversation-memory tier.
			 *
			 * Prefer this over `system_prompt_override` for any retrieved
			 * or recalled content: the override REPLACES the whole
			 * base+user prompt spine and seats its content in the trusted
			 * position with no untrusted framing.
			 *
			 * Any JSON value. An explicit `null` is refused rather than
			 * treated as absent, and a document over 32 KiB is refused
			 * with `invalid_request` at the Protocol edge before a task
			 * exists. Omitted (the default) keeps the wire shape and run
			 * behaviour byte-identical.
			 *
			 * That 32 KiB is a RESOURCE BOUND and wire-size guard, not a
			 * security boundary — the same caller can send more through
			 * `query` (uncapped below the transport envelope) or through
			 * `agent_config.session.set_user_prompt` (claim-free, 1 MiB
			 * body, landing inside the system prompt). What contains this
			 * payload is the tier it lands in, not its size.
			 *
			 * NEGOTIATE FIRST: `await client.capabilities()` then branch
			 * on `caps.has('caller_memory')`. A runtime predating the
			 * field discards the member and answers 200, so treat the
			 * capability's absence as unsupported rather than discovering
			 * the loss after the run.
			 *
			 * Harbor does not sanitise the payload — the tier's
			 * anti-prompt-injection framing IS the mitigation, and
			 * redaction is the caller's job.
			 */
			callerMemory?: unknown;
		} = {}
	): Promise<R> {
		const body: Record<string, unknown> = { query };
		if (opts.description !== undefined) {
			body.description = opts.description;
		}
		if (opts.priority !== undefined) {
			body.priority = opts.priority;
		}
		if (opts.idempotencyKey !== undefined) {
			body.idempotency_key = opts.idempotencyKey;
		}
		// Round-7 F11 / D-166 — multimodal artifact inputs. The runtime
		// resolves each id to a `planner.InputArtifactView` and routes
		// per MIME on the first planner turn: image/* bytes inline as
		// `ImagePart.DataURL`; pdf/audio stay as typed refs; everything
		// else emits an `ArtifactStub` text block the LLM routes via
		// the tool catalog. Empty / undefined keeps the wire shape
		// text-only (the omitempty tag elides the field server-side).
		if (opts.inputArtifactIDs !== undefined && opts.inputArtifactIDs.length > 0) {
			body.input_artifact_ids = opts.inputArtifactIDs;
		}
		if (
			opts.inputArtifactDispositions !== undefined &&
			Object.keys(opts.inputArtifactDispositions).length > 0
		) {
			body.input_artifact_dispositions = opts.inputArtifactDispositions;
		}
		// D-276 — per-task structured output. The runtime validates the
		// task's terminal answer against this JSON Schema and surfaces the
		// validated `answer_payload`. Elided when unset (server-side
		// omitempty keeps a schemaless task byte-identical).
		if (opts.outputSchema !== undefined) {
			body.output_schema = opts.outputSchema;
		}
		// Caller-named agent selection. Elided when unset / empty, so a
		// run that names no agent is byte-identical on the wire to one
		// sent before the field existed.
		if (opts.agentId !== undefined && opts.agentId !== '') {
			body.agent_id = opts.agentId;
		}
		// D-364 — caller-supplied external-memory block. Elided when
		// unset, so a run that supplies none is byte-identical on the wire
		// to one sent before the field existed. `null` is deliberately NOT
		// elided: the runtime refuses it loudly rather than treating it as
		// absent, and swallowing it here would hide that from the caller.
		if (opts.callerMemory !== undefined) {
			body.caller_memory = opts.callerMemory;
		}
		return this.#t.request<R>('/v1/control/start', body);
	}
	/** `cancel` — cancel the task's run. */
	cancel<R = unknown>(taskID: string): Promise<R> {
		return this.dispatch<R>('cancel', taskID);
	}
	/** `pause` — pause the task's run. */
	pause<R = unknown>(taskID: string): Promise<R> {
		return this.dispatch<R>('pause', taskID);
	}
	/** `resume` — resume the task's run. */
	resume<R = unknown>(taskID: string): Promise<R> {
		return this.dispatch<R>('resume', taskID);
	}
	/** `prioritize` — set the task's numeric priority. */
	prioritize<R = unknown>(taskID: string, priority: number): Promise<R> {
		return this.dispatch<R>('prioritize', taskID, { priority });
	}
	/** `approve` — approve a pending HITL gate on the task's run. */
	approve<R = unknown>(taskID: string): Promise<R> {
		return this.dispatch<R>('approve', taskID);
	}
	/** `reject` — reject a pending HITL gate on the task's run. */
	reject<R = unknown>(taskID: string): Promise<R> {
		return this.dispatch<R>('reject', taskID);
	}
}

/**
 * The `agents.*` namespace (Phase 73e / D-124 + Phase 108l / D-184). The
 * Runtime mounts these at `POST /v1/agents/{verb}` (the same one-shot
 * request/response shape as `tools.*`). Eight methods are READ-ONLY
 * projections of the Agent Registry; the five fleet-control verbs (pause
 * / drain / restart / force_stop / deregister) MUTATE registry state and
 * require the admin control claim (D-066) — Phase 108l (D-184) lands them
 * as real Protocol methods, superseding the D-132/F4 deferral.
 */
export class AgentsNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `agents.list` — paginated, faceted agent catalog projection. */
	list<R = unknown>(req: Record<string, unknown> = {}): Promise<R> {
		return this.#t.request<R>('/v1/agents/list', req);
	}
	/** `agents.get` — one agent's full registration-identity projection. */
	get<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/agents/get', { id });
	}
	/** `agents.tools` — the agent's tool bindings + per-binding OAuth. */
	tools<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/agents/tools', { id });
	}
	/** `agents.memory` — the agent's memory strategy + TTL + scope. */
	memory<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/agents/memory', { id });
	}
	/** `agents.governance` — per-identity-tier ceilings + spend + limits. */
	governance<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/agents/governance', { id });
	}
	/** `agents.skills` — the agent's attached skills. */
	skills<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/agents/skills', { id });
	}
	/** `agents.permissions` — the agent's permission model (V1: implicit). */
	permissions<R = unknown>(id: string): Promise<R> {
		return this.#t.request<R>('/v1/agents/permissions', { id });
	}
	/** `agents.metrics` — the registry-wide rollup the page hero shows. */
	metrics<R = unknown>(): Promise<R> {
		return this.#t.request<R>('/v1/agents/metrics', {});
	}
	/** `agents.pause` — fleet control (admin); emits agent.paused. */
	pause<R = unknown>(id: string, reason = ''): Promise<R> {
		return this.#t.request<R>('/v1/agents/pause', { id, reason });
	}
	/** `agents.drain` — fleet control (admin); emits agent.drained. */
	drain<R = unknown>(id: string, reason = ''): Promise<R> {
		return this.#t.request<R>('/v1/agents/drain', { id, reason });
	}
	/** `agents.restart` — fleet control (admin); emits agent.restart_requested. */
	restart<R = unknown>(id: string, reason = ''): Promise<R> {
		return this.#t.request<R>('/v1/agents/restart', { id, reason });
	}
	/** `agents.force_stop` — fleet control (admin); emits agent.force_stopped. */
	forceStop<R = unknown>(id: string, reason = ''): Promise<R> {
		return this.#t.request<R>('/v1/agents/force_stop', { id, reason });
	}
	/** `agents.deregister` — fleet control (admin); emits agent.deregistered. */
	deregister<R = unknown>(id: string, reason = ''): Promise<R> {
		return this.#t.request<R>('/v1/agents/deregister', { id, reason });
	}
}

/**
 * The `sessions.*` namespace (Phase 73c / D-122; `set_title` — Phase
 * 157 / D-288). The Runtime mounts these at `POST /v1/sessions/{verb}` —
 * the Sessions handler shares the same identity + cross-tenant
 * scope-claim gating the tools / flows handlers use. `list` / `inspect`
 * are read-only; `set_title` mutates (the write scope is the owning
 * `(tenant, user)`, not own-session-only — `session_id` may name a
 * sibling session of the caller's own `(tenant, user)`).
 */
export class SessionsNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `sessions.list` — the paginated, filtered session catalog. */
	list<R = unknown>(req: Record<string, unknown> = {}): Promise<R> {
		return this.#t.request<R>('/v1/sessions/list', req);
	}
	/** `sessions.inspect` — a single session's full snapshot. */
	inspect<R = unknown>(sessionID: string): Promise<R> {
		return this.#t.request<R>('/v1/sessions/inspect', { session_id: sessionID });
	}
	/**
	 * `sessions.set_title` — sets (non-empty `title`) or clears (empty
	 * `title`) a session's human-readable name. ALWAYS writes `manual`
	 * provenance; an over-bound / malformed title is rejected 400.
	 */
	setTitle<R = unknown>(sessionID: string, title: string): Promise<R> {
		return this.#t.request<R>('/v1/sessions/set_title', { session_id: sessionID, title });
	}
}

/**
 * The `topology.*` namespace — Phase 74 / D-114, consumed by the
 * Console Live Runtime page (Phase 73b / D-126). The Runtime mounts
 * `topology.snapshot` on the control surface at
 * `POST /v1/control/topology.snapshot`. It is a pure read — the page's
 * topology canvas renders the returned `TopologyProjection`.
 */
export class TopologyNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `topology.snapshot` — the Runtime engine's static node graph + live per-edge queue depth. */
	snapshot<R = unknown>(): Promise<R> {
		return this.#t.request<R>('/v1/control/topology.snapshot', {});
	}
}

/**
 * The `runs.*` namespace — Phase 73n / D-130, consumed by the Console
 * Playground page. The Runtime mounts `runs.set_overrides` at
 * `POST /v1/runs/set_overrides`. It records the reasoning-effort /
 * temperature / max-tokens / system-prompt override applied to the NEXT
 * message in the operator's session.
 */
export class RunsNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/**
	 * `runs.set_overrides` — record the next-message override. `overrides`
	 * carries `session_id` plus the optional tuning fields
	 * (`reasoning_effort` / `temperature` / `max_tokens` /
	 * `system_prompt_override` / `extra_instructions` / `model`). The
	 * override is session-scoped and one-shot — it applies to the next
	 * `user_message` only.
	 *
	 * `extra_instructions` is ADDITIVE (appended to the system prompt, and
	 * it survives a `system_prompt_override` in the same request) while
	 * `system_prompt_override` REPLACES the whole spine. The additive block
	 * composes BELOW any tenant-wide block and can never clear it.
	 *
	 * The parameter is typed against the named `RunOverrides` wire
	 * interface (NOT `Record<string, unknown>`) so `tsc` rejects a phantom
	 * key at author time — a stray key would otherwise 400 the whole
	 * request at the runtime's `DisallowUnknownFields()` decoder (D-223).
	 */
	setOverrides<R = unknown>(overrides: RunOverrides): Promise<R> {
		return this.#t.request<R>('/v1/runs/set_overrides', { overrides });
	}
}

/**
 * The `runtime.*` namespace — the read-only posture surface the Console
 * Overview page (Phase 73a / D-127) consumes. Phase 73a ships NO new
 * Protocol method: `runtime.counters` and `runtime.health` are already
 * shipped (Phase 72f / D-111) on the `PostureSurface`. Posture methods
 * route through the control transport — the Runtime mounts them at
 * `POST /v1/control/runtime.{counters,health}` (`methods.IsPostureMethod`
 * branches the route table). Both are pure reads; identity is mandatory
 * and a cross-tenant read requires `auth.ScopeAdmin` (D-079).
 */
export class RuntimeNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `runtime.counters` — the low-cardinality live-counter rollup. */
	counters(): Promise<RuntimeCounters> {
		return this.#t.request<RuntimeCounters>('/v1/control/runtime.counters', {});
	}
	/** `runtime.health` — the per-subsystem readiness rollup. */
	health(): Promise<RuntimeHealth> {
		return this.#t.request<RuntimeHealth>('/v1/control/runtime.health', {});
	}
}

/**
 * The `metrics.*` namespace — the read-only `metrics.snapshot` projection
 * over the telemetry MetricsRegistry (counters / histograms / the runtime
 * observability gauges). Already shipped on the Runtime (Phase 72f
 * PostureSurface); the gauges land on it via the runtime-gauge seam. Like
 * the other posture methods it routes through the control transport at
 * `POST /v1/control/metrics.snapshot` (`methods.IsPostureMethod`). A pure
 * read; identity is mandatory and a cross-tenant read requires
 * `auth.ScopeAdmin` (D-079).
 */
export class MetricsNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `metrics.snapshot` — the current-instant counter/gauge/histogram read. */
	snapshot(): Promise<MetricsSnapshot> {
		return this.#t.request<MetricsSnapshot>('/v1/control/metrics.snapshot', {});
	}
}

/**
 * The `pause.*` namespace — the read-only pause-snapshot surface the
 * Console Overview-page intervention queue (Phase 73a / D-127)
 * consumes. Phase 73a ships NO new Protocol method: `pause.list` is
 * already shipped (Phase 72e / D-110) at `POST /v1/pause/list`. It is a
 * READ-ONLY snapshot — it does NOT mutate the Coordinator registry and
 * does NOT call Resume. The intervention queue's Approve / Reject row
 * actions invoke the SHIPPED Phase 54 `approve` / `reject` control
 * verbs through {@link ControlNamespace} — there is no parallel pause
 * mutation here (CLAUDE.md §13). Identity is mandatory; a cross-tenant
 * filter requires the verified `auth.ScopeAdmin` claim (D-079).
 */
export class PauseNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `pause.list` — the paginated, identity-scope-filtered pause snapshot. */
	list(req: PauseListRequest = {}): Promise<PauseListResponse> {
		return this.#t.request<PauseListResponse>(
			'/v1/pause/list',
			req as unknown as Record<string, unknown>
		);
	}
}

/**
 * The `runtime.*` / `governance.posture` / `llm.posture` posture
 * namespace — consumed by the Console Settings page (Phase 73m / D-129).
 * The five `runtime.*` / `metrics.*` reads are shipped by Phase 72f
 * (D-111); `governance.posture` / `llm.posture` by Phase 72g (D-112).
 * The Runtime mounts all seven on the control surface at
 * `POST /v1/control/{method}`. Phase 73m is a pure CONSUMER — it ships
 * none of these methods, it only reads them.
 */
export class PostureNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `runtime.info` — build identity + Protocol version + uptime + capabilities. */
	info<R = unknown>(): Promise<R> {
		return this.#t.request<R>('/v1/control/runtime.info', {});
	}
	/** `runtime.health` — per-subsystem readiness rollup. */
	health<R = unknown>(): Promise<R> {
		return this.#t.request<R>('/v1/control/runtime.health', {});
	}
	/** `runtime.drivers` — configured driver name per persistence-shaped subsystem. */
	drivers<R = unknown>(): Promise<R> {
		return this.#t.request<R>('/v1/control/runtime.drivers', {});
	}
	/** `governance.posture` — the read-only D-081 IdentityTiers view. */
	governance<R = unknown>(): Promise<R> {
		return this.#t.request<R>('/v1/control/governance.posture', {});
	}
	/** `llm.posture` — bound LLM provider / model / region + the MockMode flag. */
	llm<R = unknown>(): Promise<R> {
		return this.#t.request<R>('/v1/control/llm.posture', {});
	}
}

/**
 * The `auth.*` namespace — Phase 73m / D-129. The Runtime mounts the
 * single net-new method at `POST /v1/auth/{verb}`. `auth.rotate_token`
 * is an ADMIN method: the Runtime gates it on the verified
 * `auth.ScopeAdmin` claim (D-079).
 */
export class AuthNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/**
	 * `auth.rotate_token` — rotate the operator's Protocol-auth token.
	 * Returns the one-time-revealed re-minted token. ADMIN-gated:
	 * a connection without the admin scope claim gets a
	 * `ProtocolError` carrying `identity_scope_required` (HTTP 403).
	 */
	rotateToken<R = unknown>(): Promise<R> {
		return this.#t.request<R>('/v1/auth/rotate_token', {});
	}
}

/**
 * The admin-scoped `governance.*` tenant-override namespace — Phase 92b /
 * D-232. An admin reads + writes a tenant's default LLM parameters live
 * (no redeploy); the change lands on every session's next run. Both
 * methods are ADMIN-gated: a connection without the verified
 * `auth.ScopeAdmin` claim gets a `ProtocolError` carrying `scope_mismatch`
 * (HTTP 403). The tenant is the connection's verified tenant — the
 * Transport folds the identity triple into the body; callers send only
 * the override payload.
 */
export class GovernanceNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `governance.get_tenant_overrides` — read the tenant's current default overrides. */
	getTenantOverrides(): Promise<GovernanceGetTenantOverridesResponse> {
		return this.#t.request<GovernanceGetTenantOverridesResponse>(
			'/v1/governance/get_tenant_overrides',
			{},
		);
	}
	/** `governance.set_tenant_overrides` — set (or clear) the tenant's default overrides. */
	setTenantOverrides(
		overrides: GovernanceTenantOverrides,
	): Promise<GovernanceSetTenantOverridesResponse> {
		return this.#t.request<GovernanceSetTenantOverridesResponse>(
			'/v1/governance/set_tenant_overrides',
			{ overrides: overrides as unknown as Record<string, unknown> },
		);
	}
	/**
	 * `governance.set_posture` — write the identity-tier policy table (a FULL
	 * REPLACE). Admin-scoped (auth.ScopeAdmin ONLY). The request wire type
	 * carries no identity field (authority is server-side, from the verified
	 * session), and the handler decodes it with `DisallowUnknownFields` — so
	 * this call MUST opt out of the Transport's default body identity fold
	 * (`omitBodyIdentity`), otherwise the folded `identity` key is rejected with
	 * `unknown field "identity"` (HTTP 400). Identity still rides the
	 * `X-Harbor-*` headers. A table that omits or zeroes a currently-enforced
	 * ceiling is rejected fail-closed (`invalid_request`, HTTP 400).
	 */
	setPosture(req: GovernanceSetPostureRequest): Promise<GovernanceSetPostureResponse> {
		return this.#t.request<GovernanceSetPostureResponse>(
			'/v1/governance/set_posture',
			{
				default_tier: req.default_tier,
				identity_tiers: req.identity_tiers as unknown as Record<string, unknown>,
			},
			'POST',
			{ omitBodyIdentity: true },
		);
	}
}

/**
 * The admin-scoped `agent_config.*` namespace — the agent-config control
 * plane (D-234/D-235). An admin versions an agent's config (skills now)
 * with diff + rollback; the change lands on the agent's next run. Every
 * method is ADMIN-gated: a connection without the verified
 * `auth.ScopeAdmin` claim gets a `ProtocolError` carrying `scope_mismatch`
 * (HTTP 403). The Transport folds the identity triple into the body;
 * callers send only the agent id + payload. The skills routes use the
 * `skills/*` sub-path (the `agent_config.skills.*` methods).
 */
export class AgentConfigNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/** `agent_config.get` — read the agent's active config revision. */
	get(agentId: string): Promise<AgentConfigGetResponse> {
		return this.#t.request<AgentConfigGetResponse>('/v1/agent_config/get', {
			agent_id: agentId,
		});
	}
	/** `agent_config.set_revision` — write a new revision. */
	setRevision(
		agentId: string,
		payload: AgentConfigPayload,
	): Promise<AgentConfigSetRevisionResponse> {
		return this.#t.request<AgentConfigSetRevisionResponse>('/v1/agent_config/set_revision', {
			agent_id: agentId,
			payload: payload as unknown as Record<string, unknown>,
		});
	}
	/** `agent_config.list_revisions` — the agent's revision chain, newest-first. */
	listRevisions(agentId: string, limit = 0): Promise<AgentConfigListRevisionsResponse> {
		return this.#t.request<AgentConfigListRevisionsResponse>('/v1/agent_config/list_revisions', {
			agent_id: agentId,
			limit,
		});
	}
	/** `agent_config.diff` — compare two existing revisions. */
	diff(
		agentId: string,
		fromRevision: string,
		toRevision: string,
	): Promise<AgentConfigDiffResponse> {
		return this.#t.request<AgentConfigDiffResponse>('/v1/agent_config/diff', {
			agent_id: agentId,
			from_revision: fromRevision,
			to_revision: toRevision,
		});
	}
	/** `agent_config.rollback` — repoint the active pointer to a revision. */
	rollback(agentId: string, revisionId: string): Promise<AgentConfigRollbackResponse> {
		return this.#t.request<AgentConfigRollbackResponse>('/v1/agent_config/rollback', {
			agent_id: agentId,
			revision_id: revisionId,
		});
	}
	/** `agent_config.set_tool_exposure` — set MCP pause/resume + per-tool
	 * policy (desired-state replace of the tool-exposure section); records a
	 * revision + emits `mcp.connection.paused` / `.resumed`. */
	setToolExposure(
		agentId: string,
		toolExposure: AgentConfigToolExposure,
	): Promise<AgentConfigSetToolExposureResponse> {
		return this.#t.request<AgentConfigSetToolExposureResponse>(
			'/v1/agent_config/set_tool_exposure',
			{
				agent_id: agentId,
				tool_exposure: toolExposure as unknown as Record<string, unknown>,
			},
		);
	}
	/** `agent_config.set_prompt_layers` — set the layered system prompt
	 * (operator base and/or user layer) as a desired-state replace of the
	 * prompt-layer section; records a revision. The user layer composes above
	 * the base in the lower-trust position; it can never replace or weaken the
	 * operator base. The skills + tool-exposure sections are preserved. */
	setPromptLayers(
		agentId: string,
		promptLayers: AgentConfigPromptLayers,
	): Promise<AgentConfigSetPromptLayersResponse> {
		return this.#t.request<AgentConfigSetPromptLayersResponse>(
			'/v1/agent_config/set_prompt_layers',
			{
				agent_id: agentId,
				prompt_layers: promptLayers as unknown as Record<string, unknown>,
			},
		);
	}
	/** `agent_config.set_extra_system_blocks` — set the ORDERED list of named
	 * additive prompt blocks as a WHOLE-SECTION desired-state replace; records
	 * a revision. Every sibling section is preserved; an empty list clears the
	 * section. The declared array order IS the render order and is part of the
	 * content hash, so a re-ordering is a real revision the diff reports. The
	 * bodies render VERBATIM behind a plain-text `[name]` label and survive a
	 * session `system_prompt_override`. Admin-scoped — that tier IS the trust
	 * boundary; a block must never carry user-authored text.
	 *
	 * Pass `expectedContentHash` (the `content_hash` from the
	 * `agent_config.get` this edit was composed against) so a concurrent
	 * contributor's write is refused with `revision_conflict` rather than
	 * silently reverted. */
	setExtraSystemBlocks(
		agentId: string,
		extraSystemBlocks: AgentConfigExtraSystemBlocks,
		expectedContentHash?: string,
	): Promise<AgentConfigSetExtraSystemBlocksResponse> {
		const body: Record<string, unknown> = {
			agent_id: agentId,
			extra_system_blocks: extraSystemBlocks as unknown as Record<string, unknown>,
		};
		if (expectedContentHash) {
			body.expected_content_hash = expectedContentHash;
		}
		return this.#t.request<AgentConfigSetExtraSystemBlocksResponse>(
			'/v1/agent_config/set_extra_system_blocks',
			body,
		);
	}
	/** `agent_config.set_llm_params` — set the per-agent LLM-parameter section
	 * (model / temperature / max-tokens / reasoning-effort) as a desired-state
	 * replace of the LLM-params section; records a revision. The prompt-layer +
	 * skills + tool-exposure + connection sections are preserved. A set model is
	 * validated against the configured ModelProfiles at set time. The per-agent
	 * params override the tenant-wide baseline for the agent's next run. */
	setLlmParams(
		agentId: string,
		llmParams: AgentConfigLLMParams,
	): Promise<AgentConfigSetLLMParamsResponse> {
		return this.#t.request<AgentConfigSetLLMParamsResponse>(
			'/v1/agent_config/set_llm_params',
			{
				agent_id: agentId,
				llm_params: llmParams as unknown as Record<string, unknown>,
			},
		);
	}
	/** `agent_config.add_mcp_connection` — add a NEW MCP server connection
	 * (the async dial + initialize handshake + possible OAuth path); records a
	 * revision + emits the `mcp.connection.*` lifecycle events. `headers` are
	 * used ONLY for the live attach and are never persisted. */
	addMcpConnection(
		agentId: string,
		connection: AgentConfigMCPConnectionDescriptor,
		headers?: Record<string, string>,
	): Promise<AgentConfigAddMCPConnectionResponse> {
		const body: Record<string, unknown> = {
			agent_id: agentId,
			connection: connection as unknown as Record<string, unknown>,
		};
		if (headers) {
			body.headers = headers;
		}
		return this.#t.request<AgentConfigAddMCPConnectionResponse>(
			'/v1/agent_config/add_mcp_connection',
			body,
		);
	}
	/** `agent_config.remove_mcp_connection` — remove a runtime-added MCP server
	 * connection by name; records a revision (dropping the descriptor + pruning
	 * that server's tool-exposure residue) + emits `mcp.connection.removed`. The
	 * physical detach happens at the next run's projection boundary. An unknown
	 * or boot-declared (yaml) name fails loud with a distinct error. */
	removeMcpConnection(
		agentId: string,
		name: string,
	): Promise<AgentConfigRemoveMCPConnectionResponse> {
		return this.#t.request<AgentConfigRemoveMCPConnectionResponse>(
			'/v1/agent_config/remove_mcp_connection',
			{ agent_id: agentId, name },
		);
	}
	/** `agent_config.set_mcp_discovery_origins` — FULL-REPLACE a runtime-added MCP
	 * connection's OAuth-discovery cross-origin allow-list. Records a revision AND
	 * applies the allow-list to the live registry (a revoke prunes the recorded
	 * requirement's now-unallowed authorization-server entries). Admin-scoped. An
	 * unknown / boot-declared / stdio connection fails loud with a distinct error. */
	setMcpDiscoveryOrigins(
		agentId: string,
		name: string,
		allowedOrigins: string[],
	): Promise<AgentConfigSetMCPDiscoveryOriginsResponse> {
		return this.#t.request<AgentConfigSetMCPDiscoveryOriginsResponse>(
			'/v1/agent_config/set_mcp_discovery_origins',
			{ agent_id: agentId, name, allowed_origins: allowedOrigins },
		);
	}
	/** `agent_config.set_oauth_provider` — install (upsert) a ZERO-URL, broker-pull
	 * OAuth provider. The descriptor carries only {name, driver, credential_source,
	 * credential_broker, scopes?}; a URL / env-var / secret field is rejected by the
	 * wire edge. Records a revision AND installs the provider live. Admin-scoped. */
	setOAuthProvider(
		agentId: string,
		provider: AgentConfigOAuthProviderDescriptor,
	): Promise<AgentConfigSetOAuthProviderResponse> {
		return this.#t.request<AgentConfigSetOAuthProviderResponse>(
			'/v1/agent_config/set_oauth_provider',
			{ agent_id: agentId, provider },
		);
	}
	/** `agent_config.register_oauth_mcp_capability` — atomically prepare,
	 * persist, and activate one signed OAuth MCP pair. The signed envelope is
	 * write-only; callers receive only the committed immutable revision view. */
	registerOAuthMCPCapability(
		agentId: string,
		providerName: string,
		broker: string,
		audience: string,
		scopes: string[],
		connection: SignedOAuthMCPConnectionDescriptor,
		authorityEnvelope: string,
		expectedContentHash?: string,
	): Promise<AgentConfigRegisterOAuthMCPCapabilityResponse> {
		return this.#t.request<AgentConfigRegisterOAuthMCPCapabilityResponse>(
			'/v1/agent_config/register_oauth_mcp_capability',
			{ agent_id: agentId, provider_name: providerName, broker, audience, scopes, connection, authority_envelope: authorityEnvelope, expected_content_hash: expectedContentHash },
		);
	}
	/** `agent_config.remove_oauth_mcp_capability` — atomically withdraw the
	 * server-owned pair through its durable lifetime receipt. */
	removeOAuthMCPCapability(
		agentId: string,
		expectedContentHash: string,
	): Promise<AgentConfigRemoveOAuthMCPCapabilityResponse> {
		return this.#t.request<AgentConfigRemoveOAuthMCPCapabilityResponse>(
			'/v1/agent_config/remove_oauth_mcp_capability',
			{ agent_id: agentId, expected_content_hash: expectedContentHash },
		);
	}
	/** `agent_config.remove_oauth_provider` — uninstall a Protocol-installed OAuth
	 * provider by name; records a revision AND uninstalls it live (CLOSING it, so a
	 * still-bound connection's next call fails loud). Admin-scoped. An unknown or
	 * boot-declared name fails loud with a distinct error. */
	removeOAuthProvider(
		agentId: string,
		name: string,
	): Promise<AgentConfigRemoveOAuthProviderResponse> {
		return this.#t.request<AgentConfigRemoveOAuthProviderResponse>(
			'/v1/agent_config/remove_oauth_provider',
			{ agent_id: agentId, name },
		);
	}
	/** `agent_config.set_llm_provider` — install (upsert) / rotate a ZERO-URL,
	 * broker-pull inference provider binding. A separate method from
	 * set_oauth_provider (a distinct credential plane). The descriptor carries only
	 * {name, provider, credential_source, inference_broker, model_allow?}; a URL /
	 * env-var / secret field is rejected by the wire edge. Admin-scoped. */
	setLLMProvider(
		agentId: string,
		provider: AgentConfigLLMProviderDescriptor,
	): Promise<AgentConfigSetLLMProviderResponse> {
		return this.#t.request<AgentConfigSetLLMProviderResponse>(
			'/v1/agent_config/set_llm_provider',
			{ agent_id: agentId, provider },
		);
	}
	/** `agent_config.skills.list` — list the agent's skills (metadata only). */
	skillsList(agentId: string): Promise<AgentConfigSkillsListResponse> {
		return this.#t.request<AgentConfigSkillsListResponse>('/v1/agent_config/skills/list', {
			agent_id: agentId,
		});
	}
	/** `agent_config.skills.upsert` — upsert a skill; records a revision. */
	skillsUpsert(
		agentId: string,
		skill: AgentConfigSkillInput,
	): Promise<AgentConfigSkillsUpsertResponse> {
		return this.#t.request<AgentConfigSkillsUpsertResponse>('/v1/agent_config/skills/upsert', {
			agent_id: agentId,
			skill: skill as unknown as Record<string, unknown>,
		});
	}
	/** `agent_config.skills.delete` — delete a skill; records a revision. */
	skillsDelete(agentId: string, name: string): Promise<AgentConfigSkillsDeleteResponse> {
		return this.#t.request<AgentConfigSkillsDeleteResponse>('/v1/agent_config/skills/delete', {
			agent_id: agentId,
			name,
		});
	}

	// --- Session-user safe subset (the non-admin lower tier). These verbs
	// require a valid identity but NOT the admin scope. ---

	/** `agent_config.session.set_user_prompt` — set the SESSION user prompt
	 * layer (composes ABOVE the operator base; never the base). Non-admin. */
	sessionSetUserPrompt(
		agentId: string,
		userPrompt: string,
	): Promise<AgentConfigSessionSetUserPromptResponse> {
		return this.#t.request<AgentConfigSessionSetUserPromptResponse>(
			'/v1/agent_config/session/set_user_prompt',
			{ agent_id: agentId, user_prompt: userPrompt },
		);
	}
	/** `agent_config.session.set_source_disables` — NARROW-only source/tool
	 * disable within the admin-allowed set (unioned into the admin exclusion
	 * set at run start; never widens). Non-admin. */
	sessionSetSourceDisables(
		agentId: string,
		disabledServers?: string[],
		disabledTools?: string[],
	): Promise<AgentConfigSessionSetSourceDisablesResponse> {
		return this.#t.request<AgentConfigSessionSetSourceDisablesResponse>(
			'/v1/agent_config/session/set_source_disables',
			{
				agent_id: agentId,
				disabled_servers: disabledServers,
				disabled_tools: disabledTools,
			},
		);
	}
	/** `agent_config.session.skills.list` — list the session's ephemeral
	 * personal skills (metadata only). Non-admin. */
	sessionSkillsList(agentId: string): Promise<AgentConfigSessionSkillsListResponse> {
		return this.#t.request<AgentConfigSessionSkillsListResponse>(
			'/v1/agent_config/session/skills/list',
			{ agent_id: agentId },
		);
	}
	/** `agent_config.session.skills.upsert` — upsert an ephemeral personal
	 * skill (session-scoped; never promotes). Non-admin. */
	sessionSkillsUpsert(
		agentId: string,
		skill: AgentConfigSkillInput,
	): Promise<AgentConfigSessionSkillsUpsertResponse> {
		return this.#t.request<AgentConfigSessionSkillsUpsertResponse>(
			'/v1/agent_config/session/skills/upsert',
			{ agent_id: agentId, skill: skill as unknown as Record<string, unknown> },
		);
	}
	/** `agent_config.session.skills.delete` — delete an ephemeral personal
	 * skill. Non-admin. */
	sessionSkillsDelete(
		agentId: string,
		name: string,
	): Promise<AgentConfigSessionSkillsDeleteResponse> {
		return this.#t.request<AgentConfigSessionSkillsDeleteResponse>(
			'/v1/agent_config/session/skills/delete',
			{ agent_id: agentId, name },
		);
	}

	// --- User tier (the durable per-user config variant — the middle tier).
	// Requires the `agent_config:user` scope claim (NOT admin). ---

	/** `agent_config.user.get` — read the caller's OWN durable config variant
	 * active revision. User-tier (requires the `agent_config:user` scope). */
	userGet(agentId: string): Promise<AgentConfigUserGetResponse> {
		return this.#t.request<AgentConfigUserGetResponse>('/v1/agent_config/user/get', {
			agent_id: agentId,
		});
	}
	/** `agent_config.user.set_revision` — write a new revision of the caller's
	 * durable variant from the bounded safe-subset payload. User-tier. */
	userSetRevision(
		agentId: string,
		payload: AgentConfigUserPayload,
	): Promise<AgentConfigUserSetRevisionResponse> {
		return this.#t.request<AgentConfigUserSetRevisionResponse>(
			'/v1/agent_config/user/set_revision',
			{ agent_id: agentId, payload: payload as unknown as Record<string, unknown> },
		);
	}
	/** `agent_config.user.list_revisions` — the caller's own variant revision
	 * chain, newest-first. User-tier. */
	userListRevisions(
		agentId: string,
		limit?: number,
	): Promise<AgentConfigUserListRevisionsResponse> {
		return this.#t.request<AgentConfigUserListRevisionsResponse>(
			'/v1/agent_config/user/list_revisions',
			{ agent_id: agentId, limit },
		);
	}
	/** `agent_config.user.diff` — compare two existing revisions of the
	 * caller's own variant. User-tier. */
	userDiff(
		agentId: string,
		fromRevision: string,
		toRevision: string,
	): Promise<AgentConfigUserDiffResponse> {
		return this.#t.request<AgentConfigUserDiffResponse>('/v1/agent_config/user/diff', {
			agent_id: agentId,
			from_revision: fromRevision,
			to_revision: toRevision,
		});
	}
	/** `agent_config.user.rollback` — repoint the caller's own variant active
	 * pointer to an existing revision. User-tier. */
	userRollback(
		agentId: string,
		revisionId: string,
	): Promise<AgentConfigUserRollbackResponse> {
		return this.#t.request<AgentConfigUserRollbackResponse>(
			'/v1/agent_config/user/rollback',
			{ agent_id: agentId, revision_id: revisionId },
		);
	}

	// --- Durable-per-user skills (CLAIM-FREE — a valid identity is enough;
	// `user` names the durable STORAGE scope, not an auth tier). ---

	/** `agent_config.user.skills.list` — list the caller's durable user-scope
	 * personal skills (visible across ALL of their conversations). Claim-free. */
	userSkillsList(agentId: string): Promise<AgentConfigUserSkillsListResponse> {
		return this.#t.request<AgentConfigUserSkillsListResponse>(
			'/v1/agent_config/user/skills/list',
			{ agent_id: agentId },
		);
	}
	/** `agent_config.user.skills.upsert` — upsert a DURABLE personal skill
	 * (scope forced to user server-side; persists across conversations).
	 * Claim-free. */
	userSkillsUpsert(
		agentId: string,
		skill: AgentConfigSkillInput,
	): Promise<AgentConfigUserSkillsUpsertResponse> {
		return this.#t.request<AgentConfigUserSkillsUpsertResponse>(
			'/v1/agent_config/user/skills/upsert',
			{ agent_id: agentId, skill: skill as unknown as Record<string, unknown> },
		);
	}
	/** `agent_config.user.skills.delete` — delete one of the caller's durable
	 * user-scope personal skills. Claim-free. */
	userSkillsDelete(
		agentId: string,
		name: string,
	): Promise<AgentConfigUserSkillsDeleteResponse> {
		return this.#t.request<AgentConfigUserSkillsDeleteResponse>(
			'/v1/agent_config/user/skills/delete',
			{ agent_id: agentId, name },
		);
	}
}

/**
 * The `search.*` namespace — the shipped global-search surface (Phase
 * 72c). Consumed by the app-shell top-bar ⌘K launcher (Phase 108b). The
 * Runtime mounts `search.query` on the control surface at
 * `POST /v1/control/search.query` (verified live — `/v1/search/query` is
 * NOT mounted; `methods.IsControlMethod` branches the route table). The
 * four per-index methods exist too but the launcher uses the fan-out
 * `query`. Pure read; identity mandatory; cross-tenant requires the
 * verified `auth.ScopeAdmin` claim (D-079).
 */
export class SearchNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/**
	 * `search.query` — fan-out across sessions/tasks/events/artifacts.
	 *
	 * Passes `omitBodyIdentity`: `SearchRequest` scopes through `filter` and
	 * declares NO `identity` field, so the transport's default fold would add
	 * a member the wire type does not define — refused `unknown field
	 * "identity"` (400) under the strict control-transport decode (D-374).
	 * Identity still rides the `X-Harbor-*` headers, and the search handler
	 * does its own identity defaulting + cross-tenant gating on `filter`.
	 * No e2e spec covers this call, so it is the one site in this class that
	 * would have failed in production rather than in CI.
	 */
	query(req: SearchRequest = {}): Promise<SearchResponse> {
		return this.#t.request<SearchResponse>(
			'/v1/control/search.query',
			req as unknown as Record<string, unknown>,
			'POST',
			{ omitBodyIdentity: true }
		);
	}
}

/**
 * The `state.*` namespace — the State-snapshots surface (D-254). The
 * Runtime mounts `state.history` at `POST /v1/state/history`. It is a
 * by-id, identity-scoped, read-only TAIL-FIRST windowed read of a session's
 * durable event stream: a bounded backward page with a scroll-up cursor,
 * heavy content carried by a routable `StateArtifactRef`. The events →
 * chat-messages reduction stays client-side (the reducer the Console owns).
 */
export class StateNamespace {
	readonly #t: Transport;
	constructor(t: Transport) {
		this.#t = t;
	}
	/**
	 * `state.history` — a bounded, tail-first window of a session's durable
	 * event stream. `before` is the exclusive upper bound (zero ⇒ from the
	 * tail); pass the prior response's `next_cursor` back as `before` to
	 * scroll one window older.
	 */
	history(req: StateHistoryRequest): Promise<StateHistoryResponse> {
		return this.#t.request<StateHistoryResponse>(
			'/v1/state/history',
			req as unknown as Record<string, unknown>
		);
	}
}

/** The `mcp` namespace — groups the MCP-server surface. */
export class MCPNamespace {
	/** The `mcp.servers.*` method surface. */
	readonly servers: MCPServersNamespace;
	/** The `mcp.apps.*` method surface — the MCP Apps host's tool-call proxy. */
	readonly apps: MCPAppsNamespace;
	constructor(t: Transport) {
		this.servers = new MCPServersNamespace(t);
		this.apps = new MCPAppsNamespace(t);
	}
}

/* ------------------------------------------------------------------ */
/* ProtocolClient interface + HarborClient                             */
/* ------------------------------------------------------------------ */

/**
 * The injectable Protocol-client interface. A page depends on THIS interface,
 * never on the concrete `HarborClient` — tests and the Playwright harness
 * inject a deterministic in-page implementation (CONVENTIONS.md §6).
 */
export interface ProtocolClient {
	readonly tools: ToolsNamespace;
	readonly tasks: TasksNamespace;
	readonly control: ControlNamespace;
	readonly memory: MemoryNamespace;
	readonly flows: FlowsNamespace;
	readonly artifacts: ArtifactsNamespace;
	readonly mcp: MCPNamespace;
	readonly events: EventsNamespace;
	readonly agents: AgentsNamespace;
	readonly sessions: SessionsNamespace;
	readonly topology: TopologyNamespace;
	readonly runs: RunsNamespace;
	readonly runtime: RuntimeNamespace;
	readonly metrics: MetricsNamespace;
	readonly pause: PauseNamespace;
	readonly posture: PostureNamespace;
	readonly auth: AuthNamespace;
	readonly governance: GovernanceNamespace;
	readonly agentConfig: AgentConfigNamespace;
	readonly search: SearchNamespace;
	readonly state: StateNamespace;

	/**
	 * Round-8 F1 / phase 84a: returns the per-instance Protocol
	 * capabilities the runtime advertises (memoised per client). Pages
	 * with optional surfaces gate their fetches on
	 * `caps.has('topology_snapshot')` etc.
	 */
	capabilities(): Promise<ReadonlySet<string>>;
}

/**
 * The unified production Protocol client. ONE class, ONE `fetch` choke point
 * (the shared {@link Transport}), method namespaces hanging off it. Constructed
 * once from a resolved {@link RuntimeConnection}; immutable after construction.
 *
 * A page resolves its connection via `connection.ts`, constructs a
 * `HarborClient`, and calls `client.<namespace>.<method>(...)`. New page
 * surfaces add a namespace here — never a new top-level client.
 */
export class HarborClient implements ProtocolClient {
	readonly tools: ToolsNamespace;
	readonly tasks: TasksNamespace;
	readonly control: ControlNamespace;
	readonly memory: MemoryNamespace;
	readonly flows: FlowsNamespace;
	readonly artifacts: ArtifactsNamespace;
	readonly mcp: MCPNamespace;
	readonly events: EventsNamespace;
	readonly agents: AgentsNamespace;
	readonly sessions: SessionsNamespace;
	readonly topology: TopologyNamespace;
	readonly runs: RunsNamespace;
	readonly runtime: RuntimeNamespace;
	readonly metrics: MetricsNamespace;
	readonly pause: PauseNamespace;
	readonly posture: PostureNamespace;
	readonly auth: AuthNamespace;
	readonly governance: GovernanceNamespace;
	readonly agentConfig: AgentConfigNamespace;
	readonly search: SearchNamespace;
	readonly state: StateNamespace;

	// Round-8 F1 / phase 84a: per-connection capability cache. Pages
	// with optional Protocol surfaces (Live Runtime topology view,
	// Playground topology trace) consult this BEFORE calling
	// `topology.snapshot` / similar, so the browser console stays
	// clean on planner/RunLoop runtimes that don't advertise the
	// surface. Lazy-loaded on first `capabilities()` call; the
	// returned Set is immutable, the resolution memoised for the
	// lifetime of the client (a re-attach builds a new HarborClient).
	#capsCache: Promise<ReadonlySet<string>> | null = null;

	constructor(opts: HarborClientOptions) {
		const transport = new Transport(opts);
		this.tools = new ToolsNamespace(transport);
		this.tasks = new TasksNamespace(transport);
		this.control = new ControlNamespace(transport);
		this.memory = new MemoryNamespace(transport);
		this.flows = new FlowsNamespace(transport);
		this.artifacts = new ArtifactsNamespace(transport);
		this.mcp = new MCPNamespace(transport);
		this.events = new EventsNamespace(transport);
		this.agents = new AgentsNamespace(transport);
		this.sessions = new SessionsNamespace(transport);
		this.topology = new TopologyNamespace(transport);
		this.runs = new RunsNamespace(transport);
		this.runtime = new RuntimeNamespace(transport);
		this.metrics = new MetricsNamespace(transport);
		this.pause = new PauseNamespace(transport);
		this.posture = new PostureNamespace(transport);
		this.auth = new AuthNamespace(transport);
		this.governance = new GovernanceNamespace(transport);
		this.agentConfig = new AgentConfigNamespace(transport);
		this.search = new SearchNamespace(transport);
		this.state = new StateNamespace(transport);
	}

	/**
	 * Returns the runtime's advertised capability set, fetched once per
	 * client and memoised. Pages with optional Protocol surfaces call
	 * `await client.capabilities()` then branch on `caps.has('...')`
	 * instead of eagerly invoking a method the runtime might not
	 * advertise. Round-8 F1 / phase 84a.
	 *
	 * The fetch goes through `posture.info` (the SHIPPED Phase 72f
	 * surface, every runtime advertises it). A network failure rejects
	 * the promise; the resolved Set is frozen.
	 */
	capabilities(): Promise<ReadonlySet<string>> {
		if (this.#capsCache !== null) {
			return this.#capsCache;
		}
		this.#capsCache = this.posture
			.info<{ capabilities?: string[] }>()
			.then((info) => new Set<string>(info.capabilities ?? []));
		return this.#capsCache;
	}
}
