/**
 * Typed Harbor Protocol client surface for the Console Tools page
 * (Phase 73f / D-116).
 *
 * # Why this file is hand-authored
 *
 * The canonical typed client `src/lib/protocol.ts` is generated by
 * `cmd/harbor-gen-protocol-ts` (D-093). That generator has not yet
 * shipped — Phase 72h committed `protocol.ts` as a typed stub. Until
 * the generator lands, per-page Protocol surfaces are hand-authored in
 * a sibling module so they stay OUT of the generated file (editing the
 * `DO NOT EDIT` stub would be reverted by the first regeneration).
 *
 * The wire shapes here mirror `internal/protocol/types/tools.go`
 * field-for-field (the Go-side single source per D-002). When the
 * generator ships, these types are absorbed into `protocol.ts` and
 * this module re-exports from there — a mechanical migration.
 *
 * # No hand-rolled `fetch` in components (CLAUDE.md §4.5 rule 5)
 *
 * `.svelte` components NEVER call `fetch` directly. They construct a
 * `ToolsClient` (this module's typed surface) and call its methods. The
 * single `fetch` call site lives in `toolsRequest` below.
 */

/** The (tenant, user, session) identity triple carried by every request. */
export interface ToolsIdentityScope {
  tenant: string;
  user: string;
  session: string;
}

/** Wire enum — a tool's transport. */
export type ToolTransport = 'in-proc' | 'HTTP' | 'MCP' | 'A2A' | 'flow';

/** Wire enum — a tool's OAuth binding status. */
export type ToolOAuthStatus = 'Bound' | 'Required' | 'Expired' | 'n/a';

/** Wire enum — a tool's approval gate. */
export type ToolApprovalPolicy = 'auto' | 'gated' | 'denied';

/** Wire enum — a tool's health pill. */
export type ToolStatus = 'Healthy' | 'Degraded' | 'Offline';

/** Wire enum — the `tools.metrics` observation window. */
export type ToolMetricsWindow = '1h' | '24h' | '7d';

/** The catalog-row projection of a registered tool. */
export interface Tool {
  id: string;
  name: string;
  version: string;
  description: string;
  scope: string;
  transport: ToolTransport;
  oauth_status: ToolOAuthStatus;
  approval_policy: ToolApprovalPolicy;
  reliability_tier: string;
  owner: string;
  last_used_at: string;
}

/** Server-enforced facet filter on `tools.list`. */
export interface ToolFilter {
  scopes?: string[];
  transports?: ToolTransport[];
  oauth_statuses?: ToolOAuthStatus[];
  approval_policies?: ToolApprovalPolicy[];
  reliability_tiers?: string[];
  search?: string;
}

/** The four catalog counters over the filtered view. */
export interface ToolAggregates {
  total: number;
  active: number;
  pending_approval: number;
  awaiting_oauth: number;
}

/** The `tools.list` reply. */
export interface ToolListResponse {
  tools: Tool[];
  page: number;
  page_size: number;
  page_count: number;
  total_rows: number;
  aggregates: ToolAggregates;
}

/** The full descriptor projection `tools.describe` returns. */
export interface ToolManifest {
  tool: Tool;
  side_effect: string;
  args_schema: string;
  out_schema: string;
  examples: string[];
  auth_scopes: string[];
  oauth_binding_scope: string;
  retry_attempts: number;
  timeout_ms: number;
  loading_mode: string;
  display_modes: Record<string, string>;
}

/** The `tools.metrics` reply. */
export interface ToolMetrics {
  id: string;
  window: ToolMetricsWindow;
  error_rate_1h: number;
  error_rate_24h: number;
  error_rate_7d: number;
  invocations: number;
  failures: number;
  status: ToolStatus;
}

/** One power-of-two size bucket in the result-size histogram. */
export interface ToolContentBucket {
  max_bytes: number;
  count: number;
}

/** The `tools.content_stats` reply. */
export interface ToolContentStats {
  id: string;
  histogram: ToolContentBucket[];
  heavy_threshold_bytes: number;
  heavy_count: number;
  negotiated_display: Record<string, string>;
}

/** The `tools.set_approval_policy` reply. */
export interface ToolSetApprovalPolicyResponse {
  id: string;
  policy: ToolApprovalPolicy;
}

/** The `tools.revoke_oauth` reply. */
export interface ToolRevokeOAuthResponse {
  id: string;
  revoked_count: number;
}

/** A canonical Protocol error body. */
export interface ProtocolError {
  code: string;
  message: string;
}

/** Thrown by the client when the Runtime returns a non-2xx Protocol error. */
export class ToolsProtocolError extends Error {
  readonly code: string;
  readonly status: number;
  constructor(status: number, body: ProtocolError) {
    super(body.message || `tools protocol error ${body.code}`);
    this.name = 'ToolsProtocolError';
    this.code = body.code;
    this.status = status;
  }
}

/** Configuration the Tools client needs to reach the Runtime. */
export interface ToolsClientConfig {
  /** The Runtime's Protocol base URL (e.g. `http://127.0.0.1:18080`). */
  baseURL: string;
  /** The bearer token attached to every request. */
  token: string;
  /** The active identity triple. */
  identity: ToolsIdentityScope;
  /**
   * The `fetch` implementation. Defaults to `globalThis.fetch`; tests
   * inject a stub so the client is exercised without a live Runtime.
   */
  fetchImpl?: typeof fetch;
}

/**
 * The typed Tools Protocol client. The single `fetch` choke point for
 * every `tools.*` method — `.svelte` components depend on this surface,
 * never on `fetch` directly.
 */
export class ToolsClient {
  readonly #cfg: ToolsClientConfig;
  readonly #fetch: typeof fetch;

  constructor(cfg: ToolsClientConfig) {
    this.#cfg = cfg;
    this.#fetch = cfg.fetchImpl ?? globalThis.fetch.bind(globalThis);
  }

  /** `tools.list` — paginated, faceted catalog projection. */
  async list(
    filter: ToolFilter = {},
    page = 1,
    pageSize = 50
  ): Promise<ToolListResponse> {
    return this.#post<ToolListResponse>('list', {
      filter,
      page,
      page_size: pageSize
    });
  }

  /** `tools.get` — single catalog-row projection. */
  async get(id: string): Promise<Tool> {
    return this.#post<Tool>('get', { id });
  }

  /** `tools.describe` — full manifest projection. */
  async describe(id: string): Promise<ToolManifest> {
    return this.#post<ToolManifest>('describe', { id });
  }

  /** `tools.metrics` — per-tool error-rate gauges + status pill. */
  async metrics(id: string, window: ToolMetricsWindow = '1h'): Promise<ToolMetrics> {
    return this.#post<ToolMetrics>('metrics', { id, window });
  }

  /** `tools.content_stats` — per-tool result-size histogram. */
  async contentStats(id: string): Promise<ToolContentStats> {
    return this.#post<ToolContentStats>('content_stats', { id });
  }

  /**
   * `tools.set_approval_policy` — ADMIN method. Requires the verified
   * `admin` scope claim (D-079); a non-admin caller gets a
   * `ToolsProtocolError` with `code === 'identity_scope_required'`.
   */
  async setApprovalPolicy(
    id: string,
    policy: ToolApprovalPolicy
  ): Promise<ToolSetApprovalPolicyResponse> {
    return this.#post<ToolSetApprovalPolicyResponse>('set_approval_policy', {
      id,
      policy
    });
  }

  /**
   * `tools.revoke_oauth` — ADMIN method. Requires the verified `admin`
   * scope claim (D-079).
   */
  async revokeOAuth(id: string): Promise<ToolRevokeOAuthResponse> {
    return this.#post<ToolRevokeOAuthResponse>('revoke_oauth', { id });
  }

  /** The single `fetch` choke point for the seven `tools.*` methods. */
  async #post<T>(verb: string, payload: Record<string, unknown>): Promise<T> {
    const body = JSON.stringify({
      identity: this.#cfg.identity,
      ...payload
    });
    const resp = await this.#fetch(`${this.#cfg.baseURL}/v1/tools/${verb}`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${this.#cfg.token}`,
        'Content-Type': 'application/json'
      },
      body
    });
    const text = await resp.text();
    if (!resp.ok) {
      let err: ProtocolError = { code: 'runtime_error', message: text };
      try {
        err = JSON.parse(text) as ProtocolError;
      } catch {
        // Non-JSON error body — keep the raw text as the message.
      }
      throw new ToolsProtocolError(resp.status, err);
    }
    return JSON.parse(text) as T;
  }
}
