// Command harbor-gen-protocol-docs emits the four generated Protocol
// contract-reference pages (`methods.md` / `events.md` / `errors.md` /
// `types.md`) into docs/site/protocol/ from the canonical single
// sources the Runtime compiles from (RFC §5):
//
//   - internal/protocol/methods — the canonical method registry + the
//     Is*Method classification predicates.
//   - internal/protocol/transports/{control,stream} — the exported
//     *RoutePattern constants the methods page joins against, plus the
//     control transport's HTTPStatus error-code → status binding.
//   - internal/protocol/errors — the canonical error-code set.
//   - internal/protocol/singlesource.CanonicalWireTypes — the wire-type
//     inventory, rendered field-by-field via reflection.
//   - internal/events — the canonical event-type registry, populated by
//     blank-importing internal/drivers/prod (the §4.4 production
//     aggregator; proposal Q1 resolved as registry-read) plus the
//     payload-declaring packages the eventPayloadIndex references.
//
// The output is deterministic (sorted iteration everywhere) so the
// `make protocol-docs-gen-check` gate — `git diff --exit-code` over
// docs/site/protocol/ after a regeneration — is byte-stable. Generated
// pages carry a DO-NOT-EDIT header and are never hand-edited; a Go-side
// change to a method / error code / event type / wire type without a
// regenerated reference fails CI (the gate shape specified for
// the deferred TS client generator, built here for a generator that
// exists).
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
)

// generatedHeader is the first line of every emitted page. The phase
// smoke and the §18 drift rule grep for it; hand-editing a page that
// carries it is rejection-on-sight.
const generatedHeader = "<!-- CODE GENERATED BY cmd/harbor-gen-protocol-docs. DO NOT EDIT. -->"

func main() {
	out := flag.String("out", "docs/site/protocol", "output directory for the generated reference pages")
	flag.Parse()

	if err := run(*out); err != nil {
		fmt.Fprintf(os.Stderr, "harbor-gen-protocol-docs: %v\n", err)
		os.Exit(1)
	}
}

// run renders the four pages and writes them under outDir. It is the
// whole program behind the flag surface, split out so tests drive it
// against a t.TempDir().
func run(outDir string) error {
	pages := map[string]func() (string, error){
		"methods.md": renderMethodsPage,
		"events.md":  renderEventsPage,
		"errors.md":  renderErrorsPage,
		"types.md":   renderTypesPage,
	}

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("create output dir %q: %w", outDir, err)
	}

	// Deterministic write order (sorted file names) so failures
	// reproduce identically.
	for _, name := range []string{"errors.md", "events.md", "methods.md", "types.md"} {
		content, err := pages[name]()
		if err != nil {
			return fmt.Errorf("render %s: %w", name, err)
		}
		path := filepath.Join(outDir, name)
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
		fmt.Printf("harbor-gen-protocol-docs: wrote %s\n", path)
	}
	return nil
}
