// Harbor Console e2e harness — typed Protocol helper (Phase 75 / D-115).
//
// Per-page specs that need to seed Runtime state (create a session, list
// tasks, ...) MUST call the typed Protocol client — never a hand-rolled raw
// browser HTTP call. A hand-rolled HTTP call in `.svelte` files OR specs is a
// §13 forbidden practice (CLAUDE.md §4.5 #11): the wire shapes are generated,
// so a raw call silently rots when `CanonicalWireTypes` changes.
//
// The canonical typed client lives at `web/console/src/lib/protocol.ts`. That
// file is CODE-GENERATED by `cmd/harbor-gen-protocol-ts` from
// `internal/protocol/singlesource.CanonicalWireTypes` (D-093) and is created
// by the Stage-1 SvelteKit-scaffold phase (72h). Until that phase lands, the
// generated module is absent; this helper therefore loads it lazily so the
// harness baseline type-checks and the meta-test can SKIP cleanly rather than
// fail with a missing-module compile error.
//
// Once 72h has merged, per-page specs import `protocolClient` from here and
// call `client.<method>(...)` with the generated typed wire shapes.

/**
 * The minimal Protocol client surface the harness depends on. The full typed
 * surface is the generated `web/console/src/lib/protocol.ts`; this interface
 * is the subset the harness fixtures inject. Per-page specs widen it by
 * importing the generated `ProtocolClient` type directly once 72h has landed.
 */
export interface ProtocolClient {
  /** The base URL the client targets (the ephemeral `harbor console` URL). */
  readonly baseURL: string;
}

/**
 * Lazily load the generated Protocol client module. Returns `null` when the
 * generated `src/lib/protocol.ts` is not yet present (pre-72h) so the harness
 * meta-test can SKIP rather than crash.
 *
 * Per-page specs (Stage 2) call this once the scaffold has landed; by then
 * the dynamic import always resolves and the `null` branch is dead.
 */
export async function loadGeneratedProtocol(): Promise<unknown | null> {
  try {
    // The generated module is created by cmd/harbor-gen-protocol-ts (D-093)
    // and shipped by the Stage-1 SvelteKit scaffold phase (72h). The dynamic
    // import keeps the harness baseline buildable before that phase lands.
    return await import("../../src/lib/protocol");
  } catch {
    // Module not yet generated — pre-72h. The caller treats this as SKIP.
    return null;
  }
}

/**
 * True when the generated Protocol client is present and the harness can
 * exercise typed calls. The harness meta-test gates its Protocol-round-trip
 * assertions on this so it SKIPs cleanly before the Stage-1 scaffold lands.
 */
export async function generatedProtocolAvailable(): Promise<boolean> {
  return (await loadGeneratedProtocol()) !== null;
}
